import ShielddGnarkFormal.Deployed.Contracts.NoteReshape1x8.Seg78
import ShielddGnarkFormal.Deployed.Contracts.NoteReshape1x8.Seg79

set_option maxRecDepth 1000000
set_option maxHeartbeats 1000000

/-! Exact final-state and public-assertion statement seating facts.
GENERATED by gen_note_reshape_1x8_statement_seating.py — do not edit. -/

namespace Shieldd.GnarkFormal.Deployed.NoteReshape1x8StatementSeating

open Contracts.NoteReshape1x8

theorem hw1415 : Seg78.wireSeating 1415 = 40443 := by decide +kernel
theorem hw1420 : Seg78.wireSeating 1420 = 40448 := by decide +kernel
theorem hw1425 : Seg78.wireSeating 1425 = 40453 := by decide +kernel
theorem hw1430 : Seg78.wireSeating 1430 = 40458 := by decide +kernel
theorem hw1435 : Seg78.wireSeating 1435 = 40463 := by decide +kernel
theorem hw1440 : Seg78.wireSeating 1440 = 40468 := by decide +kernel
theorem hw1445 : Seg78.wireSeating 1445 = 40473 := by decide +kernel
theorem hw1450 : Seg78.wireSeating 1450 = 40478 := by decide +kernel

end Shieldd.GnarkFormal.Deployed.NoteReshape1x8StatementSeating

namespace Shieldd.GnarkFormal.Deployed.NoteReshape1x8StatementPublicSeating

open Contracts.NoteReshape1x8

theorem hw1 : Seg79.wireSeating 1 = 40443 := by decide +kernel
theorem hw2 : Seg79.wireSeating 2 = 40448 := by decide +kernel
theorem hw3 : Seg79.wireSeating 3 = 40453 := by decide +kernel
theorem hw4 : Seg79.wireSeating 4 = 40458 := by decide +kernel
theorem hw5 : Seg79.wireSeating 5 = 40463 := by decide +kernel
theorem hw6 : Seg79.wireSeating 6 = 40468 := by decide +kernel
theorem hw7 : Seg79.wireSeating 7 = 40473 := by decide +kernel
theorem hw8 : Seg79.wireSeating 8 = 40478 := by decide +kernel
theorem hw9 : Seg79.wireSeating 9 = 1 := by decide +kernel

end Shieldd.GnarkFormal.Deployed.NoteReshape1x8StatementPublicSeating
