syntax = "proto3";
package shieldd.core.component.governance.v1;

import "shieldd/core/keys/v1/keys.proto";
import "shieldd/core/component/compliance/v1/compliance.proto";
import "shieldd/crypto/decaf377_rdsa/v1/decaf377_rdsa.proto";

message ProposalSubmit {
  // The proposal to be submitted.
  governance.v1.Proposal proposal = 1;
  // The validator identity submitting the proposal.
  keys.v1.IdentityKey proposer = 4;
  // The governance key authorizing the proposal submission.
  keys.v1.GovernanceKey governance_key = 5;
  // The proposal submission authorization signature.
  shieldd.crypto.decaf377_rdsa.v1.SpendAuthSignature auth_sig = 6;
}

message ProposalSubmitBody {
  // The proposal to be submitted.
  governance.v1.Proposal proposal = 1;
  // The validator identity submitting the proposal.
  keys.v1.IdentityKey proposer = 2;
  // The governance key authorizing the proposal submission.
  keys.v1.GovernanceKey governance_key = 3;
}

message ValidatorVote {
  // The effecting data for the vote.
  ValidatorVoteBody body = 1;
  // The vote authorization signature is authorizing data.
  shieldd.crypto.decaf377_rdsa.v1.SpendAuthSignature auth_sig = 2;
}

message ValidatorVoteReason {
  string reason = 1;
}

message ValidatorVoteBody {
  // The proposal being voted on.
  uint64 proposal = 1;
  // The vote.
  governance.v1.Vote vote = 2;
  // The validator identity.
  keys.v1.IdentityKey identity_key = 3;
  // The validator governance key.
  keys.v1.GovernanceKey governance_key = 4;
  // A justification of the vote.
  ValidatorVoteReason reason = 5;
}

// A vote on a proposal.
message Vote {
  // A vote.
  enum Vote {
    VOTE_UNSPECIFIED = 0;
    VOTE_ABSTAIN = 1;
    VOTE_YES = 2;
    VOTE_NO = 3;
  }

  // The vote.
  Vote vote = 1;
}

// The current state of a proposal.
message ProposalState {
  // Voting is in progress and the proposal has not yet concluded voting.
  message Voting {}

  // The voting period has ended, and the proposal has been assigned an outcome.
  message Finished {
    ProposalOutcome outcome = 1;
  }

  // The state of the proposal.
  oneof state {
    Voting voting = 2;
    Finished finished = 4;
  }
}

// The outcome of a concluded proposal.
message ProposalOutcome {
  // The proposal was passed.
  message Passed {}

  // The proposal did not pass.
  message Failed {}

  // The proposal did not pass, and was slashed.
  message Slashed {}

  oneof outcome {
    Passed passed = 1;
    Failed failed = 2;
    Slashed slashed = 3;
  }
}

// A tally of votes on a proposal.
message Tally {
  // The number of votes in favor of the proposal.
  uint64 yes = 1;
  // The number of votes against the proposal.
  uint64 no = 2;
  // The number of abstentions.
  uint64 abstain = 3;
}

// A proposal to be voted upon.
message Proposal {
  // The unique identifier of the proposal.
  uint64 id = 4;

  // A short title for the proposal.
  string title = 1;

  // A natural-language description of the effect of the proposal and its justification.
  string description = 2;

  // The proposal's payload.
  oneof payload {
    Signaling signaling = 5;
    Emergency emergency = 6;
    ParameterChange parameter_change = 7;
    UpgradePlan upgrade_plan = 9;
    FreezeIbcClient freeze_ibc_client = 10;
    UnfreezeIbcClient unfreeze_ibc_client = 11;
    compliance.v1.UpdateAssetIbcPolicy update_asset_ibc_policy = 12;
  }

  // A signaling proposal is meant to register a vote on-chain, but does not have an automatic
  // effect when passed.
  //
  // It optionally contains a reference to a commit which contains code to upgrade the chain.
  message Signaling {
    // The commit to be voted upon, if any is relevant.
    string commit = 1;
  }

  // An emergency proposal can be passed instantaneously by a 1/3 majority of validators, without
  // waiting for the voting period to expire.
  //
  // If the boolean `halt_chain` is set to `true`, then the chain will halt immediately when the
  // proposal is passed.
  message Emergency {
    // If `true`, the chain will halt immediately when the proposal is passed.
    bool halt_chain = 1;
  }

  // A parameter change proposal describes a replacement of the app parameters, which should take
  // effect when the proposal is passed.
  message ParameterChange {
    // A list of encoded preconditions for the parameter change: even if the
    // proposal passes, the update will not be applied if the value of the
    // precondition does not match the proposal at the time it is enacted.
    //
    // This can be empty, in which case the changes will be applied
    // unconditionally.
    repeated EncodedParameter preconditions = 3;

    // A list of encoded changes to the application parameters.
    repeated EncodedParameter changes = 4;
  }

  // An upgrade plan describes a candidate upgrade to be executed at a certain height. If passed, the chain
  // will halt at the specified height.
  message UpgradePlan {
    uint64 height = 1;
  }

  // Freeze an existing IBC client.
  // Like `Emergency` proposals, it is enacted immediately after receiving
  // +2/3 of validator votes.
  message FreezeIbcClient {
    string client_id = 1;
  }

  // Unfreeze an existing IBC client.
  // Like `Emergency` proposals, it is enacted immediately after receiving
  // +2/3 of validator votes.
  message UnfreezeIbcClient {
    string client_id = 1;
  }
}

// All the different kinds of proposals.
enum ProposalKind {
  // To make the linter happy
  PROPOSAL_KIND_UNSPECIFIED = 0;
  PROPOSAL_KIND_SIGNALING = 1;
  PROPOSAL_KIND_EMERGENCY = 2;
  PROPOSAL_KIND_PARAMETER_CHANGE = 3;
  PROPOSAL_KIND_UPGRADE_PLAN = 5;
  PROPOSAL_KIND_FREEZE_IBC_CLIENT = 6;
  PROPOSAL_KIND_UNFREEZE_IBC_CLIENT = 7;
  PROPOSAL_KIND_UPDATE_ASSET_IBC_POLICY = 8;
}

// Query operations for the governance component.
service QueryService {
  rpc ProposalInfo(ProposalInfoRequest) returns (ProposalInfoResponse);
  rpc ProposalList(ProposalListRequest) returns (stream ProposalListResponse);
  rpc ProposalData(ProposalDataRequest) returns (ProposalDataResponse);
  rpc NextProposalId(NextProposalIdRequest) returns (NextProposalIdResponse);
  rpc ValidatorVotes(ValidatorVotesRequest) returns (stream ValidatorVotesResponse);
  rpc VotingPowerAtProposalStart(VotingPowerAtProposalStartRequest) returns (VotingPowerAtProposalStartResponse);
}

message ProposalInfoRequest {
  // The proposal id to request information on.
  uint64 proposal_id = 2;
}

message ProposalInfoResponse {
  // The block height at which the proposal started voting.
  uint64 start_block_height = 1;
  // The position of the state commitment tree at which the proposal is considered to have started voting.
  uint64 start_position = 2;
}

message ProposalDataRequest {
  // The proposal id to request information on.
  uint64 proposal_id = 2;
}

message ProposalDataResponse {
  // The proposal metadata.
  Proposal proposal = 1;
  // The block height at which the proposal started voting.
  uint64 start_block_height = 2;
  // The block height at which the proposal ends voting.
  uint64 end_block_height = 3;
  // The position of the state commitment tree at which the proposal is considered to have started voting.
  uint64 start_position = 4;
  // The current state of the proposal.
  ProposalState state = 5;
}

// Requests the list of all proposals.
message ProposalListRequest {
  // Whether to include proposals that are no longer active.;
  bool inactive = 2;
  // TODO: we could filter by starting block height here?
}

// The data for a single proposal.
message ProposalListResponse {
  // The proposal metadata.
  Proposal proposal = 1;
  // The block height at which the proposal started voting.
  uint64 start_block_height = 2;
  // The block height at which the proposal ends voting.
  uint64 end_block_height = 3;
  // The position of the state commitment tree at which the proposal is considered to have started voting.
  uint64 start_position = 4;
  // The current state of the proposal.
  ProposalState state = 5;
}

// Requests the list of all validator votes for a given proposal.
message ValidatorVotesRequest {
  // The proposal id to request information on.
  uint64 proposal_id = 2;
}

// The data for a single validator vote.
message ValidatorVotesResponse {
  // The vote.
  governance.v1.Vote vote = 1;
  // The validator identity.
  keys.v1.IdentityKey identity_key = 2;
}

// Governance configuration data.
message GovernanceParameters {
  // The number of blocks during which a proposal is voted on.
  uint64 proposal_voting_blocks = 1;
  // The quorum required for a proposal to be considered valid, as a fraction of the total stake
  // weight of the network.
  string proposal_valid_quorum = 3;
  // The threshold for a proposal to pass voting, as a ratio of "yes" votes over "no" votes.
  string proposal_pass_threshold = 4;
  // The threshold for a proposal to be slashed, regardless of whether the "yes" and "no" votes
  // would have passed it, as a ratio of "no" votes over all total votes.
  string proposal_slash_threshold = 5;
}

// Governance genesis state.
message GenesisContent {
  // Governance parameters.
  GovernanceParameters governance_params = 1;
}

message EncodedParameter {
  // The component name in the `AppParameters`.
  //
  // This is the ProtoJSON-produced key in the `AppParameters` structure.
  string component = 1;
  // The parameter key in the component parameters.
  //
  // This is the ProtoJSON-produced field name in the component's substructure.
  string key = 2;
  // The parameter value.
  //
  // This is the ProtoJSON-encoded value of the parameter.
  string value = 3;
}

message VotingPowerAtProposalStartRequest {
  // The proposal id to request information on.
  uint64 proposal_id = 2;
  // The validator identity key to request information on.
  keys.v1.IdentityKey identity_key = 3;
}

message VotingPowerAtProposalStartResponse {
  // The voting power for the given identity key at the start of the proposal.
  // TODO: since we don't support optional fields in our protos any more,
  // this will be set to 0 if the validator was not active at the start of the proposal.
  // Is this potentially an issue?
  uint64 voting_power = 1;
}

message NextProposalIdRequest {}

message NextProposalIdResponse {
  // The next proposal ID.
  uint64 next_proposal_id = 1;
}

// The ratio between two numbers, used in governance to describe vote thresholds and quorums.
message Ratio {
  // The numerator.
  uint64 numerator = 1;
  // The denominator.
  uint64 denominator = 2;
}

message EventValidatorVote {
  // The validator vote.
  ValidatorVote vote = 1;
  // The validator's voting power at the time of the proposal's start.
  uint64 voting_power = 2;
}

message EventProposalSubmit {
  // Details on the submitted proposal.
  ProposalSubmit submit = 1;
  // The start height for the proposal.
  uint64 start_height = 2;
  // The end height for the proposal.
  uint64 end_height = 3;
}

message EventProposalPassed {
  // The passed proposal.
  Proposal proposal = 1;
}

message EventProposalFailed {
  // The failed proposal.
  Proposal proposal = 1;
}

message EventProposalSlashed {
  // The slashed proposal.
  Proposal proposal = 1;
}
