/-
GENERATED by gen/gen_nb_slice.py — do not edit by hand.
-/
import ShielddGnarkFormal.Deployed.Contracts.Consolidate2x1.NbAdapterSeg46BlindDefs

set_option maxRecDepth 1000000
set_option maxHeartbeats 20000000
set_option linter.unusedVariables false

namespace Shieldd.GnarkFormal.Deployed.Contracts.Consolidate2x1

theorem seg46Blind_rows191 (rho : Nat -> Seg46.F) (h : Seg46.relation rho) :
    Seg46.relationRow579 rho ∧ Seg46.relationRow1713 rho ∧ Seg46.relationRow1714 rho ∧ Seg46.relationRow1715 rho ∧ Seg46.relationRow1716 rho ∧ Seg46.relationRow1717 rho ∧ Seg46.relationRow1718 rho ∧ Seg46.relationRow1719 rho ∧ Seg46.relationRow1720 rho := by
  unfold Seg46.relation at h

  rcases h with ⟨

    _, _, _, _, _, _, _, p7, _, _,

    _, _, _, _, _, _, _, _, _, _,

    _, p21, _, _, _, _, _, _

  ⟩

  unfold Seg46.relationPart7 at p7

  rcases p7 with ⟨_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, r579, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _⟩

  unfold Seg46.relationPart21 at p21

  rcases p21 with ⟨_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, r1713, r1714, r1715, r1716, r1717, r1718, r1719, r1720, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _⟩

  exact ⟨r579, r1713, r1714, r1715, r1716, r1717, r1718, r1719, r1720⟩

theorem seg46Blind_rung191 (rho : Nat -> Seg46.F) (h : Seg46.relation rho)
    (bit : Bool) (hbitValue : rho 31852 = Bool.toZMod bit)
    (hacc : EdwardsBridge.onCurve (seg46BlindAccState rho 191)) :
    Shieldd.GnarkFormal.Deployed.NetBalance.NbFixedStepRel
      191 (Bool.toZMod bit) (seg46BlindAccState rho 191)
      (seg46BlindAccState rho 192) := by
  obtain ⟨r579, r1713, r1714, r1715, r1716, r1717, r1718, r1719, r1720⟩ := seg46Blind_rows191 rho h
  unfold Seg46.relationRow579 at r579

  unfold Seg46.relationRow1713 at r1713

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r1713

  unfold Seg46.relationRow1714 at r1714

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r1714

  unfold Seg46.relationRow1715 at r1715

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r1715

  unfold Seg46.relationRow1716 at r1716

  unfold Seg46.relationRow1717 at r1717

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r1717

  unfold Seg46.relationRow1718 at r1718

  unfold Seg46.relationRow1719 at r1719

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r1719

  unfold Seg46.relationRow1720 at r1720

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r1720

  have hnextx : seg46BlindDeltaX191 rho =
      seg46BlindDeltaX190 rho + rho 32991 := by
    unfold seg46BlindDeltaX191 seg46BlindDeltaX190
    rw [Shieldd.GnarkFormal.StrideRun.sumAux_succ rho 32663 8 41]

    ring

  have hnexty : seg46BlindDeltaY191 rho =
      seg46BlindDeltaY190 rho + rho 32992 := by
    unfold seg46BlindDeltaY191 seg46BlindDeltaY190
    rw [Shieldd.GnarkFormal.StrideRun.sumAux_succ rho 32664 8 41]

    ring

  change Shieldd.GnarkFormal.Deployed.NetBalance.NbFixedStepRel 191
    (Bool.toZMod bit) ⟨((4661681602708190761543544705274244814260880986867766715334030151044279151219 : Seg46.F) * rho 31661 + seg46BlindDeltaX190 rho : Seg46.F),
      ((1 : Seg46.F) + (4337336842509898676347982752646772244181661588533917621717979456142867120377 : Seg46.F) * rho 31661 + seg46BlindDeltaY190 rho : Seg46.F)⟩
    ⟨((4661681602708190761543544705274244814260880986867766715334030151044279151219 : Seg46.F) * rho 31661 + seg46BlindDeltaX191 rho : Seg46.F),
      ((1 : Seg46.F) + (4337336842509898676347982752646772244181661588533917621717979456142867120377 : Seg46.F) * rho 31661 + seg46BlindDeltaY191 rho : Seg46.F)⟩
  rw [hnextx, hnexty, ← hbitValue]
  rw [← add_assoc ((1 : Seg46.F) + (4337336842509898676347982752646772244181661588533917621717979456142867120377 : Seg46.F) * rho 31661)
    (seg46BlindDeltaY190 rho) (rho 32992)]
  exact Shieldd.GnarkFormal.RvkFixedSplitRung.splitRung_stepRel
    (Shieldd.GnarkFormal.Deployed.NetBalance.Cb 191)
    (4661681602708190761543544705274244814260880986867766715334030151044279151219 : Seg46.F) (4337336842509898676347982752646772244181661588533917621717979456142867120377 : Seg46.F)
    (7795627490918527138041161579809081456452436047591391680037266100603945016815 : Seg46.F) (3189572002925575920347648111790343103502172016293966354214985046616570335139 : Seg46.F)
    (2540737744415732634139984752817878028578708728731294206317017691303106112913 : Seg46.F) (554556695789719013642702519139470527066643240247620509116776151269737032555 : Seg46.F)
    (566164740394201302335690568881923380160519813285528409368452626895040709138 : Seg46.F) (559200741045195250524530251089018769402279419388473271726665058493386012757 : Seg46.F)
    (7316742360078395850510735121132322818658676912321782356138261176337704907294 : Seg46.F) (6162487642510414456944286869074828711181403113579895600869964336802651405238 : Seg46.F)
    (5254889746502794503901176826991203427873727318860097473720248409300838903902 : Seg46.F) (648834258509843286207663358972465074923463287562672147897967355313464222226 : Seg46.F)
    (2281974106917955967304538069706717820194496221574168227065269119114757833803 : Seg46.F) (3782780146720179662705280233507301717115018348286297112601203304873130087822 : Seg46.F) (4107124906918471747900842186134774287194237746620146206217253999774542118664 : Seg46.F)
    (rho 31661) (seg46BlindDeltaX190 rho) (seg46BlindDeltaY190 rho) (rho 31852)
    (rho 32985) (rho 32986) (rho 32987) (rho 32989)
    (rho 32988) (rho 32990) (rho 32991) (rho 32992) hacc
    (Shieldd.GnarkFormal.Deployed.NetBalance.Cb_onCurve 191)
    (by rw [Shieldd.GnarkFormal.NbFixedBaseLiteral.C_eq_L191]; rfl)
    (by decide) (by decide) (by decide) (by decide)
    (by decide) (by decide) (by decide) (by decide) (by decide)
    (by unfold seg46BlindDeltaX190 seg46BlindDeltaY190;
        first | linear_combination r1713 | linear_combination -r1713)
    (by unfold seg46BlindDeltaX190 seg46BlindDeltaY190;
        first | linear_combination r1714 | linear_combination -r1714)
    (by unfold seg46BlindDeltaX190 seg46BlindDeltaY190;
        first | linear_combination r1715 | linear_combination -r1715)
    (by first | linear_combination r1716 | linear_combination -r1716)
    (by unfold seg46BlindDeltaX190 seg46BlindDeltaY190;
        first | linear_combination r1717 | linear_combination -r1717)
    (by first | linear_combination r1718 | linear_combination -r1718)
    (by unfold seg46BlindDeltaX190; first | linear_combination r1719 | linear_combination -r1719)
    (by unfold seg46BlindDeltaY190; first | linear_combination r1720 | linear_combination -r1720)
    (by linear_combination r579)

theorem seg46Blind_rows192 (rho : Nat -> Seg46.F) (h : Seg46.relation rho) :
    Seg46.relationRow580 rho ∧ Seg46.relationRow1721 rho ∧ Seg46.relationRow1722 rho ∧ Seg46.relationRow1723 rho ∧ Seg46.relationRow1724 rho ∧ Seg46.relationRow1725 rho ∧ Seg46.relationRow1726 rho ∧ Seg46.relationRow1727 rho ∧ Seg46.relationRow1728 rho := by
  unfold Seg46.relation at h

  rcases h with ⟨

    _, _, _, _, _, _, _, p7, _, _,

    _, _, _, _, _, _, _, _, _, _,

    _, p21, _, _, _, _, _, _

  ⟩

  unfold Seg46.relationPart7 at p7

  rcases p7 with ⟨_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, r580, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _⟩

  unfold Seg46.relationPart21 at p21

  rcases p21 with ⟨_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, r1721, r1722, r1723, r1724, r1725, r1726, r1727, r1728, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _⟩

  exact ⟨r580, r1721, r1722, r1723, r1724, r1725, r1726, r1727, r1728⟩

theorem seg46Blind_rung192 (rho : Nat -> Seg46.F) (h : Seg46.relation rho)
    (bit : Bool) (hbitValue : rho 31853 = Bool.toZMod bit)
    (hacc : EdwardsBridge.onCurve (seg46BlindAccState rho 192)) :
    Shieldd.GnarkFormal.Deployed.NetBalance.NbFixedStepRel
      192 (Bool.toZMod bit) (seg46BlindAccState rho 192)
      (seg46BlindAccState rho 193) := by
  obtain ⟨r580, r1721, r1722, r1723, r1724, r1725, r1726, r1727, r1728⟩ := seg46Blind_rows192 rho h
  unfold Seg46.relationRow580 at r580

  unfold Seg46.relationRow1721 at r1721

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r1721

  unfold Seg46.relationRow1722 at r1722

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r1722

  unfold Seg46.relationRow1723 at r1723

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r1723

  unfold Seg46.relationRow1724 at r1724

  unfold Seg46.relationRow1725 at r1725

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r1725

  unfold Seg46.relationRow1726 at r1726

  unfold Seg46.relationRow1727 at r1727

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r1727

  unfold Seg46.relationRow1728 at r1728

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r1728

  have hnextx : seg46BlindDeltaX192 rho =
      seg46BlindDeltaX191 rho + rho 32999 := by
    unfold seg46BlindDeltaX192 seg46BlindDeltaX191
    rw [Shieldd.GnarkFormal.StrideRun.sumAux_succ rho 32663 8 42]

    ring

  have hnexty : seg46BlindDeltaY192 rho =
      seg46BlindDeltaY191 rho + rho 33000 := by
    unfold seg46BlindDeltaY192 seg46BlindDeltaY191
    rw [Shieldd.GnarkFormal.StrideRun.sumAux_succ rho 32664 8 42]

    ring

  change Shieldd.GnarkFormal.Deployed.NetBalance.NbFixedStepRel 192
    (Bool.toZMod bit) ⟨((4661681602708190761543544705274244814260880986867766715334030151044279151219 : Seg46.F) * rho 31661 + seg46BlindDeltaX191 rho : Seg46.F),
      ((1 : Seg46.F) + (4337336842509898676347982752646772244181661588533917621717979456142867120377 : Seg46.F) * rho 31661 + seg46BlindDeltaY191 rho : Seg46.F)⟩
    ⟨((4661681602708190761543544705274244814260880986867766715334030151044279151219 : Seg46.F) * rho 31661 + seg46BlindDeltaX192 rho : Seg46.F),
      ((1 : Seg46.F) + (4337336842509898676347982752646772244181661588533917621717979456142867120377 : Seg46.F) * rho 31661 + seg46BlindDeltaY192 rho : Seg46.F)⟩
  rw [hnextx, hnexty, ← hbitValue]
  rw [← add_assoc ((1 : Seg46.F) + (4337336842509898676347982752646772244181661588533917621717979456142867120377 : Seg46.F) * rho 31661)
    (seg46BlindDeltaY191 rho) (rho 33000)]
  exact Shieldd.GnarkFormal.RvkFixedSplitRung.splitRung_stepRel
    (Shieldd.GnarkFormal.Deployed.NetBalance.Cb 192)
    (4661681602708190761543544705274244814260880986867766715334030151044279151219 : Seg46.F) (4337336842509898676347982752646772244181661588533917621717979456142867120377 : Seg46.F)
    (2201443287703118336923186320266692790412732967462530460839825374398628917893 : Seg46.F) (6846513832253225230347721765363986944279063983096280693769125028585801189149 : Seg46.F)
    (603495370527973143022083146849133203315897615404747326673716947067020868001 : Seg46.F) (554556695789719013642702519139470527066643240247620509116776151269737032555 : Seg46.F)
    (2831462886914251895095178088597103327474821141561661263139977815970166007720 : Seg46.F) (6629768296966429689160763288732932376564175026205222742192023532947073032112 : Seg46.F)
    (7160083176997050742282765130665319097078478313482009216028559646455803224278 : Seg46.F) (1230749160449538127066993612358232434647795025110371274904304972532004703188 : Seg46.F)
    (1597947917175145193901103173417559587096835352057783134166108427331608049892 : Seg46.F) (6243018461725252087325638618514853740963166367691533367095408081518780321148 : Seg46.F)
    (7213712588978832297181831326423314096728104310043692553030928483385404535853 : Seg46.F) (3782780146720179662705280233507301717115018348286297112601203304873130087822 : Seg46.F) (4107124906918471747900842186134774287194237746620146206217253999774542118664 : Seg46.F)
    (rho 31661) (seg46BlindDeltaX191 rho) (seg46BlindDeltaY191 rho) (rho 31853)
    (rho 32993) (rho 32994) (rho 32995) (rho 32997)
    (rho 32996) (rho 32998) (rho 32999) (rho 33000) hacc
    (Shieldd.GnarkFormal.Deployed.NetBalance.Cb_onCurve 192)
    (by rw [Shieldd.GnarkFormal.NbFixedBaseLiteral.C_eq_L192]; rfl)
    (by decide) (by decide) (by decide) (by decide)
    (by decide) (by decide) (by decide) (by decide) (by decide)
    (by unfold seg46BlindDeltaX191 seg46BlindDeltaY191;
        first | linear_combination r1721 | linear_combination -r1721)
    (by unfold seg46BlindDeltaX191 seg46BlindDeltaY191;
        first | linear_combination r1722 | linear_combination -r1722)
    (by unfold seg46BlindDeltaX191 seg46BlindDeltaY191;
        first | linear_combination r1723 | linear_combination -r1723)
    (by first | linear_combination r1724 | linear_combination -r1724)
    (by unfold seg46BlindDeltaX191 seg46BlindDeltaY191;
        first | linear_combination r1725 | linear_combination -r1725)
    (by first | linear_combination r1726 | linear_combination -r1726)
    (by unfold seg46BlindDeltaX191; first | linear_combination r1727 | linear_combination -r1727)
    (by unfold seg46BlindDeltaY191; first | linear_combination r1728 | linear_combination -r1728)
    (by linear_combination r580)

theorem seg46Blind_rows193 (rho : Nat -> Seg46.F) (h : Seg46.relation rho) :
    Seg46.relationRow581 rho ∧ Seg46.relationRow1729 rho ∧ Seg46.relationRow1730 rho ∧ Seg46.relationRow1731 rho ∧ Seg46.relationRow1732 rho ∧ Seg46.relationRow1733 rho ∧ Seg46.relationRow1734 rho ∧ Seg46.relationRow1735 rho ∧ Seg46.relationRow1736 rho := by
  unfold Seg46.relation at h

  rcases h with ⟨

    _, _, _, _, _, _, _, p7, _, _,

    _, _, _, _, _, _, _, _, _, _,

    _, p21, _, _, _, _, _, _

  ⟩

  unfold Seg46.relationPart7 at p7

  rcases p7 with ⟨_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, r581, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _⟩

  unfold Seg46.relationPart21 at p21

  rcases p21 with ⟨_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, r1729, r1730, r1731, r1732, r1733, r1734, r1735, r1736, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _⟩

  exact ⟨r581, r1729, r1730, r1731, r1732, r1733, r1734, r1735, r1736⟩

theorem seg46Blind_rung193 (rho : Nat -> Seg46.F) (h : Seg46.relation rho)
    (bit : Bool) (hbitValue : rho 31854 = Bool.toZMod bit)
    (hacc : EdwardsBridge.onCurve (seg46BlindAccState rho 193)) :
    Shieldd.GnarkFormal.Deployed.NetBalance.NbFixedStepRel
      193 (Bool.toZMod bit) (seg46BlindAccState rho 193)
      (seg46BlindAccState rho 194) := by
  obtain ⟨r581, r1729, r1730, r1731, r1732, r1733, r1734, r1735, r1736⟩ := seg46Blind_rows193 rho h
  unfold Seg46.relationRow581 at r581

  unfold Seg46.relationRow1729 at r1729

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r1729

  unfold Seg46.relationRow1730 at r1730

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r1730

  unfold Seg46.relationRow1731 at r1731

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r1731

  unfold Seg46.relationRow1732 at r1732

  unfold Seg46.relationRow1733 at r1733

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r1733

  unfold Seg46.relationRow1734 at r1734

  unfold Seg46.relationRow1735 at r1735

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r1735

  unfold Seg46.relationRow1736 at r1736

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r1736

  have hnextx : seg46BlindDeltaX193 rho =
      seg46BlindDeltaX192 rho + rho 33007 := by
    unfold seg46BlindDeltaX193 seg46BlindDeltaX192
    rw [Shieldd.GnarkFormal.StrideRun.sumAux_succ rho 32663 8 43]

    ring

  have hnexty : seg46BlindDeltaY193 rho =
      seg46BlindDeltaY192 rho + rho 33008 := by
    unfold seg46BlindDeltaY193 seg46BlindDeltaY192
    rw [Shieldd.GnarkFormal.StrideRun.sumAux_succ rho 32664 8 43]

    ring

  change Shieldd.GnarkFormal.Deployed.NetBalance.NbFixedStepRel 193
    (Bool.toZMod bit) ⟨((4661681602708190761543544705274244814260880986867766715334030151044279151219 : Seg46.F) * rho 31661 + seg46BlindDeltaX192 rho : Seg46.F),
      ((1 : Seg46.F) + (4337336842509898676347982752646772244181661588533917621717979456142867120377 : Seg46.F) * rho 31661 + seg46BlindDeltaY192 rho : Seg46.F)⟩
    ⟨((4661681602708190761543544705274244814260880986867766715334030151044279151219 : Seg46.F) * rho 31661 + seg46BlindDeltaX193 rho : Seg46.F),
      ((1 : Seg46.F) + (4337336842509898676347982752646772244181661588533917621717979456142867120377 : Seg46.F) * rho 31661 + seg46BlindDeltaY193 rho : Seg46.F)⟩
  rw [hnextx, hnexty, ← hbitValue]
  rw [← add_assoc ((1 : Seg46.F) + (4337336842509898676347982752646772244181661588533917621717979456142867120377 : Seg46.F) * rho 31661)
    (seg46BlindDeltaY192 rho) (rho 33008)]
  exact Shieldd.GnarkFormal.RvkFixedSplitRung.splitRung_stepRel
    (Shieldd.GnarkFormal.Deployed.NetBalance.Cb 193)
    (4661681602708190761543544705274244814260880986867766715334030151044279151219 : Seg46.F) (4337336842509898676347982752646772244181661588533917621717979456142867120377 : Seg46.F)
    (8379505003927404927120020956400071289170845704972341444623697570956102475621 : Seg46.F) (8222636974042191456093926116742032547305962112844880315099558006378415146841 : Seg46.F)
    (8157680228541225958965122134360557305100908482663157931788022121417108383421 : Seg46.F) (554556695789719013642702519139470527066643240247620509116776151269737032555 : Seg46.F)
    (5424293512622971143956653721151976634791598216281713958243143416091586587080 : Seg46.F) (1159492356918577458388895628832242118290019297883964640947573388330292787616 : Seg46.F)
    (7398689112597503690364031459430454241780594976319482742382007271263098015962 : Seg46.F) (5425623735987271667172610899632063110025184545561162617297158795099787645232 : Seg46.F)
    (221824775386178968154898822039513984069937222309183512835675449538994092200 : Seg46.F) (64956745500965497128803982381475242205053630181722383311535884961306763420 : Seg46.F)
    (3018838013441098757076214039149483421350714789592901210638074660817621593809 : Seg46.F) (3782780146720179662705280233507301717115018348286297112601203304873130087822 : Seg46.F) (4107124906918471747900842186134774287194237746620146206217253999774542118664 : Seg46.F)
    (rho 31661) (seg46BlindDeltaX192 rho) (seg46BlindDeltaY192 rho) (rho 31854)
    (rho 33001) (rho 33002) (rho 33003) (rho 33005)
    (rho 33004) (rho 33006) (rho 33007) (rho 33008) hacc
    (Shieldd.GnarkFormal.Deployed.NetBalance.Cb_onCurve 193)
    (by rw [Shieldd.GnarkFormal.NbFixedBaseLiteral.C_eq_L193]; rfl)
    (by decide) (by decide) (by decide) (by decide)
    (by decide) (by decide) (by decide) (by decide) (by decide)
    (by unfold seg46BlindDeltaX192 seg46BlindDeltaY192;
        first | linear_combination r1729 | linear_combination -r1729)
    (by unfold seg46BlindDeltaX192 seg46BlindDeltaY192;
        first | linear_combination r1730 | linear_combination -r1730)
    (by unfold seg46BlindDeltaX192 seg46BlindDeltaY192;
        first | linear_combination r1731 | linear_combination -r1731)
    (by first | linear_combination r1732 | linear_combination -r1732)
    (by unfold seg46BlindDeltaX192 seg46BlindDeltaY192;
        first | linear_combination r1733 | linear_combination -r1733)
    (by first | linear_combination r1734 | linear_combination -r1734)
    (by unfold seg46BlindDeltaX192; first | linear_combination r1735 | linear_combination -r1735)
    (by unfold seg46BlindDeltaY192; first | linear_combination r1736 | linear_combination -r1736)
    (by linear_combination r581)

theorem seg46Blind_rows194 (rho : Nat -> Seg46.F) (h : Seg46.relation rho) :
    Seg46.relationRow582 rho ∧ Seg46.relationRow1737 rho ∧ Seg46.relationRow1738 rho ∧ Seg46.relationRow1739 rho ∧ Seg46.relationRow1740 rho ∧ Seg46.relationRow1741 rho ∧ Seg46.relationRow1742 rho ∧ Seg46.relationRow1743 rho ∧ Seg46.relationRow1744 rho := by
  unfold Seg46.relation at h

  rcases h with ⟨

    _, _, _, _, _, _, _, p7, _, _,

    _, _, _, _, _, _, _, _, _, _,

    _, p21, _, _, _, _, _, _

  ⟩

  unfold Seg46.relationPart7 at p7

  rcases p7 with ⟨_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, r582, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _⟩

  unfold Seg46.relationPart21 at p21

  rcases p21 with ⟨_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, r1737, r1738, r1739, r1740, r1741, r1742, r1743, r1744, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _⟩

  exact ⟨r582, r1737, r1738, r1739, r1740, r1741, r1742, r1743, r1744⟩

theorem seg46Blind_rung194 (rho : Nat -> Seg46.F) (h : Seg46.relation rho)
    (bit : Bool) (hbitValue : rho 31855 = Bool.toZMod bit)
    (hacc : EdwardsBridge.onCurve (seg46BlindAccState rho 194)) :
    Shieldd.GnarkFormal.Deployed.NetBalance.NbFixedStepRel
      194 (Bool.toZMod bit) (seg46BlindAccState rho 194)
      (seg46BlindAccState rho 195) := by
  obtain ⟨r582, r1737, r1738, r1739, r1740, r1741, r1742, r1743, r1744⟩ := seg46Blind_rows194 rho h
  unfold Seg46.relationRow582 at r582

  unfold Seg46.relationRow1737 at r1737

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r1737

  unfold Seg46.relationRow1738 at r1738

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r1738

  unfold Seg46.relationRow1739 at r1739

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r1739

  unfold Seg46.relationRow1740 at r1740

  unfold Seg46.relationRow1741 at r1741

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r1741

  unfold Seg46.relationRow1742 at r1742

  unfold Seg46.relationRow1743 at r1743

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r1743

  unfold Seg46.relationRow1744 at r1744

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r1744

  have hnextx : seg46BlindDeltaX194 rho =
      seg46BlindDeltaX193 rho + rho 33015 := by
    unfold seg46BlindDeltaX194 seg46BlindDeltaX193
    rw [Shieldd.GnarkFormal.StrideRun.sumAux_succ rho 32663 8 44]

    ring

  have hnexty : seg46BlindDeltaY194 rho =
      seg46BlindDeltaY193 rho + rho 33016 := by
    unfold seg46BlindDeltaY194 seg46BlindDeltaY193
    rw [Shieldd.GnarkFormal.StrideRun.sumAux_succ rho 32664 8 44]

    ring

  change Shieldd.GnarkFormal.Deployed.NetBalance.NbFixedStepRel 194
    (Bool.toZMod bit) ⟨((4661681602708190761543544705274244814260880986867766715334030151044279151219 : Seg46.F) * rho 31661 + seg46BlindDeltaX193 rho : Seg46.F),
      ((1 : Seg46.F) + (4337336842509898676347982752646772244181661588533917621717979456142867120377 : Seg46.F) * rho 31661 + seg46BlindDeltaY193 rho : Seg46.F)⟩
    ⟨((4661681602708190761543544705274244814260880986867766715334030151044279151219 : Seg46.F) * rho 31661 + seg46BlindDeltaX194 rho : Seg46.F),
      ((1 : Seg46.F) + (4337336842509898676347982752646772244181661588533917621717979456142867120377 : Seg46.F) * rho 31661 + seg46BlindDeltaY194 rho : Seg46.F)⟩
  rw [hnextx, hnexty, ← hbitValue]
  rw [← add_assoc ((1 : Seg46.F) + (4337336842509898676347982752646772244181661588533917621717979456142867120377 : Seg46.F) * rho 31661)
    (seg46BlindDeltaY193 rho) (rho 33016)]
  exact Shieldd.GnarkFormal.RvkFixedSplitRung.splitRung_stepRel
    (Shieldd.GnarkFormal.Deployed.NetBalance.Cb 194)
    (4661681602708190761543544705274244814260880986867766715334030151044279151219 : Seg46.F) (4337336842509898676347982752646772244181661588533917621717979456142867120377 : Seg46.F)
    (6444490698300857073481181944246794033469722497984396226284135138276924131970 : Seg46.F) (8198823652717836620711767586720711280439202192284079120380256009977844066466 : Seg46.F)
    (6198852601590323269944124592185958782533025355114411518729157692337358959395 : Seg46.F) (554556695789719013642702519139470527066643240247620509116776151269737032555 : Seg46.F)
    (1039943787173976848446334036992801681317072883333815334713679937305626686533 : Seg46.F) (7763323733134130071288516841185356454533071645192017275536901946325694198167 : Seg46.F)
    (5978637330494813918645192268005069037660298137679939836064151660217248578339 : Seg46.F) (3745004071372151816914715129910381229435807440401535650340004072402749506166 : Seg46.F)
    (245638096710533803537057352060835250936697142869984707554977445939565172575 : Seg46.F) (1999971051127513350767642994534752497906176837169667601651098317640485107071 : Seg46.F)
    (4699457678056218607334109808871165301940091894752528177595229383514659732875 : Seg46.F) (3782780146720179662705280233507301717115018348286297112601203304873130087822 : Seg46.F) (4107124906918471747900842186134774287194237746620146206217253999774542118664 : Seg46.F)
    (rho 31661) (seg46BlindDeltaX193 rho) (seg46BlindDeltaY193 rho) (rho 31855)
    (rho 33009) (rho 33010) (rho 33011) (rho 33013)
    (rho 33012) (rho 33014) (rho 33015) (rho 33016) hacc
    (Shieldd.GnarkFormal.Deployed.NetBalance.Cb_onCurve 194)
    (by rw [Shieldd.GnarkFormal.NbFixedBaseLiteral.C_eq_L194]; rfl)
    (by decide) (by decide) (by decide) (by decide)
    (by decide) (by decide) (by decide) (by decide) (by decide)
    (by unfold seg46BlindDeltaX193 seg46BlindDeltaY193;
        first | linear_combination r1737 | linear_combination -r1737)
    (by unfold seg46BlindDeltaX193 seg46BlindDeltaY193;
        first | linear_combination r1738 | linear_combination -r1738)
    (by unfold seg46BlindDeltaX193 seg46BlindDeltaY193;
        first | linear_combination r1739 | linear_combination -r1739)
    (by first | linear_combination r1740 | linear_combination -r1740)
    (by unfold seg46BlindDeltaX193 seg46BlindDeltaY193;
        first | linear_combination r1741 | linear_combination -r1741)
    (by first | linear_combination r1742 | linear_combination -r1742)
    (by unfold seg46BlindDeltaX193; first | linear_combination r1743 | linear_combination -r1743)
    (by unfold seg46BlindDeltaY193; first | linear_combination r1744 | linear_combination -r1744)
    (by linear_combination r582)

theorem seg46Blind_rows195 (rho : Nat -> Seg46.F) (h : Seg46.relation rho) :
    Seg46.relationRow583 rho ∧ Seg46.relationRow1745 rho ∧ Seg46.relationRow1746 rho ∧ Seg46.relationRow1747 rho ∧ Seg46.relationRow1748 rho ∧ Seg46.relationRow1749 rho ∧ Seg46.relationRow1750 rho ∧ Seg46.relationRow1751 rho ∧ Seg46.relationRow1752 rho := by
  unfold Seg46.relation at h

  rcases h with ⟨

    _, _, _, _, _, _, _, p7, _, _,

    _, _, _, _, _, _, _, _, _, _,

    _, p21, _, _, _, _, _, _

  ⟩

  unfold Seg46.relationPart7 at p7

  rcases p7 with ⟨_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, r583, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _⟩

  unfold Seg46.relationPart21 at p21

  rcases p21 with ⟨_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, r1745, r1746, r1747, r1748, r1749, r1750, r1751, r1752, _, _, _, _, _, _, _⟩

  exact ⟨r583, r1745, r1746, r1747, r1748, r1749, r1750, r1751, r1752⟩

theorem seg46Blind_rung195 (rho : Nat -> Seg46.F) (h : Seg46.relation rho)
    (bit : Bool) (hbitValue : rho 31856 = Bool.toZMod bit)
    (hacc : EdwardsBridge.onCurve (seg46BlindAccState rho 195)) :
    Shieldd.GnarkFormal.Deployed.NetBalance.NbFixedStepRel
      195 (Bool.toZMod bit) (seg46BlindAccState rho 195)
      (seg46BlindAccState rho 196) := by
  obtain ⟨r583, r1745, r1746, r1747, r1748, r1749, r1750, r1751, r1752⟩ := seg46Blind_rows195 rho h
  unfold Seg46.relationRow583 at r583

  unfold Seg46.relationRow1745 at r1745

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r1745

  unfold Seg46.relationRow1746 at r1746

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r1746

  unfold Seg46.relationRow1747 at r1747

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r1747

  unfold Seg46.relationRow1748 at r1748

  unfold Seg46.relationRow1749 at r1749

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r1749

  unfold Seg46.relationRow1750 at r1750

  unfold Seg46.relationRow1751 at r1751

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r1751

  unfold Seg46.relationRow1752 at r1752

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r1752

  have hnextx : seg46BlindDeltaX195 rho =
      seg46BlindDeltaX194 rho + rho 33023 := by
    unfold seg46BlindDeltaX195 seg46BlindDeltaX194
    rw [Shieldd.GnarkFormal.StrideRun.sumAux_succ rho 32663 8 45]

    ring

  have hnexty : seg46BlindDeltaY195 rho =
      seg46BlindDeltaY194 rho + rho 33024 := by
    unfold seg46BlindDeltaY195 seg46BlindDeltaY194
    rw [Shieldd.GnarkFormal.StrideRun.sumAux_succ rho 32664 8 45]

    ring

  change Shieldd.GnarkFormal.Deployed.NetBalance.NbFixedStepRel 195
    (Bool.toZMod bit) ⟨((4661681602708190761543544705274244814260880986867766715334030151044279151219 : Seg46.F) * rho 31661 + seg46BlindDeltaX194 rho : Seg46.F),
      ((1 : Seg46.F) + (4337336842509898676347982752646772244181661588533917621717979456142867120377 : Seg46.F) * rho 31661 + seg46BlindDeltaY194 rho : Seg46.F)⟩
    ⟨((4661681602708190761543544705274244814260880986867766715334030151044279151219 : Seg46.F) * rho 31661 + seg46BlindDeltaX195 rho : Seg46.F),
      ((1 : Seg46.F) + (4337336842509898676347982752646772244181661588533917621717979456142867120377 : Seg46.F) * rho 31661 + seg46BlindDeltaY195 rho : Seg46.F)⟩
  rw [hnextx, hnexty, ← hbitValue]
  rw [← add_assoc ((1 : Seg46.F) + (4337336842509898676347982752646772244181661588533917621717979456142867120377 : Seg46.F) * rho 31661)
    (seg46BlindDeltaY194 rho) (rho 33024)]
  exact Shieldd.GnarkFormal.RvkFixedSplitRung.splitRung_stepRel
    (Shieldd.GnarkFormal.Deployed.NetBalance.Cb 195)
    (4661681602708190761543544705274244814260880986867766715334030151044279151219 : Seg46.F) (4337336842509898676347982752646772244181661588533917621717979456142867120377 : Seg46.F)
    (534543527702324573819012140335261053705566569841713933263725786904339161184 : Seg46.F) (6217973748861355706774664776848221649695057456414935984473422092483830200013 : Seg46.F)
    (6752517276563680280593676917183482703400624026256649917737147879388169361197 : Seg46.F) (554556695789719013642702519139470527066643240247620509116776151269737032555 : Seg46.F)
    (4015764581459766636875627008318117948768454446883655766248935433332886612089 : Seg46.F) (3157768499214601969918244417310321822715768325365981343453183964039078504438 : Seg46.F)
    (6659275747808960082924259503299544426670642258395145597892705017474190829857 : Seg46.F) (1704336021480828285432287185509947710912034594408787045894785211655744122702 : Seg46.F)
    (2226488000567014717474160161933324881680841878739127843461811363433579039028 : Seg46.F) (7909918221726045850429812798446285477670332765312349894671507669013070077857 : Seg46.F)
    (6740125727947542138816537753271598820463864740745276782040448244261665116339 : Seg46.F) (3782780146720179662705280233507301717115018348286297112601203304873130087822 : Seg46.F) (4107124906918471747900842186134774287194237746620146206217253999774542118664 : Seg46.F)
    (rho 31661) (seg46BlindDeltaX194 rho) (seg46BlindDeltaY194 rho) (rho 31856)
    (rho 33017) (rho 33018) (rho 33019) (rho 33021)
    (rho 33020) (rho 33022) (rho 33023) (rho 33024) hacc
    (Shieldd.GnarkFormal.Deployed.NetBalance.Cb_onCurve 195)
    (by rw [Shieldd.GnarkFormal.NbFixedBaseLiteral.C_eq_L195]; rfl)
    (by decide) (by decide) (by decide) (by decide)
    (by decide) (by decide) (by decide) (by decide) (by decide)
    (by unfold seg46BlindDeltaX194 seg46BlindDeltaY194;
        first | linear_combination r1745 | linear_combination -r1745)
    (by unfold seg46BlindDeltaX194 seg46BlindDeltaY194;
        first | linear_combination r1746 | linear_combination -r1746)
    (by unfold seg46BlindDeltaX194 seg46BlindDeltaY194;
        first | linear_combination r1747 | linear_combination -r1747)
    (by first | linear_combination r1748 | linear_combination -r1748)
    (by unfold seg46BlindDeltaX194 seg46BlindDeltaY194;
        first | linear_combination r1749 | linear_combination -r1749)
    (by first | linear_combination r1750 | linear_combination -r1750)
    (by unfold seg46BlindDeltaX194; first | linear_combination r1751 | linear_combination -r1751)
    (by unfold seg46BlindDeltaY194; first | linear_combination r1752 | linear_combination -r1752)
    (by linear_combination r583)

theorem seg46Blind_rows196 (rho : Nat -> Seg46.F) (h : Seg46.relation rho) :
    Seg46.relationRow584 rho ∧ Seg46.relationRow1753 rho ∧ Seg46.relationRow1754 rho ∧ Seg46.relationRow1755 rho ∧ Seg46.relationRow1756 rho ∧ Seg46.relationRow1757 rho ∧ Seg46.relationRow1758 rho ∧ Seg46.relationRow1759 rho ∧ Seg46.relationRow1760 rho := by
  unfold Seg46.relation at h

  rcases h with ⟨

    _, _, _, _, _, _, _, p7, _, _,

    _, _, _, _, _, _, _, _, _, _,

    _, p21, p22, _, _, _, _, _

  ⟩

  unfold Seg46.relationPart7 at p7

  rcases p7 with ⟨_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, r584, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _⟩

  unfold Seg46.relationPart21 at p21

  rcases p21 with ⟨_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, r1753, r1754, r1755, r1756, r1757, r1758, r1759⟩

  unfold Seg46.relationPart22 at p22

  rcases p22 with ⟨r1760, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _⟩

  exact ⟨r584, r1753, r1754, r1755, r1756, r1757, r1758, r1759, r1760⟩

theorem seg46Blind_rung196 (rho : Nat -> Seg46.F) (h : Seg46.relation rho)
    (bit : Bool) (hbitValue : rho 31857 = Bool.toZMod bit)
    (hacc : EdwardsBridge.onCurve (seg46BlindAccState rho 196)) :
    Shieldd.GnarkFormal.Deployed.NetBalance.NbFixedStepRel
      196 (Bool.toZMod bit) (seg46BlindAccState rho 196)
      (seg46BlindAccState rho 197) := by
  obtain ⟨r584, r1753, r1754, r1755, r1756, r1757, r1758, r1759, r1760⟩ := seg46Blind_rows196 rho h
  unfold Seg46.relationRow584 at r584

  unfold Seg46.relationRow1753 at r1753

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r1753

  unfold Seg46.relationRow1754 at r1754

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r1754

  unfold Seg46.relationRow1755 at r1755

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r1755

  unfold Seg46.relationRow1756 at r1756

  unfold Seg46.relationRow1757 at r1757

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r1757

  unfold Seg46.relationRow1758 at r1758

  unfold Seg46.relationRow1759 at r1759

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r1759

  unfold Seg46.relationRow1760 at r1760

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r1760

  have hnextx : seg46BlindDeltaX196 rho =
      seg46BlindDeltaX195 rho + rho 33031 := by
    unfold seg46BlindDeltaX196 seg46BlindDeltaX195
    rw [Shieldd.GnarkFormal.StrideRun.sumAux_succ rho 32663 8 46]

    ring

  have hnexty : seg46BlindDeltaY196 rho =
      seg46BlindDeltaY195 rho + rho 33032 := by
    unfold seg46BlindDeltaY196 seg46BlindDeltaY195
    rw [Shieldd.GnarkFormal.StrideRun.sumAux_succ rho 32664 8 46]

    ring

  change Shieldd.GnarkFormal.Deployed.NetBalance.NbFixedStepRel 196
    (Bool.toZMod bit) ⟨((4661681602708190761543544705274244814260880986867766715334030151044279151219 : Seg46.F) * rho 31661 + seg46BlindDeltaX195 rho : Seg46.F),
      ((1 : Seg46.F) + (4337336842509898676347982752646772244181661588533917621717979456142867120377 : Seg46.F) * rho 31661 + seg46BlindDeltaY195 rho : Seg46.F)⟩
    ⟨((4661681602708190761543544705274244814260880986867766715334030151044279151219 : Seg46.F) * rho 31661 + seg46BlindDeltaX196 rho : Seg46.F),
      ((1 : Seg46.F) + (4337336842509898676347982752646772244181661588533917621717979456142867120377 : Seg46.F) * rho 31661 + seg46BlindDeltaY196 rho : Seg46.F)⟩
  rw [hnextx, hnexty, ← hbitValue]
  rw [← add_assoc ((1 : Seg46.F) + (4337336842509898676347982752646772244181661588533917621717979456142867120377 : Seg46.F) * rho 31661)
    (seg46BlindDeltaY195 rho) (rho 33032)]
  exact Shieldd.GnarkFormal.RvkFixedSplitRung.splitRung_stepRel
    (Shieldd.GnarkFormal.Deployed.NetBalance.Cb 196)
    (4661681602708190761543544705274244814260880986867766715334030151044279151219 : Seg46.F) (4337336842509898676347982752646772244181661588533917621717979456142867120377 : Seg46.F)
    (7033226505414935809728453247699649254198983826468420616303541913858179390258 : Seg46.F) (2532552902178607999355399383107160906073217720946833384503303324915775657262 : Seg46.F)
    (1121317658165173384835027692025263628896302212261190172871611782856545808479 : Seg46.F) (554556695789719013642702519139470527066643240247620509116776151269737032555 : Seg46.F)
    (159972499471161683226141830651939820625937330801826475157833509385490017356 : Seg46.F) (889344209890450458886721940910110142040239231044373030628454235548509460521 : Seg46.F)
    (1744946012703359804205378596564623655474306445177260178979160388767327552813 : Seg46.F) (4959782277533719432919392301145785066008674030300801316071562549820147524464 : Seg46.F)
    (5911908847249762424893425555674385625302681614207230443431930131001633581779 : Seg46.F) (1411235244013434614520371691081897277176915508685643211631691542059229848783 : Seg46.F)
    (3484679471894650991329432637635761465367225304853262511863670906097261714577 : Seg46.F) (3782780146720179662705280233507301717115018348286297112601203304873130087822 : Seg46.F) (4107124906918471747900842186134774287194237746620146206217253999774542118664 : Seg46.F)
    (rho 31661) (seg46BlindDeltaX195 rho) (seg46BlindDeltaY195 rho) (rho 31857)
    (rho 33025) (rho 33026) (rho 33027) (rho 33029)
    (rho 33028) (rho 33030) (rho 33031) (rho 33032) hacc
    (Shieldd.GnarkFormal.Deployed.NetBalance.Cb_onCurve 196)
    (by rw [Shieldd.GnarkFormal.NbFixedBaseLiteral.C_eq_L196]; rfl)
    (by decide) (by decide) (by decide) (by decide)
    (by decide) (by decide) (by decide) (by decide) (by decide)
    (by unfold seg46BlindDeltaX195 seg46BlindDeltaY195;
        first | linear_combination r1753 | linear_combination -r1753)
    (by unfold seg46BlindDeltaX195 seg46BlindDeltaY195;
        first | linear_combination r1754 | linear_combination -r1754)
    (by unfold seg46BlindDeltaX195 seg46BlindDeltaY195;
        first | linear_combination r1755 | linear_combination -r1755)
    (by first | linear_combination r1756 | linear_combination -r1756)
    (by unfold seg46BlindDeltaX195 seg46BlindDeltaY195;
        first | linear_combination r1757 | linear_combination -r1757)
    (by first | linear_combination r1758 | linear_combination -r1758)
    (by unfold seg46BlindDeltaX195; first | linear_combination r1759 | linear_combination -r1759)
    (by unfold seg46BlindDeltaY195; first | linear_combination r1760 | linear_combination -r1760)
    (by linear_combination r584)

theorem seg46Blind_rows197 (rho : Nat -> Seg46.F) (h : Seg46.relation rho) :
    Seg46.relationRow585 rho ∧ Seg46.relationRow1761 rho ∧ Seg46.relationRow1762 rho ∧ Seg46.relationRow1763 rho ∧ Seg46.relationRow1764 rho ∧ Seg46.relationRow1765 rho ∧ Seg46.relationRow1766 rho ∧ Seg46.relationRow1767 rho ∧ Seg46.relationRow1768 rho := by
  unfold Seg46.relation at h

  rcases h with ⟨

    _, _, _, _, _, _, _, p7, _, _,

    _, _, _, _, _, _, _, _, _, _,

    _, _, p22, _, _, _, _, _

  ⟩

  unfold Seg46.relationPart7 at p7

  rcases p7 with ⟨_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, r585, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _⟩

  unfold Seg46.relationPart22 at p22

  rcases p22 with ⟨_, r1761, r1762, r1763, r1764, r1765, r1766, r1767, r1768, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _⟩

  exact ⟨r585, r1761, r1762, r1763, r1764, r1765, r1766, r1767, r1768⟩

theorem seg46Blind_rung197 (rho : Nat -> Seg46.F) (h : Seg46.relation rho)
    (bit : Bool) (hbitValue : rho 31858 = Bool.toZMod bit)
    (hacc : EdwardsBridge.onCurve (seg46BlindAccState rho 197)) :
    Shieldd.GnarkFormal.Deployed.NetBalance.NbFixedStepRel
      197 (Bool.toZMod bit) (seg46BlindAccState rho 197)
      (seg46BlindAccState rho 198) := by
  obtain ⟨r585, r1761, r1762, r1763, r1764, r1765, r1766, r1767, r1768⟩ := seg46Blind_rows197 rho h
  unfold Seg46.relationRow585 at r585

  unfold Seg46.relationRow1761 at r1761

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r1761

  unfold Seg46.relationRow1762 at r1762

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r1762

  unfold Seg46.relationRow1763 at r1763

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r1763

  unfold Seg46.relationRow1764 at r1764

  unfold Seg46.relationRow1765 at r1765

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r1765

  unfold Seg46.relationRow1766 at r1766

  unfold Seg46.relationRow1767 at r1767

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r1767

  unfold Seg46.relationRow1768 at r1768

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r1768

  have hnextx : seg46BlindDeltaX197 rho =
      seg46BlindDeltaX196 rho + rho 33039 := by
    unfold seg46BlindDeltaX197 seg46BlindDeltaX196
    rw [Shieldd.GnarkFormal.StrideRun.sumAux_succ rho 32663 8 47]

    ring

  have hnexty : seg46BlindDeltaY197 rho =
      seg46BlindDeltaY196 rho + rho 33040 := by
    unfold seg46BlindDeltaY197 seg46BlindDeltaY196
    rw [Shieldd.GnarkFormal.StrideRun.sumAux_succ rho 32664 8 47]

    ring

  change Shieldd.GnarkFormal.Deployed.NetBalance.NbFixedStepRel 197
    (Bool.toZMod bit) ⟨((4661681602708190761543544705274244814260880986867766715334030151044279151219 : Seg46.F) * rho 31661 + seg46BlindDeltaX196 rho : Seg46.F),
      ((1 : Seg46.F) + (4337336842509898676347982752646772244181661588533917621717979456142867120377 : Seg46.F) * rho 31661 + seg46BlindDeltaY196 rho : Seg46.F)⟩
    ⟨((4661681602708190761543544705274244814260880986867766715334030151044279151219 : Seg46.F) * rho 31661 + seg46BlindDeltaX197 rho : Seg46.F),
      ((1 : Seg46.F) + (4337336842509898676347982752646772244181661588533917621717979456142867120377 : Seg46.F) * rho 31661 + seg46BlindDeltaY197 rho : Seg46.F)⟩
  rw [hnextx, hnexty, ← hbitValue]
  rw [← add_assoc ((1 : Seg46.F) + (4337336842509898676347982752646772244181661588533917621717979456142867120377 : Seg46.F) * rho 31661)
    (seg46BlindDeltaY196 rho) (rho 33040)]
  exact Shieldd.GnarkFormal.RvkFixedSplitRung.splitRung_stepRel
    (Shieldd.GnarkFormal.Deployed.NetBalance.Cb 197)
    (4661681602708190761543544705274244814260880986867766715334030151044279151219 : Seg46.F) (4337336842509898676347982752646772244181661588533917621717979456142867120377 : Seg46.F)
    (1287811907937307797322206503857689576857462357949847351868008167510510354195 : Seg46.F) (2939412043880705116914549657537370999037035682997305022831277955059888969285 : Seg46.F)
    (4227223951818012914236756161395060575894498040947152374699286122570399323480 : Seg46.F) (554556695789719013642702519139470527066643240247620509116776151269737032555 : Seg46.F)
    (4834485914392842313339504760992383614814597087937390813360340066727465977894 : Seg46.F) (4247903498688423199534134705096608045797863838610849994701913573296089218708 : Seg46.F)
    (8422332758588264717161581845639255967478228743291154791017212862493824457737 : Seg46.F) (8172166040961695728421806900328020423030021832888885709746286315834019511595 : Seg46.F)
    (5505049705547665307334275281244175532338863652156758805103955500857520269756 : Seg46.F) (7156649841491062626926618434923856954518436977204216476067225288406898884846 : Seg46.F)
    (272295708466674695827018038453526108345877502265178118188947140083389727446 : Seg46.F) (3782780146720179662705280233507301717115018348286297112601203304873130087822 : Seg46.F) (4107124906918471747900842186134774287194237746620146206217253999774542118664 : Seg46.F)
    (rho 31661) (seg46BlindDeltaX196 rho) (seg46BlindDeltaY196 rho) (rho 31858)
    (rho 33033) (rho 33034) (rho 33035) (rho 33037)
    (rho 33036) (rho 33038) (rho 33039) (rho 33040) hacc
    (Shieldd.GnarkFormal.Deployed.NetBalance.Cb_onCurve 197)
    (by rw [Shieldd.GnarkFormal.NbFixedBaseLiteral.C_eq_L197]; rfl)
    (by decide) (by decide) (by decide) (by decide)
    (by decide) (by decide) (by decide) (by decide) (by decide)
    (by unfold seg46BlindDeltaX196 seg46BlindDeltaY196;
        first | linear_combination r1761 | linear_combination -r1761)
    (by unfold seg46BlindDeltaX196 seg46BlindDeltaY196;
        first | linear_combination r1762 | linear_combination -r1762)
    (by unfold seg46BlindDeltaX196 seg46BlindDeltaY196;
        first | linear_combination r1763 | linear_combination -r1763)
    (by first | linear_combination r1764 | linear_combination -r1764)
    (by unfold seg46BlindDeltaX196 seg46BlindDeltaY196;
        first | linear_combination r1765 | linear_combination -r1765)
    (by first | linear_combination r1766 | linear_combination -r1766)
    (by unfold seg46BlindDeltaX196; first | linear_combination r1767 | linear_combination -r1767)
    (by unfold seg46BlindDeltaY196; first | linear_combination r1768 | linear_combination -r1768)
    (by linear_combination r585)

theorem seg46Blind_rows198 (rho : Nat -> Seg46.F) (h : Seg46.relation rho) :
    Seg46.relationRow586 rho ∧ Seg46.relationRow1769 rho ∧ Seg46.relationRow1770 rho ∧ Seg46.relationRow1771 rho ∧ Seg46.relationRow1772 rho ∧ Seg46.relationRow1773 rho ∧ Seg46.relationRow1774 rho ∧ Seg46.relationRow1775 rho ∧ Seg46.relationRow1776 rho := by
  unfold Seg46.relation at h

  rcases h with ⟨

    _, _, _, _, _, _, _, p7, _, _,

    _, _, _, _, _, _, _, _, _, _,

    _, _, p22, _, _, _, _, _

  ⟩

  unfold Seg46.relationPart7 at p7

  rcases p7 with ⟨_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, r586, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _⟩

  unfold Seg46.relationPart22 at p22

  rcases p22 with ⟨_, _, _, _, _, _, _, _, _, r1769, r1770, r1771, r1772, r1773, r1774, r1775, r1776, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _⟩

  exact ⟨r586, r1769, r1770, r1771, r1772, r1773, r1774, r1775, r1776⟩

theorem seg46Blind_rung198 (rho : Nat -> Seg46.F) (h : Seg46.relation rho)
    (bit : Bool) (hbitValue : rho 31859 = Bool.toZMod bit)
    (hacc : EdwardsBridge.onCurve (seg46BlindAccState rho 198)) :
    Shieldd.GnarkFormal.Deployed.NetBalance.NbFixedStepRel
      198 (Bool.toZMod bit) (seg46BlindAccState rho 198)
      (seg46BlindAccState rho 199) := by
  obtain ⟨r586, r1769, r1770, r1771, r1772, r1773, r1774, r1775, r1776⟩ := seg46Blind_rows198 rho h
  unfold Seg46.relationRow586 at r586

  unfold Seg46.relationRow1769 at r1769

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r1769

  unfold Seg46.relationRow1770 at r1770

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r1770

  unfold Seg46.relationRow1771 at r1771

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r1771

  unfold Seg46.relationRow1772 at r1772

  unfold Seg46.relationRow1773 at r1773

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r1773

  unfold Seg46.relationRow1774 at r1774

  unfold Seg46.relationRow1775 at r1775

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r1775

  unfold Seg46.relationRow1776 at r1776

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r1776

  have hnextx : seg46BlindDeltaX198 rho =
      seg46BlindDeltaX197 rho + rho 33047 := by
    unfold seg46BlindDeltaX198 seg46BlindDeltaX197
    rw [Shieldd.GnarkFormal.StrideRun.sumAux_succ rho 32663 8 48]

    ring

  have hnexty : seg46BlindDeltaY198 rho =
      seg46BlindDeltaY197 rho + rho 33048 := by
    unfold seg46BlindDeltaY198 seg46BlindDeltaY197
    rw [Shieldd.GnarkFormal.StrideRun.sumAux_succ rho 32664 8 48]

    ring

  change Shieldd.GnarkFormal.Deployed.NetBalance.NbFixedStepRel 198
    (Bool.toZMod bit) ⟨((4661681602708190761543544705274244814260880986867766715334030151044279151219 : Seg46.F) * rho 31661 + seg46BlindDeltaX197 rho : Seg46.F),
      ((1 : Seg46.F) + (4337336842509898676347982752646772244181661588533917621717979456142867120377 : Seg46.F) * rho 31661 + seg46BlindDeltaY197 rho : Seg46.F)⟩
    ⟨((4661681602708190761543544705274244814260880986867766715334030151044279151219 : Seg46.F) * rho 31661 + seg46BlindDeltaX198 rho : Seg46.F),
      ((1 : Seg46.F) + (4337336842509898676347982752646772244181661588533917621717979456142867120377 : Seg46.F) * rho 31661 + seg46BlindDeltaY198 rho : Seg46.F)⟩
  rw [hnextx, hnexty, ← hbitValue]
  rw [← add_assoc ((1 : Seg46.F) + (4337336842509898676347982752646772244181661588533917621717979456142867120377 : Seg46.F) * rho 31661)
    (seg46BlindDeltaY197 rho) (rho 33048)]
  exact Shieldd.GnarkFormal.RvkFixedSplitRung.splitRung_stepRel
    (Shieldd.GnarkFormal.Deployed.NetBalance.Cb 198)
    (4661681602708190761543544705274244814260880986867766715334030151044279151219 : Seg46.F) (4337336842509898676347982752646772244181661588533917621717979456142867120377 : Seg46.F)
    (1189785845959812492681481939094349700657637573249984492101068248967037471045 : Seg46.F) (313065814926456601259847752896291272836620104337514703885056590706326326606 : Seg46.F)
    (1502851660886269093941329691990640973494257677587499195986124839673363797651 : Seg46.F) (554556695789719013642702519139470527066643240247620509116776151269737032555 : Seg46.F)
    (8436572706276275314380493294944270256704509001530835535945046916979407143175 : Seg46.F) (1602782074949261827795561264723734697894838837521197630438188003049246203409 : Seg46.F)
    (6751606183813397713597296114152273309656750207528415013862084614103750643323 : Seg46.F) (1360092137943693216229474947106632950727185500916475945190576124046937278243 : Seg46.F)
    (8131395934501913822988977185885255258539279230816549124050176865211082912435 : Seg46.F) (7254675903468557931567342999687196830718261761904079335834165206950371767996 : Seg46.F)
    (7084369611484677208019349991674913580648713834237587882744657331870471960798 : Seg46.F) (3782780146720179662705280233507301717115018348286297112601203304873130087822 : Seg46.F) (4107124906918471747900842186134774287194237746620146206217253999774542118664 : Seg46.F)
    (rho 31661) (seg46BlindDeltaX197 rho) (seg46BlindDeltaY197 rho) (rho 31859)
    (rho 33041) (rho 33042) (rho 33043) (rho 33045)
    (rho 33044) (rho 33046) (rho 33047) (rho 33048) hacc
    (Shieldd.GnarkFormal.Deployed.NetBalance.Cb_onCurve 198)
    (by rw [Shieldd.GnarkFormal.NbFixedBaseLiteral.C_eq_L198]; rfl)
    (by decide) (by decide) (by decide) (by decide)
    (by decide) (by decide) (by decide) (by decide) (by decide)
    (by unfold seg46BlindDeltaX197 seg46BlindDeltaY197;
        first | linear_combination r1769 | linear_combination -r1769)
    (by unfold seg46BlindDeltaX197 seg46BlindDeltaY197;
        first | linear_combination r1770 | linear_combination -r1770)
    (by unfold seg46BlindDeltaX197 seg46BlindDeltaY197;
        first | linear_combination r1771 | linear_combination -r1771)
    (by first | linear_combination r1772 | linear_combination -r1772)
    (by unfold seg46BlindDeltaX197 seg46BlindDeltaY197;
        first | linear_combination r1773 | linear_combination -r1773)
    (by first | linear_combination r1774 | linear_combination -r1774)
    (by unfold seg46BlindDeltaX197; first | linear_combination r1775 | linear_combination -r1775)
    (by unfold seg46BlindDeltaY197; first | linear_combination r1776 | linear_combination -r1776)
    (by linear_combination r586)

theorem seg46Blind_rows199 (rho : Nat -> Seg46.F) (h : Seg46.relation rho) :
    Seg46.relationRow587 rho ∧ Seg46.relationRow1777 rho ∧ Seg46.relationRow1778 rho ∧ Seg46.relationRow1779 rho ∧ Seg46.relationRow1780 rho ∧ Seg46.relationRow1781 rho ∧ Seg46.relationRow1782 rho ∧ Seg46.relationRow1783 rho ∧ Seg46.relationRow1784 rho := by
  unfold Seg46.relation at h

  rcases h with ⟨

    _, _, _, _, _, _, _, p7, _, _,

    _, _, _, _, _, _, _, _, _, _,

    _, _, p22, _, _, _, _, _

  ⟩

  unfold Seg46.relationPart7 at p7

  rcases p7 with ⟨_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, r587, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _⟩

  unfold Seg46.relationPart22 at p22

  rcases p22 with ⟨_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, r1777, r1778, r1779, r1780, r1781, r1782, r1783, r1784, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _⟩

  exact ⟨r587, r1777, r1778, r1779, r1780, r1781, r1782, r1783, r1784⟩

theorem seg46Blind_rung199 (rho : Nat -> Seg46.F) (h : Seg46.relation rho)
    (bit : Bool) (hbitValue : rho 31860 = Bool.toZMod bit)
    (hacc : EdwardsBridge.onCurve (seg46BlindAccState rho 199)) :
    Shieldd.GnarkFormal.Deployed.NetBalance.NbFixedStepRel
      199 (Bool.toZMod bit) (seg46BlindAccState rho 199)
      (seg46BlindAccState rho 200) := by
  obtain ⟨r587, r1777, r1778, r1779, r1780, r1781, r1782, r1783, r1784⟩ := seg46Blind_rows199 rho h
  unfold Seg46.relationRow587 at r587

  unfold Seg46.relationRow1777 at r1777

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r1777

  unfold Seg46.relationRow1778 at r1778

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r1778

  unfold Seg46.relationRow1779 at r1779

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r1779

  unfold Seg46.relationRow1780 at r1780

  unfold Seg46.relationRow1781 at r1781

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r1781

  unfold Seg46.relationRow1782 at r1782

  unfold Seg46.relationRow1783 at r1783

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r1783

  unfold Seg46.relationRow1784 at r1784

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r1784

  have hnextx : seg46BlindDeltaX199 rho =
      seg46BlindDeltaX198 rho + rho 33055 := by
    unfold seg46BlindDeltaX199 seg46BlindDeltaX198
    rw [Shieldd.GnarkFormal.StrideRun.sumAux_succ rho 32663 8 49]

    ring

  have hnexty : seg46BlindDeltaY199 rho =
      seg46BlindDeltaY198 rho + rho 33056 := by
    unfold seg46BlindDeltaY199 seg46BlindDeltaY198
    rw [Shieldd.GnarkFormal.StrideRun.sumAux_succ rho 32664 8 49]

    ring

  change Shieldd.GnarkFormal.Deployed.NetBalance.NbFixedStepRel 199
    (Bool.toZMod bit) ⟨((4661681602708190761543544705274244814260880986867766715334030151044279151219 : Seg46.F) * rho 31661 + seg46BlindDeltaX198 rho : Seg46.F),
      ((1 : Seg46.F) + (4337336842509898676347982752646772244181661588533917621717979456142867120377 : Seg46.F) * rho 31661 + seg46BlindDeltaY198 rho : Seg46.F)⟩
    ⟨((4661681602708190761543544705274244814260880986867766715334030151044279151219 : Seg46.F) * rho 31661 + seg46BlindDeltaX199 rho : Seg46.F),
      ((1 : Seg46.F) + (4337336842509898676347982752646772244181661588533917621717979456142867120377 : Seg46.F) * rho 31661 + seg46BlindDeltaY199 rho : Seg46.F)⟩
  rw [hnextx, hnexty, ← hbitValue]
  rw [← add_assoc ((1 : Seg46.F) + (4337336842509898676347982752646772244181661588533917621717979456142867120377 : Seg46.F) * rho 31661)
    (seg46BlindDeltaY198 rho) (rho 33056)]
  exact Shieldd.GnarkFormal.RvkFixedSplitRung.splitRung_stepRel
    (Shieldd.GnarkFormal.Deployed.NetBalance.Cb 199)
    (4661681602708190761543544705274244814260880986867766715334030151044279151219 : Seg46.F) (4337336842509898676347982752646772244181661588533917621717979456142867120377 : Seg46.F)
    (3551123497965750934797699834002404728361160069706598447696579925198710334471 : Seg46.F) (3002030520192283727479249997399438260283975122815343265517649215638558877392 : Seg46.F)
    (6553154018158034662276949831401842988645135192521941713214229140837269211863 : Seg46.F) (554556695789719013642702519139470527066643240247620509116776151269737032555 : Seg46.F)
    (8226744364247675495825082831103556151548859404841517754312782244706255110239 : Seg46.F) (4248897056721397889874420512898227115066472860817192579095222727956920142414 : Seg46.F)
    (560917769939457241020240338036935902182861430632256579106756322648974055852 : Seg46.F) (394608995391631743646835811120684804941058223995902180862129118204390264326 : Seg46.F)
    (5442431229236086696769574941382108271091924212338720562417584240278850361649 : Seg46.F) (4893338251462619489451125104779141803014739265447465380238653530718698904570 : Seg46.F)
    (8049852754036738680601989127660861726434841111158161647073104337713018974715 : Seg46.F) (3782780146720179662705280233507301717115018348286297112601203304873130087822 : Seg46.F) (4107124906918471747900842186134774287194237746620146206217253999774542118664 : Seg46.F)
    (rho 31661) (seg46BlindDeltaX198 rho) (seg46BlindDeltaY198 rho) (rho 31860)
    (rho 33049) (rho 33050) (rho 33051) (rho 33053)
    (rho 33052) (rho 33054) (rho 33055) (rho 33056) hacc
    (Shieldd.GnarkFormal.Deployed.NetBalance.Cb_onCurve 199)
    (by rw [Shieldd.GnarkFormal.NbFixedBaseLiteral.C_eq_L199]; rfl)
    (by decide) (by decide) (by decide) (by decide)
    (by decide) (by decide) (by decide) (by decide) (by decide)
    (by unfold seg46BlindDeltaX198 seg46BlindDeltaY198;
        first | linear_combination r1777 | linear_combination -r1777)
    (by unfold seg46BlindDeltaX198 seg46BlindDeltaY198;
        first | linear_combination r1778 | linear_combination -r1778)
    (by unfold seg46BlindDeltaX198 seg46BlindDeltaY198;
        first | linear_combination r1779 | linear_combination -r1779)
    (by first | linear_combination r1780 | linear_combination -r1780)
    (by unfold seg46BlindDeltaX198 seg46BlindDeltaY198;
        first | linear_combination r1781 | linear_combination -r1781)
    (by first | linear_combination r1782 | linear_combination -r1782)
    (by unfold seg46BlindDeltaX198; first | linear_combination r1783 | linear_combination -r1783)
    (by unfold seg46BlindDeltaY198; first | linear_combination r1784 | linear_combination -r1784)
    (by linear_combination r587)

theorem seg46Blind_rows200 (rho : Nat -> Seg46.F) (h : Seg46.relation rho) :
    Seg46.relationRow588 rho ∧ Seg46.relationRow1785 rho ∧ Seg46.relationRow1786 rho ∧ Seg46.relationRow1787 rho ∧ Seg46.relationRow1788 rho ∧ Seg46.relationRow1789 rho ∧ Seg46.relationRow1790 rho ∧ Seg46.relationRow1791 rho ∧ Seg46.relationRow1792 rho := by
  unfold Seg46.relation at h

  rcases h with ⟨

    _, _, _, _, _, _, _, p7, _, _,

    _, _, _, _, _, _, _, _, _, _,

    _, _, p22, _, _, _, _, _

  ⟩

  unfold Seg46.relationPart7 at p7

  rcases p7 with ⟨_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, r588, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _⟩

  unfold Seg46.relationPart22 at p22

  rcases p22 with ⟨_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, r1785, r1786, r1787, r1788, r1789, r1790, r1791, r1792, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _⟩

  exact ⟨r588, r1785, r1786, r1787, r1788, r1789, r1790, r1791, r1792⟩

theorem seg46Blind_rung200 (rho : Nat -> Seg46.F) (h : Seg46.relation rho)
    (bit : Bool) (hbitValue : rho 31861 = Bool.toZMod bit)
    (hacc : EdwardsBridge.onCurve (seg46BlindAccState rho 200)) :
    Shieldd.GnarkFormal.Deployed.NetBalance.NbFixedStepRel
      200 (Bool.toZMod bit) (seg46BlindAccState rho 200)
      (seg46BlindAccState rho 201) := by
  obtain ⟨r588, r1785, r1786, r1787, r1788, r1789, r1790, r1791, r1792⟩ := seg46Blind_rows200 rho h
  unfold Seg46.relationRow588 at r588

  unfold Seg46.relationRow1785 at r1785

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r1785

  unfold Seg46.relationRow1786 at r1786

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r1786

  unfold Seg46.relationRow1787 at r1787

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r1787

  unfold Seg46.relationRow1788 at r1788

  unfold Seg46.relationRow1789 at r1789

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r1789

  unfold Seg46.relationRow1790 at r1790

  unfold Seg46.relationRow1791 at r1791

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r1791

  unfold Seg46.relationRow1792 at r1792

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r1792

  have hnextx : seg46BlindDeltaX200 rho =
      seg46BlindDeltaX199 rho + rho 33063 := by
    unfold seg46BlindDeltaX200 seg46BlindDeltaX199
    rw [Shieldd.GnarkFormal.StrideRun.sumAux_succ rho 32663 8 50]

    ring

  have hnexty : seg46BlindDeltaY200 rho =
      seg46BlindDeltaY199 rho + rho 33064 := by
    unfold seg46BlindDeltaY200 seg46BlindDeltaY199
    rw [Shieldd.GnarkFormal.StrideRun.sumAux_succ rho 32664 8 50]

    ring

  change Shieldd.GnarkFormal.Deployed.NetBalance.NbFixedStepRel 200
    (Bool.toZMod bit) ⟨((4661681602708190761543544705274244814260880986867766715334030151044279151219 : Seg46.F) * rho 31661 + seg46BlindDeltaX199 rho : Seg46.F),
      ((1 : Seg46.F) + (4337336842509898676347982752646772244181661588533917621717979456142867120377 : Seg46.F) * rho 31661 + seg46BlindDeltaY199 rho : Seg46.F)⟩
    ⟨((4661681602708190761543544705274244814260880986867766715334030151044279151219 : Seg46.F) * rho 31661 + seg46BlindDeltaX200 rho : Seg46.F),
      ((1 : Seg46.F) + (4337336842509898676347982752646772244181661588533917621717979456142867120377 : Seg46.F) * rho 31661 + seg46BlindDeltaY200 rho : Seg46.F)⟩
  rw [hnextx, hnexty, ← hbitValue]
  rw [← add_assoc ((1 : Seg46.F) + (4337336842509898676347982752646772244181661588533917621717979456142867120377 : Seg46.F) * rho 31661)
    (seg46BlindDeltaY199 rho) (rho 33064)]
  exact Shieldd.GnarkFormal.RvkFixedSplitRung.splitRung_stepRel
    (Shieldd.GnarkFormal.Deployed.NetBalance.Cb 200)
    (4661681602708190761543544705274244814260880986867766715334030151044279151219 : Seg46.F) (4337336842509898676347982752646772244181661588533917621717979456142867120377 : Seg46.F)
    (237407082182476649271201308514110417937957700889391563201001451196613456842 : Seg46.F) (961186733346023561115570340324357733199172280018292165698470412330626102152 : Seg46.F)
    (1198593815528500210386771648838468151137129980907683728899471863527239558994 : Seg46.F) (554556695789719013642702519139470527066643240247620509116776151269737032555 : Seg46.F)
    (7294741384406122612791044117814251732765985977416739593294040271150085610129 : Seg46.F) (8280214252583025169891409716798129779029250702630506565416096652795038393465 : Seg46.F)
    (4440596737623467634352615922521817381278024270263026038921952693420240567282 : Seg46.F) (429353156714312750522287818459088917432687562358820428081310804626925562691 : Seg46.F)
    (7483275016082346863133254598457188798176727055135771662236763043586783136889 : Seg46.F) (8207054667245893774977623630267436113437941634264672264734232004720795782199 : Seg46.F)
    (8015108592714057673726537120322457613943211772795243399853922651290483676350 : Seg46.F) (3782780146720179662705280233507301717115018348286297112601203304873130087822 : Seg46.F) (4107124906918471747900842186134774287194237746620146206217253999774542118664 : Seg46.F)
    (rho 31661) (seg46BlindDeltaX199 rho) (seg46BlindDeltaY199 rho) (rho 31861)
    (rho 33057) (rho 33058) (rho 33059) (rho 33061)
    (rho 33060) (rho 33062) (rho 33063) (rho 33064) hacc
    (Shieldd.GnarkFormal.Deployed.NetBalance.Cb_onCurve 200)
    (by rw [Shieldd.GnarkFormal.NbFixedBaseLiteral.C_eq_L200]; rfl)
    (by decide) (by decide) (by decide) (by decide)
    (by decide) (by decide) (by decide) (by decide) (by decide)
    (by unfold seg46BlindDeltaX199 seg46BlindDeltaY199;
        first | linear_combination r1785 | linear_combination -r1785)
    (by unfold seg46BlindDeltaX199 seg46BlindDeltaY199;
        first | linear_combination r1786 | linear_combination -r1786)
    (by unfold seg46BlindDeltaX199 seg46BlindDeltaY199;
        first | linear_combination r1787 | linear_combination -r1787)
    (by first | linear_combination r1788 | linear_combination -r1788)
    (by unfold seg46BlindDeltaX199 seg46BlindDeltaY199;
        first | linear_combination r1789 | linear_combination -r1789)
    (by first | linear_combination r1790 | linear_combination -r1790)
    (by unfold seg46BlindDeltaX199; first | linear_combination r1791 | linear_combination -r1791)
    (by unfold seg46BlindDeltaY199; first | linear_combination r1792 | linear_combination -r1792)
    (by linear_combination r588)

theorem seg46Blind_hstep_c19 (rho : Nat -> Seg46.F)
    (h : Seg46.relation rho) (bits : List.Vector Bool 251)
    (hbitAt : ∀ i, i < 251 → rho (31661 + i) = Bool.toZMod bits[i]!) :
    ∀ i, 191 ≤ i → i < 201 →
      EdwardsBridge.onCurve (seg46BlindAccState rho i) →
      Shieldd.GnarkFormal.Deployed.NetBalance.NbFixedStepRel i
        (Bool.toZMod bits[i]!) (seg46BlindAccState rho i)
        (seg46BlindAccState rho (i + 1)) := by
  intro i hlo hhi hacc
  interval_cases i
  · exact seg46Blind_rung191 rho h bits[191]! (hbitAt 191 (by omega)) hacc
  · exact seg46Blind_rung192 rho h bits[192]! (hbitAt 192 (by omega)) hacc
  · exact seg46Blind_rung193 rho h bits[193]! (hbitAt 193 (by omega)) hacc
  · exact seg46Blind_rung194 rho h bits[194]! (hbitAt 194 (by omega)) hacc
  · exact seg46Blind_rung195 rho h bits[195]! (hbitAt 195 (by omega)) hacc
  · exact seg46Blind_rung196 rho h bits[196]! (hbitAt 196 (by omega)) hacc
  · exact seg46Blind_rung197 rho h bits[197]! (hbitAt 197 (by omega)) hacc
  · exact seg46Blind_rung198 rho h bits[198]! (hbitAt 198 (by omega)) hacc
  · exact seg46Blind_rung199 rho h bits[199]! (hbitAt 199 (by omega)) hacc
  · exact seg46Blind_rung200 rho h bits[200]! (hbitAt 200 (by omega)) hacc

end Shieldd.GnarkFormal.Deployed.Contracts.Consolidate2x1
