import Ipp.Extracted.ArkworksG2PreparedSchedule
import Ipp.Extracted.ArkworksG2PreparedDouble
import Ipp.Extracted.ArkworksG2PreparedAddStep
import Ipp.Extracted.ArkworksG2PreparedScalar
import Ipp.Extracted.ArkworksG2PreparedResult
import Ipp.Extracted.ArkworksG2PreparedInput
import Ipp.Extracted.ArkworksG2PreparedGenericityHomogeneous
import Ipp.Extracted.ArkworksG2PreparedPointStepDouble
import Ipp.Extracted.ArkworksG2PreparedPointStepAddition
import Ipp.Extracted.ArkworksG2PreparedModelPrefix
import Ipp.Extracted.ArkworksG2PreparedLoopPureStepFalse
import Ipp.Extracted.ArkworksG2PreparedLoopPureStepTrue
import Ipp.Extracted.ArkworksG2PreparedLoopDoubleFacts
import Ipp.Extracted.ArkworksG2PreparedLoopAdditionFacts
import Ipp.Extracted.ArkworksG2PreparedValid

/-! Axiom gate for the prepared-G2 schedule, doubling, and mixed-addition lines. -/

#print axioms Ipp.Extracted.ArkworksG2PreparedSchedule.initialState_coordinates
#print axioms Ipp.Extracted.ArkworksG2PreparedSchedule.extractedAteBit_eq_testBit
#print axioms Ipp.Extracted.ArkworksG2PreparedSchedule.ate_schedule_positions
#print axioms Ipp.Extracted.ArkworksG2PreparedSchedule.preparedSchedule_uses_ate_bits
#print axioms Ipp.Extracted.ArkworksG2PreparedSchedule.g2_prepared_loop_eq_schedule
#print axioms Ipp.Extracted.ArkworksG2PreparedSchedule.g2_prepared_infinity
#print axioms Ipp.Extracted.ArkworksG2PreparedSchedule.g2_prepared_finite_schedule

#print axioms Ipp.Extracted.ArkworksG2PreparedDoubleOps.bind_eq_ok
#print axioms Ipp.Extracted.ArkworksG2PreparedDoubleOps.result_bind_assoc
#print axioms Ipp.Extracted.ArkworksG2PreparedDoubleOps.fq2_double_spec
#print axioms Ipp.Extracted.ArkworksG2PreparedDoubleOps.fq2_add_spec
#print axioms Ipp.Extracted.ArkworksG2PreparedDoubleOps.fq2_sub_spec
#print axioms Ipp.Extracted.ArkworksG2PreparedDoubleOps.fq2_neg_spec
#print axioms Ipp.Extracted.ArkworksG2PreparedDoubleOps.fq2_mul_fp_spec
#print axioms Ipp.Extracted.ArkworksG2PreparedDoubleOps.segment1_eq_cut
#print axioms Ipp.Extracted.ArkworksG2PreparedDoubleOps.segment2_eq_cut
#print axioms Ipp.Extracted.ArkworksG2PreparedDoubleOps.segment3_eq_cut
#print axioms Ipp.Extracted.ArkworksG2PreparedDoubleOps.g2_double_line_eq_segmented

#print axioms Ipp.Extracted.ArkworksG2PreparedDoubleSegment1A.segment1A_spec
#print axioms Ipp.Extracted.ArkworksG2PreparedDoubleSegment1B.segment1B_spec
#print axioms Ipp.Extracted.ArkworksG2PreparedDoubleSegment1C.segment1C_spec
#print axioms Ipp.Extracted.ArkworksG2PreparedDoubleSegment1Assembly.assemble_segment1_spec
#print axioms Ipp.Extracted.ArkworksG2PreparedDoubleSegment1.segment1_spec
#print axioms Ipp.Extracted.ArkworksG2PreparedDoubleSegment2A.segment2A_spec
#print axioms Ipp.Extracted.ArkworksG2PreparedDoubleSegment2B.segment2B_spec
#print axioms Ipp.Extracted.ArkworksG2PreparedDoubleSegment2.segment2_spec
#print axioms Ipp.Extracted.ArkworksG2PreparedDoubleSegment3A.segment3A_spec
#print axioms Ipp.Extracted.ArkworksG2PreparedDoubleSegment3B.segment3B_spec
#print axioms Ipp.Extracted.ArkworksG2PreparedDoubleSegment3.segment3_spec
#print axioms Ipp.Extracted.ArkworksG2PreparedDoubleAssembly.assemble_double_model
#print axioms Ipp.Extracted.ArkworksG2PreparedDoublePrefix.segment12_spec
#print axioms Ipp.Extracted.ArkworksG2PreparedDoublePrefix.segmentedDoubleLine_eq_segment12
#print axioms Ipp.Extracted.ArkworksG2PreparedDoubleExecute.g2_double_line_cut_spec
#print axioms Ipp.Extracted.ArkworksG2PreparedDouble.g2_double_line_exec_spec

#print axioms Ipp.Extracted.ArkworksG2PreparedModel.decodeHomogeneous_coordinates
#print axioms Ipp.Extracted.ArkworksG2PreparedModel.ate_twoInv_add_self
#print axioms Ipp.Extracted.ArkworksG2PreparedModel.ate_twoInv_ne_zero
#print axioms Ipp.Extracted.ArkworksG2PreparedModel.fq2MulFq_twoInv_add_self
#print axioms Ipp.Extracted.ArkworksG2PreparedModel.doubleLine_decode_generic
#print axioms Ipp.Extracted.ArkworksG2PreparedModel.doubleLine_decode_order_two
#print axioms Ipp.Extracted.ArkworksG2PreparedModel.doubleLine_decode_infinity
#print axioms Ipp.Extracted.ArkworksG2PreparedModel.doubleLine_represents_double
#print axioms Ipp.Extracted.ArkworksG2PreparedModel.g2_coeff_b_spec
#print axioms Ipp.Extracted.ArkworksG2PreparedModelTransport.doubleLine_represents_model
#print axioms Ipp.Extracted.ArkworksG2PreparedDoubleAll.allHomogeneousDoubles
#print axioms Ipp.Extracted.ArkworksG2PreparedDoubleTransition.transition_of
#print axioms Ipp.Extracted.ArkworksG2PreparedDoubleCap.combine_double_line_spec
#print axioms Ipp.Extracted.ArkworksG2PreparedDouble.g2_double_line_spec

#print axioms Ipp.Extracted.ArkworksG2PreparedAdditionModel.addLine_decode_generic
#print axioms Ipp.Extracted.ArkworksG2PreparedAdditionTransport.addLine_represents_add
#print axioms Ipp.Extracted.ArkworksG2PreparedAdditionOps.g2_add_line_eq_segmented
#print axioms Ipp.Extracted.ArkworksG2PreparedAdditionSegment1A.segment1A_spec
#print axioms Ipp.Extracted.ArkworksG2PreparedAdditionSegment1B.segment1B_spec
#print axioms Ipp.Extracted.ArkworksG2PreparedAdditionSegment1.segment1_spec
#print axioms Ipp.Extracted.ArkworksG2PreparedAdditionSegment2A.segment2A_spec
#print axioms Ipp.Extracted.ArkworksG2PreparedAdditionSegment2B.segment2B_spec
#print axioms Ipp.Extracted.ArkworksG2PreparedAdditionSegment2.segment2_spec
#print axioms Ipp.Extracted.ArkworksG2PreparedAdditionSegment3A.segment3A_spec
#print axioms Ipp.Extracted.ArkworksG2PreparedAdditionSegment3B.segment3B_spec
#print axioms Ipp.Extracted.ArkworksG2PreparedAdditionSegment3.segment3_spec
#print axioms Ipp.Extracted.ArkworksG2PreparedAdditionAssembly.assemble_add_model
#print axioms Ipp.Extracted.ArkworksG2PreparedAdditionExecute.g2_add_line_exec_spec
#print axioms Ipp.Extracted.ArkworksG2PreparedAdditionAll.allGenericHomogeneousAdds
#print axioms Ipp.Extracted.ArkworksG2PreparedAdditionTransition.transition_of
#print axioms Ipp.Extracted.ArkworksG2PreparedAdditionCap.combine_add_line_spec
#print axioms Ipp.Extracted.ArkworksG2PreparedAddition.g2_add_line_spec
#print axioms Ipp.Extracted.ArkworksG2PreparedAddStep.g2_add_line_valid_add_step
#print axioms Ipp.Extracted.ArkworksG2PreparedAddStep.preparedSchedule_add_step_instantiated

#print axioms Ipp.Extracted.ArkworksG2PreparedScalar.ate_addition_scalar_table
#print axioms Ipp.Extracted.ArkworksG2PreparedScalar.doubledScalar_mem
#print axioms Ipp.Extracted.ArkworksG2PreparedScalar.accumulatedScalar_step
#print axioms Ipp.Extracted.ArkworksG2PreparedScalar.accumulatedScalar_initial
#print axioms Ipp.Extracted.ArkworksG2PreparedScalar.accumulatedScalar_final
#print axioms Ipp.Extracted.ArkworksG2PreparedScalar.additionDoubledScalars_safe
#print axioms Ipp.Extracted.ArkworksG2PreparedScalar.additionDoubledScalars_mod_safe
#print axioms Ipp.Extracted.ArkworksG2PreparedScalar.addOrderOf_eq_scalarModulus
#print axioms Ipp.Extracted.ArkworksG2PreparedScalar.nsmul_ne_zero_of_lt_scalarModulus
#print axioms Ipp.Extracted.ArkworksG2PreparedScalar.additionScalar_generic
#print axioms Ipp.Extracted.ArkworksG2PreparedResult.decodePrepared_infinity
#print axioms Ipp.Extracted.ArkworksG2PreparedInput.finite_ne_zero
#print axioms Ipp.Extracted.ArkworksG2PreparedInput.affineRepOfPoint_eq
#print axioms Ipp.Extracted.ArkworksG2PreparedInput.initialState_canonical
#print axioms Ipp.Extracted.ArkworksG2PreparedInput.initialState_representsDecoded
#print axioms Ipp.Extracted.ArkworksG2PreparedGenericity.represented_eq_or_eq_neg_of_same_x
#print axioms Ipp.Extracted.ArkworksG2PreparedGenericityHomogeneous.homogeneous_generic_of_point_exclusions
#print axioms Ipp.Extracted.ArkworksG2PreparedPointStep.double_model_represents_nsmul
#print axioms Ipp.Extracted.ArkworksG2PreparedPointStep.add_model_generic_and_represents
#print axioms Ipp.Extracted.ArkworksG2PreparedModelPrefix.preparedModelAt_step
#print axioms Ipp.Extracted.ArkworksG2PreparedModelPrefix.preparedModelAt_initial
#print axioms Ipp.Extracted.ArkworksG2PreparedModelPrefix.preparedModelAt_final
#print axioms Ipp.Extracted.ArkworksG2PreparedLoopPureStep.false_step
#print axioms Ipp.Extracted.ArkworksG2PreparedLoopPureStep.true_step
#print axioms Ipp.Extracted.ArkworksG2PreparedLoopDoubleFacts.double_facts
#print axioms Ipp.Extracted.ArkworksG2PreparedLoopAdditionFacts.addition_facts
#print axioms Ipp.Extracted.ArkworksG2PreparedLoopInvariant.PreparedLoopInv
#print axioms Ipp.Extracted.ArkworksG2PreparedLoopStep.preparedLoopInv_step
#print axioms Ipp.Extracted.ArkworksG2PreparedLoopFuel.preparedLoopResult
#print axioms Ipp.Extracted.ArkworksG2PreparedInvSome.inv_some_of_execution
#print axioms Ipp.Extracted.ArkworksG2PreparedTwoInv.two_inv_facts
#print axioms Ipp.Extracted.ArkworksG2PreparedFiniteCoefficients.finite_coefficients
#print axioms Ipp.Extracted.ArkworksG2PreparedFiniteResult.valid_g2_prepared_finite
#print axioms Ipp.Extracted.ArkworksG2PreparedValid.valid_g2_prepared
