import Ipp.S1
import Ipp.S1Computational
import Ipp.S1Bls12377SecurityGames
import Ipp.Goal
import Ipp.SnarkPackV1
import Ipp.SnarkPackV1Refinement
import Ipp.HonestProver
import Ipp.Cost
import Ipp.ShippingScalarReduction
import Ipp.ShippingHashExecutionTrace
import Ipp.ShippingToGoal
import Ipp.ShippingAdaptiveSha
import Ipp.ShippingMultiStatement
import Ipp.Extracted.AppVerifierStateMachine
import Ipp.Extracted.ShippingRowConstruction
import Ipp.Extracted.ShippingStatementConstruction
import Ipp.Extracted.AggregateVerifierPairingAdapter
import Ipp.Extracted.ShippingVerifierComposition
import Ipp.Extracted.ShippingBundleComposition
import Ipp.Extracted.ShippingProver
import Ipp.Extracted.ChallengeFrame
import Ipp.Extracted.TippMippChallengeExecution
import Ipp.Extracted.ArkworksFqBytesBridge
import Ipp.Extracted.ArkworksFr
import Ipp.Extracted.ArkworksFq12
import Ipp.Extracted.ArkworksG1Mathlib
import Ipp.Extracted.ArkworksG2Mathlib
import Ipp.Extracted.ArkworksScalarMulG1Loop
import Ipp.Extracted.ArkworksScalarMulG2Loop
import Ipp.Extracted.ArkworksScalarMulGlvFinal
import Ipp.Extracted.ArkworksScalarMulNormalizeBatchGeneralG1
import Ipp.Extracted.ArkworksScalarMulNormalizeBatchGeneralG2
import Ipp.Extracted.ArkworksScalarMulNormalizeBatchAllInfinityG1
import Ipp.Extracted.ArkworksScalarMulNormalizeBatchAllInfinityG2
import Ipp.Extracted.ArkworksScalarMulNormalizeBatchSingletonG1Nonzero
import Ipp.Extracted.ArkworksScalarMulNormalizeBatchSingletonG2Nonzero
import Ipp.Extracted.ArkworksScalarMulNormalizeBatchSingletonZero
import Ipp.Extracted.ArkworksMsm
import Ipp.Extracted.ArkworksG2Prepared
import Ipp.Extracted.ArkworksFinalExpSpec
import Ipp.Extracted.ArkworksMultiPairing
import Ipp.Extracted.ArkworksSubgroupCheck
import Ipp.Extracted.ArkworksMultiPairingGt
import Ipp.Bls12377Pairing
import Ipp.StrictG1Decode
import Ipp.StrictG2DecodeBridge
import Ipp.StrictGtDecode
import Ipp.AggregateSerialization
import Ipp.CanonicalSerializers
import Ipp.ChallengeMessageSerialization

/-!
Single audit surface for every campaign capstone compatible with the canonical
Fq12 extraction graph. The independently regenerated Miller graph is audited
in `Ipp.ProofAuditMiller` because it declares overlapping extracted globals.
-/

-- S1
-- The first three roots are retained as algebraic idealizations only.  The
-- publication ledger uses the experiment-relative computational roots below.
#print axioms Ipp.S1.s1_soundness
#print axioms Ipp.S1.invalid_goal_fork_bound_nonpositive
#print axioms Ipp.S1.invalid_proof_fork_bound_nonpositive
#print axioms Ipp.S1.s1Fork_success_lower_bound
#print axioms Ipp.S1.s1_computational_soundness
#print axioms Ipp.S1.invalid_goal_fork_bound_le_extraction_advantage
#print axioms Ipp.S1.invalid_proof_fork_bound_le_extraction_advantage
#print axioms Ipp.leaf_accept_to_base_of_structured
#print axioms Ipp.tree_to_acceptTree_of_structured
#print axioms Ipp.kzgFalseOpening_iff_lane
#print axioms Ipp.kzgVFalseOpening_relation
#print axioms Ipp.kzgWFalseOpening_relation
#print axioms Ipp.S1.treeHasKzgFalseOpening_iff_lane
#print axioms Ipp.S1.s1KzgBad_iff_lane
#print axioms Ipp.S1.s1PairingBad_iff_components
#print axioms Ipp.S1.s1KzgBad_probability_le_lane_sum
#print axioms Ipp.S1.s1PairingBad_probability_le_component_sum
#print axioms Ipp.S1.s1KzgVBad_iff_kzgVFalseOpeningGameWin
#print axioms Ipp.S1.s1KzgWBad_iff_kzgWFalseOpeningGameWin
#print axioms Ipp.S1.s1RootOpeningBad_iff_gipaRootOpeningGameWin
#print axioms Ipp.S1.s1ProductLaneBad_iff_gipaProductLaneGameWin
#print axioms Ipp.S1.s1KzgVBad_probability_eq_gameWin
#print axioms Ipp.S1.s1KzgWBad_probability_eq_gameWin
#print axioms Ipp.S1.s1RootOpeningBad_probability_eq_gameWin
#print axioms Ipp.S1.s1ProductLaneBad_probability_eq_gameWin
#print axioms Ipp.S1.kzg_false_opening_to_game_security
#print axioms Ipp.S1.gipa_fork_knowledge_reduction
#print axioms Ipp.S1.S1ExtractionSecurity.ofDeployedAssumptions
#print axioms Ipp.S1.kzg_false_opening_to_bls12377_security
#print axioms Ipp.S1.gipa_fork_knowledge_to_bls12377_security
#print axioms Ipp.S1.S1ExtractionSecurity.ofBls12377GameAssumptions

-- Independent goal, v1 projection, and symbolic cost model
#print axioms Ipp.Goal.no_omission_or_reordering
#print axioms Ipp.Goal.hasValidPrefixRepresentation_of_hasValidRepresentation
#print axioms Ipp.Goal.invalid_prefix_implies_invalid_padded
#print axioms Ipp.SnarkPackV1.accepts_eq_fsAccepts
#print axioms Ipp.SnarkPackV1.Refinement.represents_iff_rootOpens
#print axioms Ipp.SnarkPackV1.Refinement.validWithWitness_iff_all_ppe
#print axioms Ipp.SnarkPackV1.Refinement.hasValidRepresentation_iff
#print axioms Ipp.SnarkPackV1.Refinement.hasValidRealPrefixRepresentation_iff
#print axioms Ipp.SnarkPackV1.Refinement.invalid_realPrefix_implies_invalid_padded
#print axioms Ipp.ShippingAdaptiveSha.acceptedAlias_implies_collision
#print axioms Ipp.ShippingAdaptiveSha.adaptive_shipping_sha256_collision_reduction
#print axioms Ipp.ShippingAdaptiveSha.adaptive_real_acceptance_le_ideal_add_hash_losses
#print axioms Ipp.ShippingMultiStatement.globalQueryEncoding_ofRegistered
#print axioms Ipp.ShippingMultiStatement.globalQueryEncoding_fixed_key_injective
#print axioms Ipp.ShippingMultiStatement.globalFsVerifier_support_proof_eq
#print axioms Ipp.ShippingMultiStatement.OutcomeAt.roundQuery?_of_lt
#print axioms Ipp.ShippingMultiStatement.PackedOutcome.at?_self
#print axioms Ipp.ShippingMultiStatement.multiStatementFsGame_isTotalQueryBound
#print axioms Ipp.ShippingMultiStatement.leastInvalidOutcome?_mem
#print axioms Ipp.ShippingMultiStatement.bundle_acceptance_implies_least_invalid_acceptance
#print axioms Ipp.ShippingMultiStatement.rawForkSucceededAt_le_explicit_game_advantage
#print axioms Ipp.ShippingMultiStatement.FreshCacheCounterexample.adaptive_selection_beats_every_fixed_fresh
#print axioms Ipp.SnarkPackV1.HonestProver.honest_complete
#print axioms Ipp.Extracted.ShippingProver.shipping_prover_refines_honest_complete
#print axioms Ipp.Cost.prover_miller_terms
#print axioms Ipp.Cost.prover_final_exponentiations
#print axioms Ipp.Cost.prover_primary_fold_scalar_muls
#print axioms Ipp.Cost.prover_kzg_msm_terms
#print axioms Ipp.Cost.verifier_gt_subgroup_validations
#print axioms Ipp.Cost.verifier_gt_exponentiations
#print axioms Ipp.Cost.verifier_final_exponentiations

-- Extracted application planner and acceptance state machine
#print axioms Ipp.Extracted.AppVerifierStateMachine.extracted_family_code_matches_eq_model
#print axioms Ipp.Extracted.AppVerifierStateMachine.extracted_call_id_matches_eq_model
#print axioms Ipp.Extracted.AppVerifierStateMachine.extracted_plan_ids_eq_model
#print axioms Ipp.Extracted.AppVerifierStateMachine.extracted_segment_plan_eq_model
#print axioms Ipp.Extracted.AppVerifierStateMachine.extracted_family_count_eq_model
#print axioms Ipp.Extracted.AppVerifierStateMachine.extracted_plan_identity_eq_model
#print axioms Ipp.Extracted.AppVerifierStateMachine.extracted_plan_padding_eq_model
#print axioms Ipp.Extracted.AppVerifierStateMachine.extracted_reduce_eq_model
#print axioms Ipp.Extracted.AppVerifierStateMachine.app_plan_deterministic_exact
#print axioms Ipp.Extracted.AppVerifierStateMachine.app_plan_complete_noDuplicate
#print axioms Ipp.Extracted.AppVerifierStateMachine.app_reduce_accepts_iff_all_expected_accept
#print axioms Ipp.Extracted.AppVerifierStateMachine.app_reduce_permutation_invariant
#print axioms Ipp.Extracted.AppVerifierStateMachine.app_normal_profiled_acceptance_parity
#print axioms Ipp.Extracted.AppVerifierStateMachine.extracted_shipping_call_from_parts_exact
#print axioms Ipp.Extracted.AppVerifierStateMachine.extracted_shipping_wrapper_projection_from_parts_exact
#print axioms Ipp.Extracted.AppVerifierStateMachine.extracted_shipping_input_success_retains_wrapper
#print axioms Ipp.Extracted.AppVerifierStateMachine.extracted_shipping_input_success_exact
#print axioms Ipp.Extracted.AppVerifierStateMachine.extracted_repeat_final_rows_loopFuel_exact
#print axioms Ipp.Extracted.AppVerifierStateMachine.extracted_repeat_final_rows_loop_exact
#print axioms Ipp.Extracted.AppVerifierStateMachine.extracted_repeat_final_rows_core_exact
#print axioms Ipp.Extracted.AppVerifierStateMachine.extracted_repeat_final_rows_success_refines
#print axioms Ipp.Extracted.AppVerifierStateMachine.extracted_repeat_final_rows_success_postcondition
#print axioms Ipp.Extracted.AppVerifierStateMachine.shippingFamilyCode_represents
#print axioms Ipp.Extracted.AppVerifierStateMachine.extracted_shipping_projection_ok
#print axioms Ipp.Extracted.AppVerifierStateMachine.app_acceptance_binds_shipping_input
#print axioms Ipp.Extracted.ShippingRowConstruction.ExactRowConstruction.ofExtractedSuccess
#print axioms Ipp.Extracted.ShippingRowConstruction.validCounts
#print axioms Ipp.Extracted.ShippingRowConstruction.realPrefixExact
#print axioms Ipp.Extracted.ShippingRowConstruction.repeatFinalPadding
#print axioms Ipp.Extracted.ShippingRowConstruction.preserves_order_and_padding
#print axioms Ipp.Extracted.ShippingStatementConstruction.extracted_protocol_version_exact
#print axioms Ipp.Extracted.ShippingStatementConstruction.ConstructorExecution.outputExact
#print axioms Ipp.Extracted.ShippingStatementConstruction.accepted_constructor_retains_shipping_input
#print axioms Ipp.Extracted.ShippingStatementConstruction.supported_shipping_input_has_retained_output
#print axioms Ipp.Extracted.ShippingStatementConstruction.ExactSemanticBoundary.bindingContract
#print axioms Ipp.Extracted.ShippingStatementConstruction.ExactSemanticBoundary.projectionContract
#print axioms Ipp.Extracted.ShippingStatementConstruction.supported_constructor_projects_exact_statement

-- Concrete shipping input, adapter, and deployed-hash composition
#print axioms Ipp.ShippingV1.shipping_statement_binds_public_claim
#print axioms Ipp.ShippingV1.verified_call_binds_unique_shipping_input
#print axioms Ipp.ShippingV1.shipping_input_preserves_order_and_padding
#print axioms Ipp.ShippingV1.shipping_input_projects_exact_statement
#print axioms Ipp.Extracted.AggregateVerifier.arkworks_tipp_primitive_refinement_statement
#print axioms Ipp.Extracted.AggregateVerifier.arkworks_tipp_refinement_from_primitives
#print axioms Ipp.Extracted.AggregateVerifier.arkworks_acceptedAdapterContract
#print axioms Ipp.Extracted.AggregateVerifier.arkworks_shipping_acceptance_implies_snarkPackV1
#print axioms Ipp.Extracted.AggregateVerifier.arkworks_canonical_input_acceptance_implies_snarkPackV1
#print axioms Ipp.Extracted.ShippingVerifierComposition.shipping_tipp_input_exact
#print axioms Ipp.Extracted.ShippingVerifierComposition.shipping_adapter_input_exact
#print axioms Ipp.Extracted.ShippingVerifierComposition.decodedRandomizerMessage_eq_formal
#print axioms Ipp.Extracted.ShippingVerifierComposition.production_adapter_input_installed_exact
#print axioms Ipp.Extracted.ShippingVerifierComposition.production_adapter_input_projection
#print axioms Ipp.Extracted.ShippingVerifierComposition.accepted_app_adapter_call_refines_shipping_v1
#print axioms Ipp.Extracted.ShippingVerifierComposition.ShippingApplicationConstruction.projectionContract
#print axioms Ipp.Extracted.ShippingVerifierComposition.AcceptedShippingExecutionAt.appFacts
#print axioms Ipp.Extracted.ShippingVerifierComposition.AcceptedShippingExecutionAt.refines
#print axioms Ipp.Extracted.ShippingVerifierComposition.ShippingCallData.acceptedAt_refines_v1
#print axioms Ipp.Extracted.ShippingBundleComposition.ShippingCallExecutionBoundary.toAccepted
#print axioms Ipp.Extracted.ShippingBundleComposition.ShippingBundleCallWitness.refinesV1
#print axioms Ipp.Extracted.ShippingBundleComposition.accepted_bundle_lifts_per_call_claim
#print axioms Ipp.Extracted.ShippingBundleComposition.accepted_shipping_bundle_refines_all_v1
#print axioms Ipp.Extracted.ChallengeFrame.challenge_preimage_core_exact
#print axioms Ipp.Extracted.TippMippChallengeExecution.sampleEquations_of_calls
#print axioms Ipp.Extracted.TippMippChallengeExecution.acceptedExecutionSamples_of_calls
#print axioms Ipp.Extracted.TippMippChallengeExecution.AcceptedExecutionSamples.randomizerAtTranscript
#print axioms Ipp.Extracted.TippMippChallengeExecution.AcceptedExecutionSamples.x0AtTranscript
#print axioms Ipp.Extracted.TippMippChallengeExecution.AcceptedExecutionSamples.roundAtTranscript
#print axioms Ipp.Extracted.TippMippChallengeExecution.AcceptedExecutionSamples.bridgeAtTranscript
#print axioms Ipp.Extracted.TippMippChallengeExecution.AcceptedExecutionSamples.kzgAtTranscript
#print axioms Ipp.ShippingHashExecutionTrace.roundExecution_of_eval_eq_some
#print axioms Ipp.ShippingHashExecutionTrace.transcriptExecution_of_eval_eq_some
#print axioms Ipp.RandomOracleReindex.evalDist_randomOracle_reindex
#print axioms Ipp.ShippingHashGame.shippingDecodeFr_eq_some
#print axioms Ipp.ShippingHashGame.shippingDecodeFr_ne_none
#print axioms Ipp.ShippingScalarReduction.digestFiber_card
#print axioms Ipp.ShippingScalarReduction.uniformDigest_reduceFr_point_mass
#print axioms Ipp.ShippingScalarReduction.uniformDigest_reduceFr_tvDist_le
#print axioms Ipp.ShippingScalarReduction.simulate_reducedFresh_uniformFresh_tvDist_le
#print axioms Ipp.ShippingScalarReduction.simulate_reducedCaching_uniformCaching_tvDist_le
#print axioms Ipp.ShippingScalarReduction.modReductionBudget_mono
#print axioms Ipp.ShippingHashGame.reducedCaching_fieldAttempt_evalDist_eq_attemptIdeal
#print axioms Ipp.ShippingHashGame.uniformCaching_fieldAttempt_evalDist_eq_fieldAttemptIdeal
#print axioms Ipp.ShippingHashGame.attemptIdeal_acceptance_le_fieldAttempt_add_modReduction
#print axioms Ipp.ShippingHashGame.lastNonce_add_one
#print axioms Ipp.ShippingHashGame.nonceBytes_injective_of_lt
#print axioms Ipp.ShippingHashGame.basePoint_pair_injective
#print axioms Ipp.ShippingHashGame.shippingPreimage_bounded_injective
#print axioms Ipp.ShippingHashGame.shippingAttemptPreimage_injective
#print axioms Ipp.ShippingHashGame.evalDist_queryDecodedAttemptOracleFull
#print axioms Ipp.ShippingHashGame.reindexedByteIdealVerifier_evalDist_eq_attempt
#print axioms Ipp.ShippingHashGame.evalWithAnswerFn_queryDecodedOracle
#print axioms Ipp.ShippingHashGame.shippingIdealQuery_support_iff_exists_consistent
#print axioms Ipp.ShippingHashGame.fsAccepts_eraseTranscriptNonces_iff
#print axioms Ipp.ShippingHashGame.queryDecoded_exhausts
#print axioms Ipp.ShippingHashGame.queryDecoded_success_at_offset
#print axioms Ipp.ShippingHashGame.queryDecoded_u64_exhausts
#print axioms Ipp.ShippingHashGame.shippingReal_acceptance_le_ideal_add_hashAdvantage
#print axioms Ipp.ShippingHashGame.shippingIdeal_acceptance_le_fsProbComp_add_modReduction
#print axioms Ipp.ShippingHashGame.shippingReal_acceptance_le_fsProbComp_add_modReduction_add_hashAdvantage
#print axioms Ipp.ShippingHashGame.shipping_invalid_goal_quantitative_bound
#print axioms Ipp.ShippingHashGame.shipping_invalid_goal_quantitative_bound_computational
#print axioms Ipp.ShippingRealVerifier.real_acceptance_le_ideal_add_explicit_hash_losses
#print axioms Ipp.ShippingRealVerifier.RawAcceptedExecution.randomizer_nonzero
#print axioms Ipp.ShippingRealVerifier.shippingReal_transcriptOption_eq_some
#print axioms Ipp.ShippingRealVerifier.shippingReal_transcriptExecution
#print axioms Ipp.ShippingRealVerifier.DeployedChallengeTrace.nonempty_ofAcceptedExecutionSamples
#print axioms Ipp.ShippingRealVerifier.DeployedChallengeTrace.answers
#print axioms Ipp.ShippingRealVerifier.shippingIdeal_resultOrigin
#print axioms Ipp.ShippingRealVerifier.shippingReal_resultOrigin
#print axioms Ipp.ShippingRealVerifier.idealCallAcceptance_le_shippingIdeal
#print axioms Ipp.ShippingRealVerifier.acceptedCallOutput_refines_shipping_v1
#print axioms Ipp.ShippingRealVerifier.realCallAcceptance_le_realFormalCallAcceptance
#print axioms Ipp.ShippingRealVerifier.accepted_call_binding_alias_implies_shaBad
#print axioms Ipp.ShippingRealVerifier.accepted_call_binds_intended_or_shaBad
#print axioms Ipp.ShippingRealVerifier.shippingRealCall_acceptance_le_fsProbComp
#print axioms Ipp.ShippingToGoal.shipping_execution_refines_ordered_goal
#print axioms Ipp.ShippingToGoal.shipping_to_goal_quantitative_from_refinement
#print axioms Ipp.ShippingToGoal.shipping_to_goal_quantitative
#print axioms Ipp.ShippingToGoal.shipping_call_to_goal_quantitative

-- S2 aggregate refinement and error behavior
#print axioms Ipp.Extracted.hax_translated_g2_kzg_product_evaluation
#print axioms Ipp.Extracted.hax_translated_g2_kzg_product_evaluation_coefficients
#print axioms Ipp.Extracted.hax_translated_verify_g2_kzg_eq
#print axioms Ipp.Extracted.hax_translated_verify_g2_kzg_true_iff
#print axioms Ipp.Extracted.hax_translated_verify_g2_kzg_opening_eq
#print axioms Ipp.Extracted.hax_translated_verify_g2_kzg_opening_true_iff
#print axioms Ipp.Extracted.hax_translated_verify_g1_kzg_eq
#print axioms Ipp.Extracted.hax_translated_verify_g1_kzg_true_iff
#print axioms Ipp.Extracted.hax_translated_verify_g1_kzg_opening_eq
#print axioms Ipp.Extracted.hax_translated_verify_g1_kzg_opening_true_iff
#print axioms Ipp.Extracted.verify_base_commitment_refinement
#print axioms Ipp.Extracted.fold_public_inputs_refinement_statement
#print axioms Ipp.Extracted.verify_ppe_refinement_eq
#print axioms Ipp.Extracted.verify_ppe_refinement_statement
#print axioms Ipp.Extracted.verify_combined_ppe_refinement_statement
#print axioms Ipp.Extracted.VerifyTippMipp.verify_tipp_mipp_refinement_statement
#print axioms Ipp.Extracted.CombinedChecks.run_empty
#print axioms Ipp.Extracted.CombinedChecks.run_not_power_of_two
#print axioms Ipp.Extracted.CombinedChecks.run_round_mismatch
#print axioms Ipp.Extracted.CombinedChecks.run_tipp_error
#print axioms Ipp.Extracted.CombinedChecks.accepted_path
#print axioms Ipp.Extracted.CombinedChecks.accepted_implies_semantics
#print axioms Ipp.Extracted.CombinedChecks.run_refinement_statement
#print axioms Ipp.Extracted.CombinedChecks.verify_combined_checks_refinement_statement
#print axioms Ipp.Extracted.AggregateAdapter.accepted_path
#print axioms Ipp.Extracted.AggregateAdapter.aggregate_adapter_core_input_from_parts_exact
#print axioms Ipp.Extracted.AggregateAdapter.combined_checks_core_input_from_parts_exact
#print axioms Ipp.Extracted.AggregateAdapter.tipp_mipp_core_input_from_parts_exact
#print axioms Ipp.Extracted.AggregateAdapterProjection.installed_ppe_true_iff
#print axioms Ipp.Extracted.AggregateVerifier.adapter_core_acceptance_implies_snarkPackV1
#print axioms Ipp.Extracted.AggregateVerifier.pairing_adapter_acceptance_implies_snarkPackV1
#print axioms Ipp.Bls12377.g1PrimeSubgroupModule
#print axioms Ipp.Bls12377.g2PrimeSubgroupModule
#print axioms Ipp.Bls12377.arkPairingOutputModule
#print axioms Ipp.Bls12377.executablePairingLinear
#print axioms Ipp.Bls12377.executablePairingLinear_apply
#print axioms Ipp.Bls12377.statementWithExecutablePairing_e
#print axioms Ipp.Bls12377.tippPairingEffect_failure
#print axioms Ipp.Bls12377.tippPairingEffect_two_pair_law
#print axioms Ipp.Bls12377.prepareNegative_value
#print axioms Ipp.Bls12377.preparedPairingEffect_two_pair_law
#print axioms Ipp.Bls12377.preparedPairingEffect_failure
#print axioms Ipp.Bls12377.ppePairingAdapterLaws

-- Fq and Fr
#print axioms Ipp.Extracted.ArkworksFqMul.decode_extracted_mul
#print axioms Ipp.Extracted.ArkworksFqOps.decode_extracted_add
#print axioms Ipp.Extracted.ArkworksFqOps.decode_extracted_sub
#print axioms Ipp.Extracted.ArkworksFqOps.decode_extracted_neg
#print axioms Ipp.Extracted.ArkworksFqSquare.decode_extracted_square
#print axioms Ipp.Extracted.ArkworksFqInv.decode_extracted_inv
#print axioms Ipp.Extracted.ArkworksFqSqrtBytes.decode_extracted_sqrt
#print axioms Ipp.Extracted.ArkworksFqSqrtBytes.from_bytes_decodeFqCanonical_bridge
#print axioms Ipp.Extracted.ArkworksFqSqrtBytes.to_bytes_value_spec
#print axioms Ipp.Extracted.ArkworksFr.decode_extracted_mul
#print axioms Ipp.Extracted.ArkworksFr.decode_extracted_add
#print axioms Ipp.Extracted.ArkworksFr.decode_extracted_sub
#print axioms Ipp.Extracted.ArkworksFr.decode_extracted_neg
#print axioms Ipp.Extracted.ArkworksFr.decode_extracted_inv
#print axioms Ipp.Extracted.ArkworksFr.from_bytes_value_spec
#print axioms Ipp.Extracted.ArkworksFr.bytes_to_limbs_value_spec

-- Fq2/Fq6/Fq12 tower
#print axioms Ipp.Extracted.ArkworksFq2.extracted_fq2_mul_spec
#print axioms Ipp.Extracted.ArkworksFq2.extracted_fq2_square_spec
#print axioms Ipp.Extracted.ArkworksFq2.extracted_fq2_inv_some_spec
#print axioms Ipp.Extracted.ArkworksFq2.extracted_fq2_inv_none_iff
#print axioms Ipp.Extracted.ArkworksFq2.decode_fq2_frobenius
#print axioms Ipp.Extracted.ArkworksFq2.decode_extracted_fq2_sqrt
#print axioms Ipp.Extracted.ArkworksFq6.canonical_field_fq6_mul
#print axioms Ipp.Extracted.ArkworksFq6.canonical_field_fq6_square
#print axioms Ipp.Extracted.ArkworksFq6.canonical_field_fq6_inv
#print axioms Ipp.Extracted.ArkworksFq6.decode_fq6_frobenius_one
#print axioms Ipp.Extracted.ArkworksFq6.decode_fq6_frobenius_two
#print axioms Ipp.Extracted.ArkworksFq12.decode_fq12_mul
#print axioms Ipp.Extracted.ArkworksFq12.decode_fq12_square
#print axioms Ipp.Extracted.ArkworksFq12.decode_fq12_inv_some
#print axioms Ipp.Extracted.ArkworksFq12.decode_fq12_inv_none
#print axioms Ipp.Extracted.ArkworksFq12.decode_fq12_frobenius_one
#print axioms Ipp.Extracted.ArkworksFq12.decode_fq12_frobenius_two
#print axioms Ipp.Extracted.ArkworksFq12.decode_fq12_cyclotomic_square
#print axioms Ipp.Extracted.ArkworksFq12.decode_fq12_cyclotomic_exp
#print axioms Ipp.Extracted.ArkworksFq12.decode_fq12_to_bytes
#print axioms Ipp.Extracted.ArkworksFq12.decode_fq12_from_bytes_exact

-- Complete G1/G2 group-law refinements
#print axioms Ipp.Extracted.ArkworksG1.executed_g1_add_generic_refines_mathlib
#print axioms Ipp.Extracted.ArkworksG1.executed_g1_add_mixed_generic_refines_mathlib
#print axioms Ipp.Extracted.ArkworksG1.executed_g1_double_generic_refines_mathlib
#print axioms Ipp.Extracted.ArkworksG1.executed_g1_double_order2_refines_mathlib
#print axioms Ipp.Extracted.ArkworksG1.executed_g1_neg_finite_refines_mathlib
#print axioms Ipp.Extracted.ArkworksG1.executed_g1_neg_identity_refines_mathlib
#print axioms Ipp.Extracted.ArkworksG1.executed_g1_add_left_identity_refines_mathlib
#print axioms Ipp.Extracted.ArkworksG1.executed_g1_add_right_identity_refines_mathlib
#print axioms Ipp.Extracted.ArkworksG1.executed_g1_add_mixed_identity_refines_mathlib
#print axioms Ipp.Extracted.ArkworksG1.executed_g1_double_identity_refines_mathlib
#print axioms Ipp.Extracted.ArkworksG1.executed_g1_add_opposite_refines_mathlib
#print axioms Ipp.Extracted.ArkworksG1.executed_g1_add_mixed_opposite_refines_mathlib
#print axioms Ipp.Extracted.ArkworksG1.executed_g1_add_equal_refines_mathlib
#print axioms Ipp.Extracted.ArkworksG1.executed_g1_add_mixed_equal_refines_mathlib
#print axioms Ipp.Extracted.ArkworksG2.executed_g2_add_generic_refines_mathlib
#print axioms Ipp.Extracted.ArkworksG2.executed_g2_add_mixed_generic_refines_mathlib
#print axioms Ipp.Extracted.ArkworksG2.executed_g2_double_generic_refines_mathlib
#print axioms Ipp.Extracted.ArkworksG2.executed_g2_double_order2_refines_mathlib
#print axioms Ipp.Extracted.ArkworksG2.executed_g2_neg_finite_refines_mathlib
#print axioms Ipp.Extracted.ArkworksG2.executed_g2_neg_identity_refines_mathlib
#print axioms Ipp.Extracted.ArkworksG2.executed_g2_add_left_identity_refines_mathlib
#print axioms Ipp.Extracted.ArkworksG2.executed_g2_add_right_identity_refines_mathlib
#print axioms Ipp.Extracted.ArkworksG2.executed_g2_add_mixed_identity_refines_mathlib
#print axioms Ipp.Extracted.ArkworksG2.executed_g2_double_identity_refines_mathlib
#print axioms Ipp.Extracted.ArkworksG2.executed_g2_add_opposite_refines_mathlib
#print axioms Ipp.Extracted.ArkworksG2.executed_g2_add_mixed_opposite_refines_mathlib
#print axioms Ipp.Extracted.ArkworksG2.executed_g2_add_equal_refines_mathlib
#print axioms Ipp.Extracted.ArkworksG2.executed_g2_add_mixed_equal_refines_mathlib

-- Scalar multiplication, normalization, and MSM
#print axioms Ipp.Extracted.ArkworksScalarMul.valid_g1_mul_affine
#print axioms Ipp.Extracted.ArkworksScalarMul.valid_g2_mul_projective
#print axioms Ipp.Extracted.ArkworksScalarMul.valid_g2_mul_affine
#print axioms Ipp.Extracted.ArkworksScalarMul.valid_g1_glv_mul_projective
#print axioms Ipp.Extracted.ArkworksScalarMulNormalize.valid_g1_into_affine
#print axioms Ipp.Extracted.ArkworksScalarMulNormalize.valid_g2_into_affine
#print axioms Ipp.Extracted.ArkworksScalarMulNormalize.valid_g1_normalize_batch_general
#print axioms Ipp.Extracted.ArkworksScalarMulNormalize.valid_g2_normalize_batch_general
#print axioms Ipp.Extracted.ArkworksScalarMulNormalize.valid_g1_normalize_batch_all_infinity
#print axioms Ipp.Extracted.ArkworksScalarMulNormalize.valid_g2_normalize_batch_all_infinity
#print axioms Ipp.Extracted.ArkworksScalarMulNormalize.valid_g1_normalize_batch_singleton_nonzero
#print axioms Ipp.Extracted.ArkworksScalarMulNormalize.valid_g2_normalize_batch_singleton_nonzero
#print axioms Ipp.Extracted.ArkworksScalarMulNormalize.valid_g1_normalize_batch_singleton_zero
#print axioms Ipp.Extracted.ArkworksMsm.executed_g1_msm
#print axioms Ipp.Extracted.ArkworksMsm.executed_g2_msm

-- Prepared G2, final exponentiation, pairing, and subgroup checks
#print axioms Ipp.Extracted.ArkworksG2PreparedValid.valid_g2_prepared
#print axioms Ipp.Extracted.ArkworksFinalExpEasy.final_exp_easy_cyclotomic
#print axioms Ipp.Extracted.ArkworksFinalExpHard.final_exp_spec
#print axioms Ipp.Extracted.ArkworksMultiPairing.multi_pairing_spec
#print axioms Ipp.Extracted.ArkworksMultiPairing.multi_pairing_product_spec
#print axioms Ipp.Extracted.ArkworksMultiPairingGt.arkworksPairingExponent_eq_executedPairingExponent
#print axioms Ipp.Extracted.ArkworksMultiPairingGt.pairingModel_eq_gtValue
#print axioms Ipp.Extracted.ArkworksSubgroupCheck.valid_g1_subgroup_check
#print axioms Ipp.Extracted.ArkworksSubgroupCheck.valid_g2_subgroup_check
#print axioms Ipp.Bls12377.PublishedPairingBilinearNondegenerate

-- Strict decoding and serialization
#print axioms Ipp.StrictG1Decode.g1_strict_checked_success_iff
#print axioms Ipp.StrictG1Decode.g1_strict_checked_byte_injective
#print axioms Ipp.StrictG2Decode.g2_strict_checked_success_iff
#print axioms Ipp.StrictG2Decode.g2_strict_checked_byte_injective
#print axioms Ipp.StrictGtDecode.gt_strict_checked_success_iff
#print axioms Ipp.StrictGtDecode.gt_strict_checked_byte_injective
#print axioms Ipp.AggregateSerialization.aggregate_strict_decode_injective
#print axioms Ipp.AggregateSerialization.aggregate_layout_component_acceptance_conformance
#print axioms Ipp.ChallengeMessageSerialization.challenge_message_serialize_injective
#print axioms Ipp.ChallengeMessageSerialization.challenge_preimage_typed_injective
