import Ipp.Extracted.TippMippAcceptedRunProjection
import Ipp.ShippingDeployedHashTraceConstruction

/-!
Audit surface for deployed accepted-run challenge-trace construction.
-/

#print axioms Ipp.Extracted.TippMippAcceptedRunProjection.runTipp_success_has_effect_trace
#print axioms Ipp.Extracted.TippMippAcceptedRunProjection.acceptedRunCallProjection
#print axioms Ipp.ShippingDeployedHashTraceConstruction.acceptedExecution_challengePrimitiveContract_of_decoded
#print axioms Ipp.ShippingDeployedHashTraceConstruction.deployed_hash_trace_construction
