#!/usr/bin/env bash
# Helper script to prepare a localhost postgres instance,
# provisioned via nix, for ingesting ABCI events from CometBFT for Shieldd.
set -euo pipefail

shieldd_devnet_home="${SHIELDD_DEVNET_HOME:-$HOME/.shieldd}"

# Set up a write-friendly directory for postgres state.
# The nix store is read-only by default, so add write capability to copy.
postgres_config_dir="${shieldd_devnet_home}/network_data/postgresql"
# While debugging it may be useful to nuke the dir between runs.
# rm -rf "$postgres_config_dir"
mkdir -p "${postgres_config_dir}"

# If PG_VERSION exists, then the initdb cmd has already been run.
if [[ -e "${postgres_config_dir}/PG_VERSION" ]] ; then
    >&2 echo "Postgres database already configured in '${postgres_config_dir}', skipping initdb..."
else
    pg_ctl initdb --pgdata "${postgres_config_dir}"
fi
