#!/usr/bin/env bash
# Utility script to automate publishing the workspace packages to crates.io
# Requires:
#
#   1. `cargo-release` (present in nix env)
#   2. env var CARGO_REGISTRY_TOKEN with sufficient rights
#
# This script assumes that a developer has already bumped the requisite version,
# by running:
#
#   cargo release --no-publish $VERSION --execute
#
# Then the resulting commits and tags can be pushed to the repo, which will trigger
# the running of this script.
set -euo pipefail


# Check deps
if ! hash cargo-release > /dev/null 2>&1 ; then
  >&2 echo "ERROR: cargo-release not found on PATH"
  exit 1
fi

if [[ -z "${CARGO_REGISTRY_TOKEN:-}" ]] ; then
  >&2 echo "ERROR: CARGO_REGISTRY_TOKEN not set"
  exit 2
fi

# Retrieve workspace-wide version from the top-level Cargo.toml.
target_version="$(toml get Cargo.toml workspace.package.version -r)"

# Check for local changes to working tree, and error out if any.
s="$(git status --porcelain)"
if [[ -n "$s" ]]; then
  >&2 echo "ERROR: found modified files that should be committed:"
  >&2 echo "$s"
  git diff | head -n 128
  exit 1
fi

# Slow down the crate publishing, to avoid hitting a 429 ratelimit.
# Normally the per-crate compilation checks would slow things down enough,
# but we skip those.
export PUBLISH_GRACE_SLEEP="20"

>&2 echo "Publishing crate versions '$target_version' to crates.io..."
# Run the publish command.
cargo release publish --execute --no-confirm
