#!/bin/bash
# CI script to manage a standalone fullnode, created in order to exercise
# direct serving of pd. This script is intended to be run from CI,
# communicating with a remote node over SSH and munging its state.
set -euo pipefail
set -x

# Unpack args. Different CI workflows can override these settings,
# to determine whether we're targeting testnet or preview.
SHIELDD_VERSION="${SHIELDD_VERSION:-main}"
SHIELDD_ENVIRONMENT="${SHIELDD_ENVIRONMENT:-shieldd-preview}"

if [[ -z "$SHIELDD_VERSION" || -z "$SHIELDD_ENVIRONMENT" ]] ; then
    >&2 echo "ERROR: required env vars not set: SHIELDD_VERSION, SHIELDD_ENVIRONMENT"
    exit 1
fi

if [[ "$SHIELDD_ENVIRONMENT" = "shieldd-preview" ]] ; then
    ci_ssh_host="solo-pd.testnet-preview.plinfra.net"
elif [[ "$SHIELDD_ENVIRONMENT" = "shieldd-testnet" ]] ; then
    ci_ssh_host="solo-pd.testnet.plinfra.net"
else
    >&2 echo "ERROR: unsupported SHIELDD_ENVIRONMENT: '$SHIELDD_ENVIRONMENT'"
    exit 2
fi

# Communicate with target host over SSH, run the script.
# The remote box has been provisioned with:
#
#   1) an ssh keypair assigned to admin user `ci`
#   2) a normal user account `shieldd` for running services
#   3) systemd service files for pd & cometbft
#
# As for the script that's being execute on the target, we'll copy that up from local context.
scp ./deployments/scripts/redeploy-ci-fullnode-via-remote "ci@${ci_ssh_host}:"
ssh -l ci "$ci_ssh_host" sudo mv redeploy-ci-fullnode-via-remote /usr/local/bin/redeploy-ci-fullnode-via-remote
ssh -l ci "$ci_ssh_host" sudo /usr/local/bin/redeploy-ci-fullnode-via-remote "$SHIELDD_VERSION" "$SHIELDD_ENVIRONMENT"
