[package]
name = "shieldd-sdk-wallet"
version = {workspace = true}
authors = {workspace = true}
edition = {workspace = true}
description = "The wallet software for the Shieldd Zone"
repository = {workspace = true}
license = {workspace = true}
publish = true

[features]
default = []
parallel = ["shieldd-sdk-transaction/parallel"]

[dependencies]
anyhow = {workspace = true}
ark-std = {workspace = true, default-features = false}
bincode = {workspace = true}
bytes = {workspace = true}
decaf377 = {workspace = true, default-features = true}
hex = {workspace = true}
shieldd-sdk-app = {workspace = true, default-features = false}
shieldd-sdk-asset = {workspace = true, default-features = true}
shieldd-sdk-custody = {workspace = true}
shieldd-sdk-fee = {workspace = true, default-features = false}
shieldd-sdk-keys = {workspace = true, default-features = true}
shieldd-sdk-num = {workspace = true, default-features = true}
shieldd-sdk-proto = {workspace = true, default-features = true}
shieldd-sdk-tct = {workspace = true, default-features = true}
shieldd-sdk-sct = {workspace = true, default-features = false}
shieldd-sdk-transaction = {workspace = true, default-features = true}
shieldd-sdk-view = {workspace = true}
pin-project = {workspace = true}
rand = {workspace = true}
rand_core = {workspace = true, features = ["getrandom"]}
serde = {workspace = true, features = ["derive"]}
serde_json = {workspace = true}
tokio = {workspace = true, features = ["full"]}
tonic = {workspace = true}
tower = {workspace = true, features = ["full"]}
tracing = {workspace = true}

[dev-dependencies]
once_cell = {workspace = true}
proptest = {workspace = true}
proptest-derive = {workspace = true}
