[package]
name = "shieldd-sdk-wallet"
version = {workspace = true}
authors = {workspace = true}
edition = {workspace = true}
description = "The wallet software for the Shieldd Zone"
repository = {workspace = true}
license = {workspace = true}
publish = true

[features]
default = []
parallel = ["shieldd-sdk-transaction/parallel"]

[dependencies]
anyhow = {workspace = true}
shieldd-sdk-custody = {workspace = true}
shieldd-sdk-keys = {workspace = true, default-features = true}
shieldd-sdk-proto = {workspace = true, default-features = true}
shieldd-sdk-transaction = {workspace = true, default-features = true}
shieldd-sdk-view = {workspace = true}
rand_core = {workspace = true, features = ["getrandom"]}
tonic = {workspace = true}
tracing = {workspace = true}
