import ShielddGnarkFormal.Deployed.Contracts.ShieldedIcs20Withdrawal.CircuitFacts

set_option maxRecDepth 1000000
set_option maxHeartbeats 8000000

/-!
Stable exact-provider inventory grouped by all eight Withdrawal protocol
obligations. Semantic refinement is supplied separately by the static
Withdrawal translator.
GENERATED by gen_deployed_family.py — do not edit by hand.
-/

namespace Shieldd.GnarkFormal.Deployed.Contracts.ShieldedIcs20Withdrawal

open Shieldd.GnarkFormal

/-- Exact provider inventory for the `canonicalSender` obligation. -/
structure CanonicalSenderExactProviders (rho : Nat → DeployedF) : Prop where
  authAkNonIdentity : Seg3.contract.spec rho
  senderDivGenNonIdentity : Seg4.contract.spec rho
  senderDivGenCompress : Seg5.contract.spec rho
  incomingViewingKeyNonzero : Seg6.contract.spec rho
  senderDtk : Seg7.contract.spec rho
  senderTransmissionCompress : Seg8.contract.spec rho
  senderTransmissionNonIdentity : Seg9.contract.spec rho

/-- Exact provider inventory for the `requiredSpend` obligation. -/
structure RequiredSpendExactProviders (rho : Nat → DeployedF) : Prop where
  requiredNoteCommitment : Seg28.contract.spec rho
  requiredNullifier : Seg29.contract.spec rho
  requiredStatePath : Seg30.contract.spec rho
  requiredRvk : Seg31.contract.spec rho
  requiredRkCompress : Seg32.contract.spec rho
  requiredNullifierAssert : Seg33.contract.spec rho
  requiredAnchorAssert : Seg34.contract.spec rho
  requiredRkEquivalent : Seg35.contract.spec rho

/-- Exact provider inventory for the `optionalSpend` obligation. -/
structure OptionalSpendExactProviders (rho : Nat → DeployedF) : Prop where
  optionalNoteCommitment : Seg38.contract.spec rho
  optionalNullifier : Seg39.contract.spec rho
  optionalStatePath : Seg40.contract.spec rho
  optionalRvk : Seg41.contract.spec rho
  optionalRkCompress : Seg42.contract.spec rho
  optionalIsDummyBoolean : Seg43.contract.spec rho
  optionalSyntheticNullifier : Seg44.contract.spec rho
  optionalNullifierMux : Seg45.contract.spec rho
  optionalNullifierAssert : Seg46.contract.spec rho
  optionalAnchorAssert : Seg47.contract.spec rho
  optionalRkEquivalent : Seg48.contract.spec rho
  optionalAmountZero : Seg49.contract.spec rho

/-- Exact provider inventory for the `changeOutput` obligation. -/
structure ChangeOutputExactProviders (rho : Nat → DeployedF) : Prop where
  changeNoteCommitment : Seg52.contract.spec rho
  changeNoteAssert : Seg53.contract.spec rho

/-- Exact provider inventory for the `assetRegistry` obligation. -/
structure AssetRegistryExactProviders (rho : Nat → DeployedF) : Prop where
  isRegulatedBoolean : Seg1.contract.spec rho
  assetLeaf : Seg10.contract.spec rho
  assetPath : Seg11.contract.spec rho
  assetRootAssert : Seg12.contract.spec rho
  assetIdNonzero : Seg13.contract.spec rho
  assetGap : Seg14.contract.spec rho
  assetGapAccept : Seg15.contract.spec rho

/-- Exact provider inventory for the `senderCompliance` obligation. -/
structure SenderComplianceExactProviders (rho : Nat → DeployedF) : Prop where
  senderComplianceLeaf : Seg16.contract.spec rho
  senderCompliancePath : Seg17.contract.spec rho
  senderComplianceAssert : Seg18.contract.spec rho

/-- Exact provider inventory for the `conservation` obligation. -/
structure ConservationExactProviders (rho : Nat → DeployedF) : Prop where
  conservationNetBalance : Seg55.contract.spec rho
  conservationBalanceCompress : Seg56.contract.spec rho

/-- Exact provider inventory for the `statementBinding` obligation. -/
structure StatementBindingExactProviders (rho : Nat → DeployedF) : Prop where
  routingPrecisionSelect : Seg19.contract.spec rho
  routingParametersHash : Seg20.contract.spec rho
  routingParametersBind : Seg21.contract.spec rho
  routingSenderRouteWord : Seg22.contract.spec rho
  routingTag0PublicRange : Seg23.contract.spec rho
  routingTag0RouteBits : Seg24.contract.spec rho
  routingTag0RandomWord : Seg25.contract.spec rho
  routingTag0Compose : Seg26.contract.spec rho
  statementBlock0 : Seg58.contract.spec rho
  statementBlock1 : Seg59.contract.spec rho
  statementBlock2 : Seg60.contract.spec rho
  statementAssert : Seg61.contract.spec rho

structure WithdrawalExactProviders (rho : Nat → DeployedF) : Prop where
  canonicalSender : CanonicalSenderExactProviders rho
  requiredSpend : RequiredSpendExactProviders rho
  optionalSpend : OptionalSpendExactProviders rho
  changeOutput : ChangeOutputExactProviders rho
  assetRegistry : AssetRegistryExactProviders rho
  senderCompliance : SenderComplianceExactProviders rho
  conservation : ConservationExactProviders rho
  statementBinding : StatementBindingExactProviders rho

/-- Exhaustive stable grouping of every exact provider used by refinement. -/
theorem withdrawalExactProviders
    (rho : Nat → DeployedF)
    (facts : ShieldedIcs20WithdrawalCircuitFacts rho) :
    WithdrawalExactProviders rho := by
  exact {
    canonicalSender := {
      authAkNonIdentity := facts.canonicalSender.AssertDecafNonIdentitySeg3
      senderDivGenNonIdentity := facts.canonicalSender.AssertDecafNonIdentitySeg4
      senderDivGenCompress := facts.canonicalSender.DecafCompressToFieldSeg5
      incomingViewingKeyNonzero := facts.canonicalSender.AssertNeSeg6
      senderDtk := facts.canonicalSender.DecafDiversifiedTransmissionKeySeg7
      senderTransmissionCompress := facts.canonicalSender.DecafCompressToFieldSeg8
      senderTransmissionNonIdentity := facts.canonicalSender.AssertDecafNonIdentitySeg9
    }
    requiredSpend := {
      requiredNoteCommitment := facts.requiredSpend.GadgetNoteCommitmentSeg28
      requiredNullifier := facts.requiredSpend.GadgetNullifierSeg29
      requiredStatePath := facts.requiredSpend.GadgetStateCommitmentPathSeg30
      requiredRvk := facts.requiredSpend.DecafRandomizedVerificationKeySeg31
      requiredRkCompress := facts.requiredSpend.DecafCompressToFieldSeg32
      requiredNullifierAssert := facts.requiredSpend.AssertEqSeg33
      requiredAnchorAssert := facts.requiredSpend.AssertEqSeg34
      requiredRkEquivalent := facts.requiredSpend.DecafAssertEquivalentSeg35
    }
    optionalSpend := {
      optionalNoteCommitment := facts.optionalSpend.GadgetNoteCommitmentSeg38
      optionalNullifier := facts.optionalSpend.GadgetNullifierSeg39
      optionalStatePath := facts.optionalSpend.GadgetStateCommitmentPathSeg40
      optionalRvk := facts.optionalSpend.DecafRandomizedVerificationKeySeg41
      optionalRkCompress := facts.optionalSpend.DecafCompressToFieldSeg42
      optionalIsDummyBoolean := facts.optionalSpend.AssertBooleanSeg43
      optionalSyntheticNullifier := facts.optionalSpend.GadgetSyntheticDummyNullifierSeg44
      optionalNullifierMux := facts.optionalSpend.DummyMuxSeg45
      optionalNullifierAssert := facts.optionalSpend.AssertEqSeg46
      optionalAnchorAssert := facts.optionalSpend.AssertEqIfSeg47
      optionalRkEquivalent := facts.optionalSpend.DecafAssertEquivalentIfSeg48
      optionalAmountZero := facts.optionalSpend.AssertEqIfSeg49
    }
    changeOutput := {
      changeNoteCommitment := facts.changeOutput.GadgetNoteCommitmentSeg52
      changeNoteAssert := facts.changeOutput.AssertEqSeg53
    }
    assetRegistry := {
      isRegulatedBoolean := facts.assetRegistry.AssertBooleanSeg1
      assetLeaf := facts.assetRegistry.GadgetAssetRegistryLeafHashSeg10
      assetPath := facts.assetRegistry.GadgetAssetRegistryPathSeg11
      assetRootAssert := facts.assetRegistry.AssertEqSeg12
      assetIdNonzero := facts.assetRegistry.AssertNeSeg13
      assetGap := facts.assetRegistry.GadgetAssetRegistryGapSeg14
      assetGapAccept := facts.assetRegistry.AssertEqSeg15
    }
    senderCompliance := {
      senderComplianceLeaf := facts.senderCompliance.GadgetComplianceLeafSeg16
      senderCompliancePath := facts.senderCompliance.GadgetCompliancePathSeg17
      senderComplianceAssert := facts.senderCompliance.AssertEqIfSeg18
    }
    conservation := {
      conservationNetBalance := facts.conservation.DecafConservationNetBalanceCommitment2Seg55
      conservationBalanceCompress := facts.conservation.DecafCompressToFieldSeg56
    }
    statementBinding := {
      routingPrecisionSelect := facts.statementBinding.RoutingPrecisionSelectSeg19
      routingParametersHash := facts.statementBinding.RoutingParametersHashSeg20
      routingParametersBind := facts.statementBinding.RoutingParametersBindSeg21
      routingSenderRouteWord := facts.statementBinding.RoutingRouteWordSeg22
      routingTag0PublicRange := facts.statementBinding.RoutingTagPublicRangeSeg23
      routingTag0RouteBits := facts.statementBinding.RoutingTagRouteBitsSeg24
      routingTag0RandomWord := facts.statementBinding.RoutingTagRandomWordSeg25
      routingTag0Compose := facts.statementBinding.RoutingTagComposeSeg26
      statementBlock0 := facts.statementBinding.StatementHashSeg58
      statementBlock1 := facts.statementBinding.StatementHashSeg59
      statementBlock2 := facts.statementBinding.StatementHashSeg60
      statementAssert := facts.statementBinding.AssertEqSeg61
    }
  }

end Shieldd.GnarkFormal.Deployed.Contracts.ShieldedIcs20Withdrawal
