[package]
name = "shieldd-sdk-fee"
authors = {workspace = true}
repository = {workspace = true}
description = "Multidimensional fee implementation for Shieldd"
version = {workspace = true}
license = {workspace = true}
edition = {workspace = true}

[features]
component = [
    "cnidarium-component",
    "cnidarium",
    "shieldd-sdk-proto/cnidarium",
]
default = ["std", "component"]
std = []
docsrs = []

[dependencies]
shieldd-sdk-crypto.workspace = true
ff.workspace = true
group.workspace = true
reddsa.workspace = true
shieldd-sdk-proof-params.workspace = true
anyhow = {workspace = true}
async-trait = {workspace = true}
cnidarium = {workspace = true, optional = true, default-features = true}
cnidarium-component = {workspace = true, optional = true, default-features = true}
shieldd-sdk-asset = {workspace = true, default-features = false}
shieldd-sdk-num = {workspace = true, default-features = false}
shieldd-sdk-proto = {workspace = true, default-features = false}
serde = {workspace = true, features = ["derive"]}
tracing = {workspace = true}

[dev-dependencies]
tokio = {workspace = true, features = ["macros", "rt"]}
