[package]
name = "shieldd-sdk-compact-block"
authors = {workspace = true}
repository = {workspace = true}
description = "Compact block component implementation for Shieldd"
version = {workspace = true}
license = {workspace = true}
edition = {workspace = true}

[features]
component = [
    "cnidarium-component",
    "cnidarium",
    "shieldd-sdk-proto/cnidarium",
    "tonic",
    "tokio-stream",
    "tokio",
    "shieldd-sdk-fee/component",
    "shieldd-sdk-governance/component",
]
# proving-keys = ["shieldd-sdk-proof-params/proving-keys"]
default = ["std", "component"]
std = ["ark-ff/std"]
docsrs = []

[dependencies]
anyhow = {workspace = true}
ark-ff = {workspace = true, default-features = false}
async-trait = {workspace = true}
blake2b_simd = {workspace = true}
bytes = {workspace = true}
cnidarium = {workspace = true, optional = true, default-features = true}
cnidarium-component = {workspace = true, optional = true, default-features = true}
decaf377-rdsa = {workspace = true}
futures = {workspace = true}
im = {workspace = true}
metrics = {workspace = true}
shieldd-sdk-compliance = {workspace = true, default-features = false}
shieldd-sdk-fee = {workspace = true, default-features = false}
shieldd-sdk-governance = {workspace = true, default-features = false}
shieldd-sdk-ibc = {workspace = true, default-features = false}
shieldd-sdk-proof-params = {workspace = true, default-features = false}
shieldd-sdk-proto = {workspace = true, default-features = false}
shieldd-sdk-sct = {workspace = true, default-features = false}
shieldd-sdk-shielded-pool = {workspace = true, default-features = false}
shieldd-sdk-tct = {workspace = true, default-features = true}
rand = {workspace = true}
rand_core = {workspace = true, features = ["getrandom"]}
serde = {workspace = true, features = ["derive"]}
tendermint = {workspace = true}
tokio = {workspace = true, optional = true}
tokio-stream = {workspace = true, optional = true}
tonic = {workspace = true, optional = true}
tracing = {workspace = true}
