[package]
name = "shieldd-sdk-txhash"
authors = {workspace = true}
repository = {workspace = true}
description = "Produce Shieldd tx effecting data and authorization hashes"
version = {workspace = true}
license = {workspace = true}
edition = {workspace = true}

[dependencies]
anyhow = {workspace = true}
blake2b_simd = {workspace = true}
hex = {workspace = true}
shieldd-sdk-proto = {workspace = true, default-features = false}
shieldd-sdk-tct = {workspace = true, default-features = true}
serde = {workspace = true}
getrandom = {workspace = true}
