/-! Canonical wiring transcript expected from the Go `transfer` Define path. -/

namespace Shieldd.GnarkFormal.TransferWiringTranscript

def lines : List String :=
  ["schema shieldd.gnark.wiring.v1",
   "circuit transfer",
   "shape n_in=2 n_out=2",
   "0001 shared.bind claimed.balance_commitment=balance_commitment shared.ak=auth.ak shared.asset_id=spend0.note.asset_id sender.div_gen=sender.div_gen sender.transmission=sender.transmission",
   "0002 select.point cond=is_regulated if_true=asset.leaf.ring_pk if_false=unregulated.ring_pk out=effective.ring_pk",
   "0003 select.point cond=is_regulated if_true=asset.leaf.dk_pub if_false=unregulated.dk_pub out=effective.dk_pub",
   "0004 decaf.compress_to_field in=sender.div_gen out=sender.div_gen_fq",
   "0005 decaf.compress_to_field in=sender.transmission out=sender.transmission_fq",
   "0006 decaf.diversified_transmission_key nk=auth.nk ak=shared.ak div_gen=sender.div_gen ivk_reduced=auth.ivk_reduced ivk_quotient_a=auth.ivk_quotient_a out=sender.transmission.computed",
   "0007 decaf.assert_equivalent_if lhs=sender.transmission.computed rhs=sender.transmission cond=1",
   "0008 gadget.asset_registry_imt asset_id=shared.asset_id is_regulated=is_regulated leaf=asset.leaf path=asset.path position=asset.position root=asset_anchor",
   "0009 gadget.compliance_leaf div_gen_fq=sender.div_gen_fq transmission_fq=sender.transmission_fq asset_id=sender.asset_id slot_id=sender.slot_id slot_derivation=sender.slot_derivation d=sender.d out=sender.leaf_commitment",
   "0010 gadget.compliance_path leaf=sender.leaf_commitment path=sender.path position=sender.position out=sender.compliance_root",
   "0011 assert.eq_if lhs=sender.compliance_root rhs=compliance_anchor cond=is_regulated",
   "0012 decaf.ack ring_pk=effective.ring_pk d=sender.d out=sender.ack",
   "0013 spend.begin spend0",
   "0014 assert.boolean var=spend0.is_dummy",
   "0015 decaf.compress_to_field in=spend0.note.div_gen out=spend0.note.div_gen_fq",
   "0016 assert.eq lhs=spend0.note.transmission_key_s rhs=sender.transmission_fq",
   "0017 gadget.note_commitment blinding=spend0.note.blinding amount=spend0.note.amount asset_id=spend0.note.asset_id div_gen_fq=spend0.note.div_gen_fq transmission_key_s=sender.transmission_fq clue_key=spend0.note.clue_key out=spend0.note.commitment.computed",
   "0018 assert.eq_if lhs=spend0.note.commitment.computed rhs=spend0.state_proof.commitment cond=spend0.is_not_dummy",
   "0019 gadget.nullifier nk=auth.nk commitment=spend0.state_proof.commitment position=spend0.state_proof.position out=spend0.nullifier.real",
   "0020 gadget.state_commitment_path commitment=spend0.state_proof.commitment position=spend0.state_proof.position path=spend0.state_proof.path out=spend0.anchor.computed",
   "0021 gadget.synthetic_dummy_nullifier seed=spend0.dummy_nullifier_seed randomizer=spend0.auth_randomizer slot=spend0 out=spend0.nullifier.synthetic",
   "0022 dummy.mux is_dummy=spend0.is_dummy real=spend0.nullifier.real synthetic=spend0.nullifier.synthetic out=spend0.nullifier",
   "0023 assert.eq_if lhs=spend0.anchor.computed rhs=anchor cond=spend0.is_not_dummy",
   "0024 decaf.randomized_verification_key ak=shared.ak randomizer=spend0.auth_randomizer out=spend0.rk.computed",
   "0025 decaf.randomized_verification_key.dummy spend_auth_key=spend0.dummy_spend_auth_key randomizer=spend0.auth_randomizer out=spend0.rk.dummy",
   "0026 decaf.assert_equivalent_if lhs=spend0.rk.computed rhs=spend0.rk.claimed cond=spend0.is_not_dummy",
   "0027 decaf.assert_equivalent_if lhs=spend0.rk.dummy rhs=spend0.rk.claimed cond=spend0.is_dummy",
   "0028 assert.eq_if lhs=spend0.note.amount rhs=0 cond=spend0.is_dummy",
   "0029 assert.eq lhs=spend0.note.asset_id rhs=shared.asset_id",
   "0030 assert.eq lhs=sender.asset_id rhs=spend0.note.asset_id",
   "0031 decaf.assert_equivalent_if lhs=sender.div_gen rhs=spend0.note.div_gen cond=1",
   "0032 decaf.assert_equivalent_if lhs=sender.transmission rhs=spend0.note.transmission cond=1",
   "0033 decaf.compress_to_field in=spend0.rk.claimed out=spend0.rk.compressed",
   "0034 spend.collect spend0 amount->input_amounts nullifier->statement.nullifiers_and_rks rk_compressed->statement.nullifiers_and_rks",
   "0035 spend.begin spend1",
   "0036 assert.boolean var=spend1.is_dummy",
   "0037 decaf.compress_to_field in=spend1.note.div_gen out=spend1.note.div_gen_fq",
   "0038 assert.eq lhs=spend1.note.transmission_key_s rhs=sender.transmission_fq",
   "0039 gadget.note_commitment blinding=spend1.note.blinding amount=spend1.note.amount asset_id=spend1.note.asset_id div_gen_fq=spend1.note.div_gen_fq transmission_key_s=sender.transmission_fq clue_key=spend1.note.clue_key out=spend1.note.commitment.computed",
   "0040 assert.eq_if lhs=spend1.note.commitment.computed rhs=spend1.state_proof.commitment cond=spend1.is_not_dummy",
   "0041 gadget.nullifier nk=auth.nk commitment=spend1.state_proof.commitment position=spend1.state_proof.position out=spend1.nullifier.real",
   "0042 gadget.state_commitment_path commitment=spend1.state_proof.commitment position=spend1.state_proof.position path=spend1.state_proof.path out=spend1.anchor.computed",
   "0043 gadget.synthetic_dummy_nullifier seed=spend1.dummy_nullifier_seed randomizer=spend1.auth_randomizer slot=spend1 out=spend1.nullifier.synthetic",
   "0044 dummy.mux is_dummy=spend1.is_dummy real=spend1.nullifier.real synthetic=spend1.nullifier.synthetic out=spend1.nullifier",
   "0045 assert.eq_if lhs=spend1.anchor.computed rhs=anchor cond=spend1.is_not_dummy",
   "0046 decaf.randomized_verification_key ak=shared.ak randomizer=spend1.auth_randomizer out=spend1.rk.computed",
   "0047 decaf.randomized_verification_key.dummy spend_auth_key=spend1.dummy_spend_auth_key randomizer=spend1.auth_randomizer out=spend1.rk.dummy",
   "0048 decaf.assert_equivalent_if lhs=spend1.rk.computed rhs=spend1.rk.claimed cond=spend1.is_not_dummy",
   "0049 decaf.assert_equivalent_if lhs=spend1.rk.dummy rhs=spend1.rk.claimed cond=spend1.is_dummy",
   "0050 assert.eq_if lhs=spend1.note.amount rhs=0 cond=spend1.is_dummy",
   "0051 assert.eq lhs=spend1.note.asset_id rhs=shared.asset_id",
   "0052 assert.eq lhs=sender.asset_id rhs=spend1.note.asset_id",
   "0053 decaf.assert_equivalent_if lhs=sender.div_gen rhs=spend1.note.div_gen cond=1",
   "0054 decaf.assert_equivalent_if lhs=sender.transmission rhs=spend1.note.transmission cond=1",
   "0055 decaf.compress_to_field in=spend1.rk.claimed out=spend1.rk.compressed",
   "0056 spend.collect spend1 amount->input_amounts nullifier->statement.nullifiers_and_rks rk_compressed->statement.nullifiers_and_rks",
   "0057 output.begin output0",
   "0058 assert.eq lhs=output0.is_receiver rhs=1",
   "0059 gadget.is_zero in=output0.note.amount out=output0.is_dummy",
   "0060 decaf.compress_to_field in=output0.note.div_gen out=output0.note.div_gen_fq",
   "0061 decaf.compress_to_field in=output0.note.transmission out=output0.note.transmission_fq",
   "0062 assert.eq lhs=output0.note.transmission_key_s rhs=output0.note.transmission_fq",
   "0063 gadget.note_commitment blinding=output0.note.blinding amount=output0.note.amount asset_id=output0.note.asset_id div_gen_fq=output0.note.div_gen_fq transmission_key_s=output0.note.transmission_fq clue_key=output0.note.clue_key out=output0.note.commitment.computed",
   "0064 assert.eq lhs=output0.note.commitment.computed rhs=output0.note_commitment",
   "0065 assert.eq lhs=output0.note.asset_id rhs=shared.asset_id",
   "0066 assert.eq lhs=output0.recipient.asset_id rhs=output0.note.asset_id",
   "0067 decaf.assert_equivalent_if lhs=output0.recipient.div_gen rhs=output0.note.div_gen cond=1",
   "0068 decaf.assert_equivalent_if lhs=output0.recipient.transmission rhs=output0.note.transmission cond=1",
   "0069 gadget.compliance_leaf div_gen_fq=output0.note.div_gen_fq transmission_fq=output0.note.transmission_fq asset_id=output0.recipient.asset_id slot_id=output0.recipient.slot_id slot_derivation=output0.recipient.slot_derivation d=output0.recipient.d out=output0.recipient.leaf_commitment",
   "0070 gadget.compliance_path leaf=output0.recipient.leaf_commitment path=output0.recipient.path position=output0.recipient.position out=output0.recipient.compliance_root",
   "0071 assert.eq_if lhs=output0.recipient.compliance_root rhs=compliance_anchor cond=is_regulated",
   "0072 assert.eq lhs=output0.is_dummy rhs=0",
   "0073 decaf.ack ring_pk=effective.ring_pk d=output0.recipient.d out=receiver.ack",
   "0074 output.collect output0 amount->output_amounts commitment->statement.output_commitments ack->receiver_ack",
   "0075 output.begin output1",
   "0076 assert.eq lhs=output1.is_receiver rhs=0",
   "0077 gadget.is_zero in=output1.note.amount out=output1.is_dummy",
   "0078 decaf.compress_to_field in=output1.note.div_gen out=output1.note.div_gen_fq",
   "0079 decaf.compress_to_field in=output1.note.transmission out=output1.note.transmission_fq",
   "0080 assert.eq lhs=output1.note.transmission_key_s rhs=output1.note.transmission_fq",
   "0081 gadget.note_commitment blinding=output1.note.blinding amount=output1.note.amount asset_id=output1.note.asset_id div_gen_fq=output1.note.div_gen_fq transmission_key_s=output1.note.transmission_fq clue_key=output1.note.clue_key out=output1.note.commitment.computed",
   "0082 assert.eq lhs=output1.note.commitment.computed rhs=output1.note_commitment",
   "0083 assert.eq lhs=output1.note.asset_id rhs=shared.asset_id",
   "0084 assert.eq lhs=output1.recipient.asset_id rhs=output1.note.asset_id",
   "0085 decaf.assert_equivalent_if lhs=output1.recipient.div_gen rhs=output1.note.div_gen cond=1",
   "0086 decaf.assert_equivalent_if lhs=output1.recipient.transmission rhs=output1.note.transmission cond=1",
   "0087 gadget.compliance_leaf div_gen_fq=output1.note.div_gen_fq transmission_fq=output1.note.transmission_fq asset_id=output1.recipient.asset_id slot_id=output1.recipient.slot_id slot_derivation=output1.recipient.slot_derivation d=output1.recipient.d out=output1.recipient.leaf_commitment",
   "0088 gadget.compliance_path leaf=output1.recipient.leaf_commitment path=output1.recipient.path position=output1.recipient.position out=output1.recipient.compliance_root",
   "0089 assert.eq_if lhs=output1.recipient.compliance_root rhs=compliance_anchor cond=is_regulated",
   "0090 assert.eq lhs=output1.recipient.asset_id rhs=sender.asset_id",
   "0091 assert.eq lhs=output1.recipient.d rhs=sender.d",
   "0092 decaf.assert_equivalent_if lhs=output1.recipient.div_gen rhs=sender.div_gen cond=1",
   "0093 decaf.assert_equivalent_if lhs=output1.recipient.transmission rhs=sender.transmission cond=1",
   "0094 output.collect output1 amount->output_amounts commitment->statement.output_commitments",
   "0095 compliance.begin tiers=sender_core,sender_ext,output_core,output_ext",
   "0096 threshold.flag amount=receiver.amount threshold=asset.leaf.threshold out=is_flagged",
   "0097 decaf.compress_to_field in=compliance.sender_core.epk out=compliance.sender_core.epk_fq",
   "0098 decaf.compress_to_field in=compliance.sender_ext.epk out=compliance.sender_ext.epk_fq",
   "0099 decaf.compress_to_field in=compliance.output_core.epk out=compliance.output_core.epk_fq",
   "0100 decaf.compress_to_field in=compliance.output_ext.epk out=compliance.output_ext.epk_fq",
   "0101 gadget.transfer_salt label=salt0 nonce_root=compliance.transfer_nonce_root out=salt0",
   "0102 gadget.transfer_salt label=salt1 nonce_root=compliance.transfer_nonce_root out=salt1",
   "0103 gadget.transfer_salt label=salt2 nonce_root=compliance.transfer_nonce_root out=salt2",
   "0104 gadget.transfer_salt label=salt3 nonce_root=compliance.transfer_nonce_root out=salt3",
   "0105 gadget.transfer_salt label=salt4 nonce_root=compliance.transfer_nonce_root out=salt4",
   "0106 decaf.shared_secret tier=sender_core esk=compliance.sender_r_core ack=sender.ack dk_pub=effective.dk_pub flag=is_flagged epk=compliance.sender_core.epk out=sender_core.shared",
   "0107 decaf.shared_secret tier=sender_ext esk=compliance.sender_r_ext ack=sender.ack dk_pub=effective.dk_pub flag=is_flagged epk=compliance.sender_ext.epk out=sender_ext.shared",
   "0108 decaf.shared_secret tier=output_core esk=compliance.output_r_core ack=receiver.ack dk_pub=effective.dk_pub flag=is_flagged epk=compliance.output_core.epk out=output_core.shared",
   "0109 decaf.shared_secret tier=output_ext esk=compliance.output_r_ext ack=receiver.ack dk_pub=effective.dk_pub flag=is_flagged epk=compliance.output_ext.epk out=output_ext.shared",
   "0110 gadget.poseidon_encryption.detection regulated=is_regulated flag=is_flagged ss=sender_core.ss_detection epk_fq=compliance.sender_core.epk_fq salt=salt0 asset_id=shared.asset_id sender_slot=sender.slot_id receiver_slot=receiver.slot_id out=compliance.detection_ciphertext",
   "0111 gadget.poseidon_encryption.amount tier=sender_core regulated=is_regulated ss=sender_core.shared c2=compliance.sender_core.c2 amount=receiver.amount out=compliance.sender_core.ciphertext",
   "0112 gadget.poseidon_encryption.address tier=sender_ext regulated=is_regulated ss=sender_ext.shared c2=compliance.sender_ext.c2 div_gen_fq=receiver.div_gen_fq transmission_fq=receiver.transmission_fq out=compliance.sender_ext.ciphertext",
   "0113 gadget.poseidon_encryption.amount tier=output_core regulated=is_regulated ss=output_core.shared c2=compliance.output_core.c2 amount=receiver.amount out=compliance.output_core.ciphertext",
   "0114 gadget.poseidon_encryption.address tier=output_ext regulated=is_regulated ss=output_ext.shared c2=compliance.output_ext.c2 div_gen_fq=sender.div_gen_fq transmission_fq=sender.transmission_fq out=compliance.output_ext.ciphertext",
   "0115 decaf.assert_equivalent lhs=compliance.sender_core.epk rhs=compliance.sender_core.proof.enc_cmt",
   "0116 decaf.assert_equivalent lhs=compliance.sender_ext.epk rhs=compliance.sender_ext.proof.enc_cmt",
   "0117 decaf.assert_equivalent lhs=compliance.output_core.epk rhs=compliance.output_core.proof.enc_cmt",
   "0118 decaf.assert_equivalent lhs=compliance.output_ext.epk rhs=compliance.output_ext.proof.enc_cmt",
   "0119 decaf.assert_equivalent lhs=sender.ack rhs=compliance.sender_core.proof.derived_pk",
   "0120 decaf.assert_equivalent lhs=sender.ack rhs=compliance.sender_ext.proof.derived_pk",
   "0121 decaf.assert_equivalent lhs=receiver.ack rhs=compliance.output_core.proof.derived_pk",
   "0122 decaf.assert_equivalent lhs=receiver.ack rhs=compliance.output_ext.proof.derived_pk",
   "0123 gadget.metadata_hash tier=sender_core out=sender_core.metadata_hash",
   "0124 gadget.metadata_hash tier=sender_ext out=sender_ext.metadata_hash",
   "0125 gadget.metadata_hash tier=output_core out=output_core.metadata_hash",
   "0126 gadget.metadata_hash tier=output_ext out=output_ext.metadata_hash",
   "0127 gadget.dleq tier=sender_core r=compliance.sender_r_core derived_pk=compliance.sender_core.proof.derived_pk shared_point=compliance.sender_core.proof.shared_point enc_cmt=compliance.sender_core.proof.enc_cmt metadata=sender_core.metadata_hash challenge=compliance.sender_core.proof.challenge response=compliance.sender_core.proof.response",
   "0128 gadget.dleq tier=sender_ext r=compliance.sender_r_ext derived_pk=compliance.sender_ext.proof.derived_pk shared_point=compliance.sender_ext.proof.shared_point enc_cmt=compliance.sender_ext.proof.enc_cmt metadata=sender_ext.metadata_hash challenge=compliance.sender_ext.proof.challenge response=compliance.sender_ext.proof.response",
   "0129 gadget.dleq tier=output_core r=compliance.output_r_core derived_pk=compliance.output_core.proof.derived_pk shared_point=compliance.output_core.proof.shared_point enc_cmt=compliance.output_core.proof.enc_cmt metadata=output_core.metadata_hash challenge=compliance.output_core.proof.challenge response=compliance.output_core.proof.response",
   "0130 gadget.dleq tier=output_ext r=compliance.output_r_ext derived_pk=compliance.output_ext.proof.derived_pk shared_point=compliance.output_ext.proof.shared_point enc_cmt=compliance.output_ext.proof.enc_cmt metadata=output_ext.metadata_hash challenge=compliance.output_ext.proof.challenge response=compliance.output_ext.proof.response",
   "0131 compliance.collect detection_ciphertext->statement tier_ciphertexts->statement dleq_proofs->statement",
   "0132 decaf.net_balance_commitment inputs=input_amounts outputs=output_amounts asset_id=shared.asset_id blinding=action_balance_blinding out=balance_commitment.computed",
   "0133 decaf.assert_equivalent lhs=balance_commitment.computed rhs=claimed.balance_commitment",
   "0134 decaf.compress_to_field in=balance_commitment.computed out=balance_commitment.fq",
   "0135 statement.assemble shape=transfer2x2 fields=transfer_statement_fields",
   "0136 decaf.compress_to_field in=sender_core.proof.derived_pk out=sender_core.proof.derived_pk_fq",
   "0137 decaf.compress_to_field in=sender_core.proof.enc_cmt out=sender_core.proof.enc_cmt_fq",
   "0138 decaf.compress_to_field in=sender_core.proof.shared_point out=sender_core.proof.shared_point_fq",
   "0139 decaf.compress_to_field in=sender_ext.proof.derived_pk out=sender_ext.proof.derived_pk_fq",
   "0140 decaf.compress_to_field in=sender_ext.proof.enc_cmt out=sender_ext.proof.enc_cmt_fq",
   "0141 decaf.compress_to_field in=sender_ext.proof.shared_point out=sender_ext.proof.shared_point_fq",
   "0142 decaf.compress_to_field in=output_core.proof.derived_pk out=output_core.proof.derived_pk_fq",
   "0143 decaf.compress_to_field in=output_core.proof.enc_cmt out=output_core.proof.enc_cmt_fq",
   "0144 decaf.compress_to_field in=output_core.proof.shared_point out=output_core.proof.shared_point_fq",
   "0145 decaf.compress_to_field in=output_ext.proof.derived_pk out=output_ext.proof.derived_pk_fq",
   "0146 decaf.compress_to_field in=output_ext.proof.enc_cmt out=output_ext.proof.enc_cmt_fq",
   "0147 decaf.compress_to_field in=output_ext.proof.shared_point out=output_ext.proof.shared_point_fq",
   "0148 statement.hash family=transfer fields=statement_fields out=statement_hash",
   "0149 assert.eq lhs=statement_hash rhs=claimed_statement_hash"]

def canonical : String :=
  String.intercalate "\n" lines ++ "\n"

end Shieldd.GnarkFormal.TransferWiringTranscript
