[package]
name = "shieldd-proto-compiler"
# We don't use `{ workspace = true }` attributes, because the proto-compiler tool
# is excluded from the workspace.
authors    = ["Shieldd Labs <team@shielddlabs.xyz"]
description = "The Shieldd Protobuf Compilation Helper"
edition = "2021"
license    = "MIT OR Apache-2.0"
publish = false
repository = "https://github.com/mizufinance/shieldd"
version = "0.1.0"

[dependencies]
anyhow = "1"
pbjson-build = "0.7.0"
prost-build = "0.13.3"
tonic-build = { version = "0.12.3", features = ["cleanup-markdown"] }
