[package]
name = "shieldd-sdk-num"
authors = {workspace = true}
repository = {workspace = true}
description = "Numerical data structures and implementations used by Shieldd"
version = {workspace = true}
license = {workspace = true}
edition = {workspace = true}

[features]
default = []
parallel = ["ark-ff/parallel", "decaf377/parallel"]

[dependencies]
anyhow = { workspace = true }
ark-ff = { workspace = true, default-features = false }
decaf377 = { workspace = true }
shieldd-sdk-proto = { workspace = true }
serde = { workspace = true, features = ["derive"] }

[dev-dependencies]
proptest = { workspace = true }
