/-
GENERATED by gen/gen_note_reshape2x1_compress_adapters.py — do not edit by hand.
-/
import ShielddGnarkFormal.Deployed.Contracts.NoteReshape2x1.CompressAdapterSeg48Base

set_option maxRecDepth 1000000
set_option maxHeartbeats 20000000
set_option linter.unusedVariables false

namespace Shieldd.GnarkFormal.Deployed.Contracts.NoteReshape2x1

open Shieldd.GnarkFormal.Extracted.DecafCompressToField

theorem seg48_rows5 (rho : Nat → Seg48.F)
    (p64 : Seg48.relationPart64 rho)
    (p65 : Seg48.relationPart65 rho)
    (p66 : Seg48.relationPart66 rho)
    (p67 : Seg48.relationPart67 rho)
    (p68 : Seg48.relationPart68 rho)
    (p69 : Seg48.relationPart69 rho)
    (p70 : Seg48.relationPart70 rho)
    (p71 : Seg48.relationPart71 rho)
    (p72 : Seg48.relationPart72 rho)
    (p73 : Seg48.relationPart73 rho)
    (p74 : Seg48.relationPart74 rho)
    (p75 : Seg48.relationPart75 rho)
    (p76 : Seg48.relationPart76 rho)
    : CompressRows5 (seg48Rho rho) := by
  unfold Seg48.relationPart64 at p64
  rcases p64 with ⟨r320, r321, r322, r323, r324⟩
  unfold Seg48.relationPart65 at p65
  rcases p65 with ⟨r325, r326, r327, r328, r329⟩
  unfold Seg48.relationPart66 at p66
  rcases p66 with ⟨r330, r331, r332, r333, r334⟩
  unfold Seg48.relationPart67 at p67
  rcases p67 with ⟨r335, r336, r337, r338, r339⟩
  unfold Seg48.relationPart68 at p68
  rcases p68 with ⟨r340, r341, r342, r343, r344⟩
  unfold Seg48.relationPart69 at p69
  rcases p69 with ⟨r345, r346, r347, r348, r349⟩
  unfold Seg48.relationPart70 at p70
  rcases p70 with ⟨r350, r351, r352, r353, r354⟩
  unfold Seg48.relationPart71 at p71
  rcases p71 with ⟨r355, r356, r357, r358, r359⟩
  unfold Seg48.relationPart72 at p72
  rcases p72 with ⟨r360, r361, r362, r363, r364⟩
  unfold Seg48.relationPart73 at p73
  rcases p73 with ⟨r365, r366, r367, r368, r369⟩
  unfold Seg48.relationPart74 at p74
  rcases p74 with ⟨r370, r371, r372, r373, r374⟩
  unfold Seg48.relationPart75 at p75
  rcases p75 with ⟨r375, r376, r377, r378, r379⟩
  unfold Seg48.relationPart76 at p76
  rcases p76 with ⟨r380, r381, r382, r383, r384⟩
  refine ⟨?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_⟩
  · unfold Seg48.relationRow321 at r321
    simpa [seg48Rho, mul_eq_zero] using r321
  · unfold Seg48.relationRow322 at r322
    simpa [seg48Rho, mul_eq_zero] using r322
  · unfold Seg48.relationRow323 at r323
    simpa [seg48Rho, mul_eq_zero] using r323
  · unfold Seg48.relationRow324 at r324
    simpa [seg48Rho, mul_eq_zero] using r324
  · unfold Seg48.relationRow325 at r325
    simpa [seg48Rho, mul_eq_zero] using r325
  · unfold Seg48.relationRow326 at r326
    simpa [seg48Rho, mul_eq_zero] using r326
  · unfold Seg48.relationRow327 at r327
    simpa [seg48Rho, mul_eq_zero] using r327
  · unfold Seg48.relationRow328 at r328
    simpa [seg48Rho, mul_eq_zero] using r328
  · unfold Seg48.relationRow329 at r329
    simpa [seg48Rho, mul_eq_zero] using r329
  · unfold Seg48.relationRow330 at r330
    simpa [seg48Rho, mul_eq_zero] using r330
  · unfold Seg48.relationRow331 at r331
    simpa [seg48Rho, mul_eq_zero] using r331
  · unfold Seg48.relationRow332 at r332
    simpa [seg48Rho, mul_eq_zero] using r332
  · unfold Seg48.relationRow333 at r333
    simpa [seg48Rho, mul_eq_zero] using r333
  · unfold Seg48.relationRow334 at r334
    simpa [seg48Rho, mul_eq_zero] using r334
  · unfold Seg48.relationRow335 at r335
    simpa [seg48Rho, mul_eq_zero] using r335
  · unfold Seg48.relationRow336 at r336
    simpa [seg48Rho, mul_eq_zero] using r336
  · unfold Seg48.relationRow337 at r337
    simpa [seg48Rho, mul_eq_zero] using r337
  · unfold Seg48.relationRow338 at r338
    simpa [seg48Rho, mul_eq_zero] using r338
  · unfold Seg48.relationRow339 at r339
    simpa [seg48Rho, mul_eq_zero] using r339
  · unfold Seg48.relationRow340 at r340
    simpa [seg48Rho, mul_eq_zero] using r340
  · unfold Seg48.relationRow341 at r341
    simpa [seg48Rho, mul_eq_zero] using r341
  · unfold Seg48.relationRow342 at r342
    simpa [seg48Rho, mul_eq_zero] using r342
  · unfold Seg48.relationRow343 at r343
    simpa [seg48Rho, mul_eq_zero] using r343
  · unfold Seg48.relationRow344 at r344
    simpa [seg48Rho, mul_eq_zero] using r344
  · unfold Seg48.relationRow345 at r345
    simpa [seg48Rho, mul_eq_zero] using r345
  · unfold Seg48.relationRow346 at r346
    simpa [seg48Rho, mul_eq_zero] using r346
  · unfold Seg48.relationRow347 at r347
    simpa [seg48Rho, mul_eq_zero] using r347
  · unfold Seg48.relationRow348 at r348
    simpa [seg48Rho, mul_eq_zero] using r348
  · unfold Seg48.relationRow349 at r349
    simpa [seg48Rho, mul_eq_zero] using r349
  · unfold Seg48.relationRow350 at r350
    simpa [seg48Rho, mul_eq_zero] using r350
  · unfold Seg48.relationRow351 at r351
    simpa [seg48Rho, mul_eq_zero] using r351
  · unfold Seg48.relationRow352 at r352
    simpa [seg48Rho, mul_eq_zero] using r352
  · unfold Seg48.relationRow353 at r353
    simpa [seg48Rho, mul_eq_zero] using r353
  · unfold Seg48.relationRow354 at r354
    simpa [seg48Rho, mul_eq_zero] using r354
  · unfold Seg48.relationRow355 at r355
    simpa [seg48Rho, mul_eq_zero] using r355
  · unfold Seg48.relationRow356 at r356
    simpa [seg48Rho, mul_eq_zero] using r356
  · unfold Seg48.relationRow357 at r357
    simpa [seg48Rho, mul_eq_zero] using r357
  · unfold Seg48.relationRow358 at r358
    simpa [seg48Rho, mul_eq_zero] using r358
  · unfold Seg48.relationRow359 at r359
    simpa [seg48Rho, mul_eq_zero] using r359
  · unfold Seg48.relationRow360 at r360
    simpa [seg48Rho, mul_eq_zero] using r360
  · unfold Seg48.relationRow361 at r361
    simpa [seg48Rho, mul_eq_zero] using r361
  · unfold Seg48.relationRow362 at r362
    simpa [seg48Rho, mul_eq_zero] using r362
  · unfold Seg48.relationRow363 at r363
    simpa [seg48Rho, mul_eq_zero] using r363
  · unfold Seg48.relationRow364 at r364
    simpa [seg48Rho, mul_eq_zero] using r364
  · unfold Seg48.relationRow365 at r365
    simpa [seg48Rho, mul_eq_zero] using r365
  · unfold Seg48.relationRow366 at r366
    simpa [seg48Rho, mul_eq_zero] using r366
  · unfold Seg48.relationRow367 at r367
    simpa [seg48Rho, mul_eq_zero] using r367
  · unfold Seg48.relationRow368 at r368
    simpa [seg48Rho, mul_eq_zero] using r368
  · unfold Seg48.relationRow369 at r369
    simpa [seg48Rho, mul_eq_zero] using r369
  · unfold Seg48.relationRow370 at r370
    simpa [seg48Rho, mul_eq_zero] using r370
  · unfold Seg48.relationRow371 at r371
    simpa [seg48Rho, mul_eq_zero] using r371
  · unfold Seg48.relationRow372 at r372
    simpa [seg48Rho, mul_eq_zero] using r372
  · unfold Seg48.relationRow373 at r373
    simpa [seg48Rho, mul_eq_zero] using r373
  · unfold Seg48.relationRow374 at r374
    simpa [seg48Rho, mul_eq_zero] using r374
  · unfold Seg48.relationRow375 at r375
    simpa [seg48Rho, mul_eq_zero] using r375
  · unfold Seg48.relationRow376 at r376
    simpa [seg48Rho, mul_eq_zero] using r376
  · unfold Seg48.relationRow377 at r377
    simpa [seg48Rho, mul_eq_zero] using r377
  · unfold Seg48.relationRow378 at r378
    simpa [seg48Rho, mul_eq_zero] using r378
  · unfold Seg48.relationRow379 at r379
    simpa [seg48Rho, mul_eq_zero] using r379
  · unfold Seg48.relationRow380 at r380
    simpa [seg48Rho, mul_eq_zero] using r380
  · unfold Seg48.relationRow381 at r381
    simpa [seg48Rho, mul_eq_zero] using r381
  · unfold Seg48.relationRow382 at r382
    simpa [seg48Rho, mul_eq_zero] using r382
  · unfold Seg48.relationRow383 at r383
    simpa [seg48Rho, mul_eq_zero] using r383
  · unfold Seg48.relationRow384 at r384
    simpa [seg48Rho, mul_eq_zero] using r384

end Shieldd.GnarkFormal.Deployed.Contracts.NoteReshape2x1
