/-
GENERATED by gen/gen_note_reshape2x1_compress_adapters.py — do not edit by hand.
-/
import ShielddGnarkFormal.Deployed.Contracts.NoteReshape2x1.CompressAdapterCommon
import ShielddGnarkFormal.Deployed.Contracts.NoteReshape2x1.Seg5
import ShielddGnarkFormal.Deployed.PrimeOrder

set_option maxRecDepth 1000000
set_option maxHeartbeats 20000000
set_option linter.unusedVariables false

namespace Shieldd.GnarkFormal.Deployed.Contracts.NoteReshape2x1

open Shieldd.GnarkFormal.Extracted.DecafCompressToField

instance seg5FactPrime : Fact (Nat.Prime Seg5.Order) :=
  ⟨Shieldd.GnarkFormal.Deployed.decaf377ScalarFieldPrime⟩

def seg5Rho (rho : Nat → Seg5.F) : Nat → Seg5.F
| 0 => 1
| 17 => rho 17
| 18 => rho 18
| i => if 210 ≤ i ∧ i ≤ 912 then rho (i - 6) else rho i

theorem seg5_hrec1 (rho : Nat → Seg5.F)
    (p56 : Seg5.relationPart56 rho) :
    recover_binary_zmod' (List.Vector.ofFn (fun i : Fin 253 => seg5Rho rho (231 + i.val))) = seg5Rho rho 230 := by
  unfold Seg5.relationPart56 at p56
  rcases p56 with ⟨r280, r281, r282, r283, r284⟩
  have hrec := recover_ofFn_eq_recBits (seg5Rho rho) 231 253
  have hacc : powSumAcc (seg5Rho rho) 0 1 231 253 = seg5Rho rho 230 := by
    unfold Seg5.relationRow281 at r281
    simpa [powSumAcc, seg5Rho] using r281
  rw [hrec]
  rw [powSumAcc_eq] at hacc
  simpa [seg5Rho] using hacc

theorem seg5_hrec2 (rho : Nat → Seg5.F)
    (p158 : Seg5.relationPart158 rho) :
    recover_binary_zmod' (List.Vector.ofFn (fun i : Fin 253 => seg5Rho rho (573 + i.val))) = seg5Rho rho 572 := by
  unfold Seg5.relationPart158 at p158
  rcases p158 with ⟨r790, r791, r792, r793, r794⟩
  have hrec := recover_ofFn_eq_recBits (seg5Rho rho) 573 253
  have hacc : powSumAcc (seg5Rho rho) 0 1 573 253 = seg5Rho rho 572 := by
    unfold Seg5.relationRow791 at r791
    simpa [powSumAcc, seg5Rho] using r791
  rw [hrec]
  rw [powSumAcc_eq] at hacc
  simpa [seg5Rho] using hacc

end Shieldd.GnarkFormal.Deployed.Contracts.NoteReshape2x1
