/-
GENERATED by gen/gen_nb_slice.py — do not edit by hand.
-/
import ShielddGnarkFormal.Deployed.Contracts.NoteReshape2x1.NbAdapterSeg46BlindDefs

set_option maxRecDepth 1000000
set_option maxHeartbeats 20000000
set_option linter.unusedVariables false

namespace Shieldd.GnarkFormal.Deployed.Contracts.NoteReshape2x1

theorem seg46Blind_rows121 (rho : Nat -> Seg46.F) (h : Seg46.relation rho) :
    Seg46.relationRow509 rho ∧ Seg46.relationRow1240 rho ∧ Seg46.relationRow1241 rho ∧ Seg46.relationRow1242 rho ∧ Seg46.relationRow1243 rho ∧ Seg46.relationRow1244 rho := by
  unfold Seg46.relation at h

  rcases h with ⟨

    _, _, _, _, _, _, p6, _, _, _,

    _, _, _, _, _, p15, _, _, _, _,

    _, _, _, _, _, _, _, _

  ⟩

  unfold Seg46.relationPart6 at p6

  rcases p6 with ⟨_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, r509, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _⟩

  unfold Seg46.relationPart15 at p15

  rcases p15 with ⟨_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, r1240, r1241, r1242, r1243, r1244, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _⟩

  exact ⟨r509, r1240, r1241, r1242, r1243, r1244⟩

theorem seg46Blind_rung121 (rho : Nat -> Seg46.F) (h : Seg46.relation rho)
    (bit : Bool) (hbitValue : rho 31776 = Bool.toZMod bit)
    (hacc : EdwardsBridge.onCurve (seg46BlindAccState rho 121)) :
    Shieldd.GnarkFormal.Deployed.NetBalance.NbFixedStepRel
      121 (Bool.toZMod bit) (seg46BlindAccState rho 121)
      (seg46BlindAccState rho 122) := by
  obtain ⟨r509, r1240, r1241, r1242, r1243, r1244⟩ := seg46Blind_rows121 rho h
  unfold Seg46.relationRow509 at r509

  unfold Seg46.relationRow1240 Seg46.relationLc628 Seg46.relationLc629 at r1240

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r1240

  unfold Seg46.relationRow1241 Seg46.relationLc630 at r1241

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r1241

  unfold Seg46.relationRow1242 Seg46.relationLc631 at r1242

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r1242

  unfold Seg46.relationRow1243 Seg46.relationLc632 at r1243

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r1243

  unfold Seg46.relationRow1244 Seg46.relationLc633 at r1244

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r1244

  have hnextx : seg46BlindDeltaX121 rho =
      seg46BlindDeltaX120 rho + rho 32509 := by
    unfold seg46BlindDeltaX121 seg46BlindDeltaX120
    rw [Shieldd.GnarkFormal.StrideRun.sumAux_succ rho 31909 5 120]

    ring

  have hnexty : seg46BlindDeltaY121 rho =
      seg46BlindDeltaY120 rho + rho 32510 := by
    unfold seg46BlindDeltaY121 seg46BlindDeltaY120
    rw [Shieldd.GnarkFormal.StrideRun.sumAux_succ rho 31910 5 120]

    ring

  change Shieldd.GnarkFormal.Deployed.NetBalance.NbFixedStepRel 121
    (Bool.toZMod bit) ⟨((4661681602708190761543544705274244814260880986867766715334030151044279151219 : Seg46.F) * rho 31655 + seg46BlindDeltaX120 rho : Seg46.F),
      ((1 : Seg46.F) + (4337336842509898676347982752646772244181661588533917621717979456142867120377 : Seg46.F) * rho 31655 + seg46BlindDeltaY120 rho : Seg46.F)⟩
    ⟨((4661681602708190761543544705274244814260880986867766715334030151044279151219 : Seg46.F) * rho 31655 + seg46BlindDeltaX121 rho : Seg46.F),
      ((1 : Seg46.F) + (4337336842509898676347982752646772244181661588533917621717979456142867120377 : Seg46.F) * rho 31655 + seg46BlindDeltaY121 rho : Seg46.F)⟩
  rw [hnextx, hnexty, ← hbitValue]
  apply Shieldd.GnarkFormal.NbFixedGenSeg46.rung121_wide (rho 31655) (rho 31776) (seg46BlindDeltaX120 rho) (seg46BlindDeltaY120 rho) (rho 32506) (rho 32507) (rho 32508) (rho 32509) (rho 32510) hacc
  · unfold seg46BlindDeltaX120 seg46BlindDeltaY120
    linear_combination r1240
  · unfold seg46BlindDeltaX120 seg46BlindDeltaY120
    linear_combination r1241
  · unfold seg46BlindDeltaX120 seg46BlindDeltaY120
    linear_combination r1242
  · unfold seg46BlindDeltaX120
    linear_combination r1243
  · unfold seg46BlindDeltaY120
    linear_combination r1244
  · linear_combination r509

theorem seg46Blind_rows122 (rho : Nat -> Seg46.F) (h : Seg46.relation rho) :
    Seg46.relationRow510 rho ∧ Seg46.relationRow1245 rho ∧ Seg46.relationRow1246 rho ∧ Seg46.relationRow1247 rho ∧ Seg46.relationRow1248 rho ∧ Seg46.relationRow1249 rho := by
  unfold Seg46.relation at h

  rcases h with ⟨

    _, _, _, _, _, _, p6, _, _, _,

    _, _, _, _, _, p15, _, _, _, _,

    _, _, _, _, _, _, _, _

  ⟩

  unfold Seg46.relationPart6 at p6

  rcases p6 with ⟨_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, r510, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _⟩

  unfold Seg46.relationPart15 at p15

  rcases p15 with ⟨_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, r1245, r1246, r1247, r1248, r1249, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _⟩

  exact ⟨r510, r1245, r1246, r1247, r1248, r1249⟩

theorem seg46Blind_rung122 (rho : Nat -> Seg46.F) (h : Seg46.relation rho)
    (bit : Bool) (hbitValue : rho 31777 = Bool.toZMod bit)
    (hacc : EdwardsBridge.onCurve (seg46BlindAccState rho 122)) :
    Shieldd.GnarkFormal.Deployed.NetBalance.NbFixedStepRel
      122 (Bool.toZMod bit) (seg46BlindAccState rho 122)
      (seg46BlindAccState rho 123) := by
  obtain ⟨r510, r1245, r1246, r1247, r1248, r1249⟩ := seg46Blind_rows122 rho h
  unfold Seg46.relationRow510 at r510

  unfold Seg46.relationRow1245 Seg46.relationLc634 Seg46.relationLc635 at r1245

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r1245

  unfold Seg46.relationRow1246 Seg46.relationLc636 at r1246

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r1246

  unfold Seg46.relationRow1247 Seg46.relationLc637 at r1247

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r1247

  unfold Seg46.relationRow1248 Seg46.relationLc638 at r1248

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r1248

  unfold Seg46.relationRow1249 Seg46.relationLc639 at r1249

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r1249

  have hnextx : seg46BlindDeltaX122 rho =
      seg46BlindDeltaX121 rho + rho 32514 := by
    unfold seg46BlindDeltaX122 seg46BlindDeltaX121
    rw [Shieldd.GnarkFormal.StrideRun.sumAux_succ rho 31909 5 121]

    ring

  have hnexty : seg46BlindDeltaY122 rho =
      seg46BlindDeltaY121 rho + rho 32515 := by
    unfold seg46BlindDeltaY122 seg46BlindDeltaY121
    rw [Shieldd.GnarkFormal.StrideRun.sumAux_succ rho 31910 5 121]

    ring

  change Shieldd.GnarkFormal.Deployed.NetBalance.NbFixedStepRel 122
    (Bool.toZMod bit) ⟨((4661681602708190761543544705274244814260880986867766715334030151044279151219 : Seg46.F) * rho 31655 + seg46BlindDeltaX121 rho : Seg46.F),
      ((1 : Seg46.F) + (4337336842509898676347982752646772244181661588533917621717979456142867120377 : Seg46.F) * rho 31655 + seg46BlindDeltaY121 rho : Seg46.F)⟩
    ⟨((4661681602708190761543544705274244814260880986867766715334030151044279151219 : Seg46.F) * rho 31655 + seg46BlindDeltaX122 rho : Seg46.F),
      ((1 : Seg46.F) + (4337336842509898676347982752646772244181661588533917621717979456142867120377 : Seg46.F) * rho 31655 + seg46BlindDeltaY122 rho : Seg46.F)⟩
  rw [hnextx, hnexty, ← hbitValue]
  apply Shieldd.GnarkFormal.NbFixedGenSeg46.rung122_wide (rho 31655) (rho 31777) (seg46BlindDeltaX121 rho) (seg46BlindDeltaY121 rho) (rho 32511) (rho 32512) (rho 32513) (rho 32514) (rho 32515) hacc
  · unfold seg46BlindDeltaX121 seg46BlindDeltaY121
    linear_combination r1245
  · unfold seg46BlindDeltaX121 seg46BlindDeltaY121
    linear_combination r1246
  · unfold seg46BlindDeltaX121 seg46BlindDeltaY121
    linear_combination r1247
  · unfold seg46BlindDeltaX121
    linear_combination r1248
  · unfold seg46BlindDeltaY121
    linear_combination r1249
  · linear_combination r510

theorem seg46Blind_rows123 (rho : Nat -> Seg46.F) (h : Seg46.relation rho) :
    Seg46.relationRow511 rho ∧ Seg46.relationRow1250 rho ∧ Seg46.relationRow1251 rho ∧ Seg46.relationRow1252 rho ∧ Seg46.relationRow1253 rho ∧ Seg46.relationRow1254 rho := by
  unfold Seg46.relation at h

  rcases h with ⟨

    _, _, _, _, _, _, p6, _, _, _,

    _, _, _, _, _, p15, _, _, _, _,

    _, _, _, _, _, _, _, _

  ⟩

  unfold Seg46.relationPart6 at p6

  rcases p6 with ⟨_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, r511, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _⟩

  unfold Seg46.relationPart15 at p15

  rcases p15 with ⟨_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, r1250, r1251, r1252, r1253, r1254, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _⟩

  exact ⟨r511, r1250, r1251, r1252, r1253, r1254⟩

theorem seg46Blind_rung123 (rho : Nat -> Seg46.F) (h : Seg46.relation rho)
    (bit : Bool) (hbitValue : rho 31778 = Bool.toZMod bit)
    (hacc : EdwardsBridge.onCurve (seg46BlindAccState rho 123)) :
    Shieldd.GnarkFormal.Deployed.NetBalance.NbFixedStepRel
      123 (Bool.toZMod bit) (seg46BlindAccState rho 123)
      (seg46BlindAccState rho 124) := by
  obtain ⟨r511, r1250, r1251, r1252, r1253, r1254⟩ := seg46Blind_rows123 rho h
  unfold Seg46.relationRow511 at r511

  unfold Seg46.relationRow1250 Seg46.relationLc640 Seg46.relationLc641 at r1250

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r1250

  unfold Seg46.relationRow1251 Seg46.relationLc642 at r1251

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r1251

  unfold Seg46.relationRow1252 Seg46.relationLc643 at r1252

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r1252

  unfold Seg46.relationRow1253 Seg46.relationLc644 at r1253

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r1253

  unfold Seg46.relationRow1254 Seg46.relationLc645 at r1254

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r1254

  have hnextx : seg46BlindDeltaX123 rho =
      seg46BlindDeltaX122 rho + rho 32519 := by
    unfold seg46BlindDeltaX123 seg46BlindDeltaX122
    rw [Shieldd.GnarkFormal.StrideRun.sumAux_succ rho 31909 5 122]

    ring

  have hnexty : seg46BlindDeltaY123 rho =
      seg46BlindDeltaY122 rho + rho 32520 := by
    unfold seg46BlindDeltaY123 seg46BlindDeltaY122
    rw [Shieldd.GnarkFormal.StrideRun.sumAux_succ rho 31910 5 122]

    ring

  change Shieldd.GnarkFormal.Deployed.NetBalance.NbFixedStepRel 123
    (Bool.toZMod bit) ⟨((4661681602708190761543544705274244814260880986867766715334030151044279151219 : Seg46.F) * rho 31655 + seg46BlindDeltaX122 rho : Seg46.F),
      ((1 : Seg46.F) + (4337336842509898676347982752646772244181661588533917621717979456142867120377 : Seg46.F) * rho 31655 + seg46BlindDeltaY122 rho : Seg46.F)⟩
    ⟨((4661681602708190761543544705274244814260880986867766715334030151044279151219 : Seg46.F) * rho 31655 + seg46BlindDeltaX123 rho : Seg46.F),
      ((1 : Seg46.F) + (4337336842509898676347982752646772244181661588533917621717979456142867120377 : Seg46.F) * rho 31655 + seg46BlindDeltaY123 rho : Seg46.F)⟩
  rw [hnextx, hnexty, ← hbitValue]
  apply Shieldd.GnarkFormal.NbFixedGenSeg46.rung123_wide (rho 31655) (rho 31778) (seg46BlindDeltaX122 rho) (seg46BlindDeltaY122 rho) (rho 32516) (rho 32517) (rho 32518) (rho 32519) (rho 32520) hacc
  · unfold seg46BlindDeltaX122 seg46BlindDeltaY122
    linear_combination r1250
  · unfold seg46BlindDeltaX122 seg46BlindDeltaY122
    linear_combination r1251
  · unfold seg46BlindDeltaX122 seg46BlindDeltaY122
    linear_combination r1252
  · unfold seg46BlindDeltaX122
    linear_combination r1253
  · unfold seg46BlindDeltaY122
    linear_combination r1254
  · linear_combination r511

theorem seg46Blind_rows124 (rho : Nat -> Seg46.F) (h : Seg46.relation rho) :
    Seg46.relationRow512 rho ∧ Seg46.relationRow1255 rho ∧ Seg46.relationRow1256 rho ∧ Seg46.relationRow1257 rho ∧ Seg46.relationRow1258 rho ∧ Seg46.relationRow1259 rho := by
  unfold Seg46.relation at h

  rcases h with ⟨

    _, _, _, _, _, _, p6, _, _, _,

    _, _, _, _, _, p15, _, _, _, _,

    _, _, _, _, _, _, _, _

  ⟩

  unfold Seg46.relationPart6 at p6

  rcases p6 with ⟨_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, r512, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _⟩

  unfold Seg46.relationPart15 at p15

  rcases p15 with ⟨_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, r1255, r1256, r1257, r1258, r1259, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _⟩

  exact ⟨r512, r1255, r1256, r1257, r1258, r1259⟩

theorem seg46Blind_rung124 (rho : Nat -> Seg46.F) (h : Seg46.relation rho)
    (bit : Bool) (hbitValue : rho 31779 = Bool.toZMod bit)
    (hacc : EdwardsBridge.onCurve (seg46BlindAccState rho 124)) :
    Shieldd.GnarkFormal.Deployed.NetBalance.NbFixedStepRel
      124 (Bool.toZMod bit) (seg46BlindAccState rho 124)
      (seg46BlindAccState rho 125) := by
  obtain ⟨r512, r1255, r1256, r1257, r1258, r1259⟩ := seg46Blind_rows124 rho h
  unfold Seg46.relationRow512 at r512

  unfold Seg46.relationRow1255 Seg46.relationLc646 Seg46.relationLc647 at r1255

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r1255

  unfold Seg46.relationRow1256 Seg46.relationLc648 at r1256

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r1256

  unfold Seg46.relationRow1257 Seg46.relationLc649 at r1257

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r1257

  unfold Seg46.relationRow1258 Seg46.relationLc650 at r1258

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r1258

  unfold Seg46.relationRow1259 Seg46.relationLc651 at r1259

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r1259

  have hnextx : seg46BlindDeltaX124 rho =
      seg46BlindDeltaX123 rho + rho 32524 := by
    unfold seg46BlindDeltaX124 seg46BlindDeltaX123
    rw [Shieldd.GnarkFormal.StrideRun.sumAux_succ rho 31909 5 123]

    ring

  have hnexty : seg46BlindDeltaY124 rho =
      seg46BlindDeltaY123 rho + rho 32525 := by
    unfold seg46BlindDeltaY124 seg46BlindDeltaY123
    rw [Shieldd.GnarkFormal.StrideRun.sumAux_succ rho 31910 5 123]

    ring

  change Shieldd.GnarkFormal.Deployed.NetBalance.NbFixedStepRel 124
    (Bool.toZMod bit) ⟨((4661681602708190761543544705274244814260880986867766715334030151044279151219 : Seg46.F) * rho 31655 + seg46BlindDeltaX123 rho : Seg46.F),
      ((1 : Seg46.F) + (4337336842509898676347982752646772244181661588533917621717979456142867120377 : Seg46.F) * rho 31655 + seg46BlindDeltaY123 rho : Seg46.F)⟩
    ⟨((4661681602708190761543544705274244814260880986867766715334030151044279151219 : Seg46.F) * rho 31655 + seg46BlindDeltaX124 rho : Seg46.F),
      ((1 : Seg46.F) + (4337336842509898676347982752646772244181661588533917621717979456142867120377 : Seg46.F) * rho 31655 + seg46BlindDeltaY124 rho : Seg46.F)⟩
  rw [hnextx, hnexty, ← hbitValue]
  apply Shieldd.GnarkFormal.NbFixedGenSeg46.rung124_wide (rho 31655) (rho 31779) (seg46BlindDeltaX123 rho) (seg46BlindDeltaY123 rho) (rho 32521) (rho 32522) (rho 32523) (rho 32524) (rho 32525) hacc
  · unfold seg46BlindDeltaX123 seg46BlindDeltaY123
    linear_combination r1255
  · unfold seg46BlindDeltaX123 seg46BlindDeltaY123
    linear_combination r1256
  · unfold seg46BlindDeltaX123 seg46BlindDeltaY123
    linear_combination r1257
  · unfold seg46BlindDeltaX123
    linear_combination r1258
  · unfold seg46BlindDeltaY123
    linear_combination r1259
  · linear_combination r512

theorem seg46Blind_rows125 (rho : Nat -> Seg46.F) (h : Seg46.relation rho) :
    Seg46.relationRow513 rho ∧ Seg46.relationRow1260 rho ∧ Seg46.relationRow1261 rho ∧ Seg46.relationRow1262 rho ∧ Seg46.relationRow1263 rho ∧ Seg46.relationRow1264 rho := by
  unfold Seg46.relation at h

  rcases h with ⟨

    _, _, _, _, _, _, p6, _, _, _,

    _, _, _, _, _, p15, _, _, _, _,

    _, _, _, _, _, _, _, _

  ⟩

  unfold Seg46.relationPart6 at p6

  rcases p6 with ⟨_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, r513, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _⟩

  unfold Seg46.relationPart15 at p15

  rcases p15 with ⟨_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, r1260, r1261, r1262, r1263, r1264, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _⟩

  exact ⟨r513, r1260, r1261, r1262, r1263, r1264⟩

theorem seg46Blind_rung125 (rho : Nat -> Seg46.F) (h : Seg46.relation rho)
    (bit : Bool) (hbitValue : rho 31780 = Bool.toZMod bit)
    (hacc : EdwardsBridge.onCurve (seg46BlindAccState rho 125)) :
    Shieldd.GnarkFormal.Deployed.NetBalance.NbFixedStepRel
      125 (Bool.toZMod bit) (seg46BlindAccState rho 125)
      (seg46BlindAccState rho 126) := by
  obtain ⟨r513, r1260, r1261, r1262, r1263, r1264⟩ := seg46Blind_rows125 rho h
  unfold Seg46.relationRow513 at r513

  unfold Seg46.relationRow1260 Seg46.relationLc652 Seg46.relationLc653 at r1260

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r1260

  unfold Seg46.relationRow1261 Seg46.relationLc654 at r1261

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r1261

  unfold Seg46.relationRow1262 Seg46.relationLc655 at r1262

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r1262

  unfold Seg46.relationRow1263 Seg46.relationLc656 at r1263

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r1263

  unfold Seg46.relationRow1264 Seg46.relationLc657 at r1264

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r1264

  have hnextx : seg46BlindDeltaX125 rho =
      seg46BlindDeltaX124 rho + rho 32529 := by
    unfold seg46BlindDeltaX125 seg46BlindDeltaX124
    rw [Shieldd.GnarkFormal.StrideRun.sumAux_succ rho 31909 5 124]

    ring

  have hnexty : seg46BlindDeltaY125 rho =
      seg46BlindDeltaY124 rho + rho 32530 := by
    unfold seg46BlindDeltaY125 seg46BlindDeltaY124
    rw [Shieldd.GnarkFormal.StrideRun.sumAux_succ rho 31910 5 124]

    ring

  change Shieldd.GnarkFormal.Deployed.NetBalance.NbFixedStepRel 125
    (Bool.toZMod bit) ⟨((4661681602708190761543544705274244814260880986867766715334030151044279151219 : Seg46.F) * rho 31655 + seg46BlindDeltaX124 rho : Seg46.F),
      ((1 : Seg46.F) + (4337336842509898676347982752646772244181661588533917621717979456142867120377 : Seg46.F) * rho 31655 + seg46BlindDeltaY124 rho : Seg46.F)⟩
    ⟨((4661681602708190761543544705274244814260880986867766715334030151044279151219 : Seg46.F) * rho 31655 + seg46BlindDeltaX125 rho : Seg46.F),
      ((1 : Seg46.F) + (4337336842509898676347982752646772244181661588533917621717979456142867120377 : Seg46.F) * rho 31655 + seg46BlindDeltaY125 rho : Seg46.F)⟩
  rw [hnextx, hnexty, ← hbitValue]
  apply Shieldd.GnarkFormal.NbFixedGenSeg46.rung125_wide (rho 31655) (rho 31780) (seg46BlindDeltaX124 rho) (seg46BlindDeltaY124 rho) (rho 32526) (rho 32527) (rho 32528) (rho 32529) (rho 32530) hacc
  · unfold seg46BlindDeltaX124 seg46BlindDeltaY124
    linear_combination r1260
  · unfold seg46BlindDeltaX124 seg46BlindDeltaY124
    linear_combination r1261
  · unfold seg46BlindDeltaX124 seg46BlindDeltaY124
    linear_combination r1262
  · unfold seg46BlindDeltaX124
    linear_combination r1263
  · unfold seg46BlindDeltaY124
    linear_combination r1264
  · linear_combination r513

theorem seg46Blind_rows126 (rho : Nat -> Seg46.F) (h : Seg46.relation rho) :
    Seg46.relationRow514 rho ∧ Seg46.relationRow1265 rho ∧ Seg46.relationRow1266 rho ∧ Seg46.relationRow1267 rho ∧ Seg46.relationRow1268 rho ∧ Seg46.relationRow1269 rho := by
  unfold Seg46.relation at h

  rcases h with ⟨

    _, _, _, _, _, _, p6, _, _, _,

    _, _, _, _, _, p15, _, _, _, _,

    _, _, _, _, _, _, _, _

  ⟩

  unfold Seg46.relationPart6 at p6

  rcases p6 with ⟨_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, r514, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _⟩

  unfold Seg46.relationPart15 at p15

  rcases p15 with ⟨_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, r1265, r1266, r1267, r1268, r1269, _, _, _, _, _, _, _, _, _, _⟩

  exact ⟨r514, r1265, r1266, r1267, r1268, r1269⟩

theorem seg46Blind_rung126 (rho : Nat -> Seg46.F) (h : Seg46.relation rho)
    (bit : Bool) (hbitValue : rho 31781 = Bool.toZMod bit)
    (hacc : EdwardsBridge.onCurve (seg46BlindAccState rho 126)) :
    Shieldd.GnarkFormal.Deployed.NetBalance.NbFixedStepRel
      126 (Bool.toZMod bit) (seg46BlindAccState rho 126)
      (seg46BlindAccState rho 127) := by
  obtain ⟨r514, r1265, r1266, r1267, r1268, r1269⟩ := seg46Blind_rows126 rho h
  unfold Seg46.relationRow514 at r514

  unfold Seg46.relationRow1265 Seg46.relationLc658 Seg46.relationLc659 at r1265

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r1265

  unfold Seg46.relationRow1266 Seg46.relationLc660 at r1266

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r1266

  unfold Seg46.relationRow1267 Seg46.relationLc661 at r1267

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r1267

  unfold Seg46.relationRow1268 Seg46.relationLc662 at r1268

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r1268

  unfold Seg46.relationRow1269 Seg46.relationLc663 at r1269

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r1269

  have hnextx : seg46BlindDeltaX126 rho =
      seg46BlindDeltaX125 rho + rho 32534 := by
    unfold seg46BlindDeltaX126 seg46BlindDeltaX125
    rw [Shieldd.GnarkFormal.StrideRun.sumAux_succ rho 31909 5 125]

    ring

  have hnexty : seg46BlindDeltaY126 rho =
      seg46BlindDeltaY125 rho + rho 32535 := by
    unfold seg46BlindDeltaY126 seg46BlindDeltaY125
    rw [Shieldd.GnarkFormal.StrideRun.sumAux_succ rho 31910 5 125]

    ring

  change Shieldd.GnarkFormal.Deployed.NetBalance.NbFixedStepRel 126
    (Bool.toZMod bit) ⟨((4661681602708190761543544705274244814260880986867766715334030151044279151219 : Seg46.F) * rho 31655 + seg46BlindDeltaX125 rho : Seg46.F),
      ((1 : Seg46.F) + (4337336842509898676347982752646772244181661588533917621717979456142867120377 : Seg46.F) * rho 31655 + seg46BlindDeltaY125 rho : Seg46.F)⟩
    ⟨((4661681602708190761543544705274244814260880986867766715334030151044279151219 : Seg46.F) * rho 31655 + seg46BlindDeltaX126 rho : Seg46.F),
      ((1 : Seg46.F) + (4337336842509898676347982752646772244181661588533917621717979456142867120377 : Seg46.F) * rho 31655 + seg46BlindDeltaY126 rho : Seg46.F)⟩
  rw [hnextx, hnexty, ← hbitValue]
  apply Shieldd.GnarkFormal.NbFixedGenSeg46.rung126_wide (rho 31655) (rho 31781) (seg46BlindDeltaX125 rho) (seg46BlindDeltaY125 rho) (rho 32531) (rho 32532) (rho 32533) (rho 32534) (rho 32535) hacc
  · unfold seg46BlindDeltaX125 seg46BlindDeltaY125
    linear_combination r1265
  · unfold seg46BlindDeltaX125 seg46BlindDeltaY125
    linear_combination r1266
  · unfold seg46BlindDeltaX125 seg46BlindDeltaY125
    linear_combination r1267
  · unfold seg46BlindDeltaX125
    linear_combination r1268
  · unfold seg46BlindDeltaY125
    linear_combination r1269
  · linear_combination r514

theorem seg46Blind_rows127 (rho : Nat -> Seg46.F) (h : Seg46.relation rho) :
    Seg46.relationRow515 rho ∧ Seg46.relationRow1270 rho ∧ Seg46.relationRow1271 rho ∧ Seg46.relationRow1272 rho ∧ Seg46.relationRow1273 rho ∧ Seg46.relationRow1274 rho := by
  unfold Seg46.relation at h

  rcases h with ⟨

    _, _, _, _, _, _, p6, _, _, _,

    _, _, _, _, _, p15, _, _, _, _,

    _, _, _, _, _, _, _, _

  ⟩

  unfold Seg46.relationPart6 at p6

  rcases p6 with ⟨_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, r515, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _⟩

  unfold Seg46.relationPart15 at p15

  rcases p15 with ⟨_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, r1270, r1271, r1272, r1273, r1274, _, _, _, _, _⟩

  exact ⟨r515, r1270, r1271, r1272, r1273, r1274⟩

theorem seg46Blind_rung127 (rho : Nat -> Seg46.F) (h : Seg46.relation rho)
    (bit : Bool) (hbitValue : rho 31782 = Bool.toZMod bit)
    (hacc : EdwardsBridge.onCurve (seg46BlindAccState rho 127)) :
    Shieldd.GnarkFormal.Deployed.NetBalance.NbFixedStepRel
      127 (Bool.toZMod bit) (seg46BlindAccState rho 127)
      (seg46BlindAccState rho 128) := by
  obtain ⟨r515, r1270, r1271, r1272, r1273, r1274⟩ := seg46Blind_rows127 rho h
  unfold Seg46.relationRow515 at r515

  unfold Seg46.relationRow1270 Seg46.relationLc664 Seg46.relationLc665 at r1270

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r1270

  unfold Seg46.relationRow1271 Seg46.relationLc666 at r1271

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r1271

  unfold Seg46.relationRow1272 Seg46.relationLc667 at r1272

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r1272

  unfold Seg46.relationRow1273 Seg46.relationLc668 at r1273

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r1273

  unfold Seg46.relationRow1274 Seg46.relationLc669 at r1274

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r1274

  have hnextx : seg46BlindDeltaX127 rho =
      seg46BlindDeltaX126 rho + rho 32539 := by
    unfold seg46BlindDeltaX127 seg46BlindDeltaX126
    rw [Shieldd.GnarkFormal.StrideRun.sumAux_succ rho 31909 5 126]

    ring

  have hnexty : seg46BlindDeltaY127 rho =
      seg46BlindDeltaY126 rho + rho 32540 := by
    unfold seg46BlindDeltaY127 seg46BlindDeltaY126
    rw [Shieldd.GnarkFormal.StrideRun.sumAux_succ rho 31910 5 126]

    ring

  change Shieldd.GnarkFormal.Deployed.NetBalance.NbFixedStepRel 127
    (Bool.toZMod bit) ⟨((4661681602708190761543544705274244814260880986867766715334030151044279151219 : Seg46.F) * rho 31655 + seg46BlindDeltaX126 rho : Seg46.F),
      ((1 : Seg46.F) + (4337336842509898676347982752646772244181661588533917621717979456142867120377 : Seg46.F) * rho 31655 + seg46BlindDeltaY126 rho : Seg46.F)⟩
    ⟨((4661681602708190761543544705274244814260880986867766715334030151044279151219 : Seg46.F) * rho 31655 + seg46BlindDeltaX127 rho : Seg46.F),
      ((1 : Seg46.F) + (4337336842509898676347982752646772244181661588533917621717979456142867120377 : Seg46.F) * rho 31655 + seg46BlindDeltaY127 rho : Seg46.F)⟩
  rw [hnextx, hnexty, ← hbitValue]
  apply Shieldd.GnarkFormal.NbFixedGenSeg46.rung127_wide (rho 31655) (rho 31782) (seg46BlindDeltaX126 rho) (seg46BlindDeltaY126 rho) (rho 32536) (rho 32537) (rho 32538) (rho 32539) (rho 32540) hacc
  · unfold seg46BlindDeltaX126 seg46BlindDeltaY126
    linear_combination r1270
  · unfold seg46BlindDeltaX126 seg46BlindDeltaY126
    linear_combination r1271
  · unfold seg46BlindDeltaX126 seg46BlindDeltaY126
    linear_combination r1272
  · unfold seg46BlindDeltaX126
    linear_combination r1273
  · unfold seg46BlindDeltaY126
    linear_combination r1274
  · linear_combination r515

theorem seg46Blind_rows128 (rho : Nat -> Seg46.F) (h : Seg46.relation rho) :
    Seg46.relationRow516 rho ∧ Seg46.relationRow1275 rho ∧ Seg46.relationRow1276 rho ∧ Seg46.relationRow1277 rho ∧ Seg46.relationRow1278 rho ∧ Seg46.relationRow1279 rho := by
  unfold Seg46.relation at h

  rcases h with ⟨

    _, _, _, _, _, _, p6, _, _, _,

    _, _, _, _, _, p15, _, _, _, _,

    _, _, _, _, _, _, _, _

  ⟩

  unfold Seg46.relationPart6 at p6

  rcases p6 with ⟨_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, r516, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _⟩

  unfold Seg46.relationPart15 at p15

  rcases p15 with ⟨_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, r1275, r1276, r1277, r1278, r1279⟩

  exact ⟨r516, r1275, r1276, r1277, r1278, r1279⟩

theorem seg46Blind_rung128 (rho : Nat -> Seg46.F) (h : Seg46.relation rho)
    (bit : Bool) (hbitValue : rho 31783 = Bool.toZMod bit)
    (hacc : EdwardsBridge.onCurve (seg46BlindAccState rho 128)) :
    Shieldd.GnarkFormal.Deployed.NetBalance.NbFixedStepRel
      128 (Bool.toZMod bit) (seg46BlindAccState rho 128)
      (seg46BlindAccState rho 129) := by
  obtain ⟨r516, r1275, r1276, r1277, r1278, r1279⟩ := seg46Blind_rows128 rho h
  unfold Seg46.relationRow516 at r516

  unfold Seg46.relationRow1275 Seg46.relationLc670 Seg46.relationLc671 at r1275

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r1275

  unfold Seg46.relationRow1276 Seg46.relationLc672 at r1276

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r1276

  unfold Seg46.relationRow1277 Seg46.relationLc673 at r1277

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r1277

  unfold Seg46.relationRow1278 Seg46.relationLc674 at r1278

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r1278

  unfold Seg46.relationRow1279 Seg46.relationLc675 at r1279

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r1279

  have hnextx : seg46BlindDeltaX128 rho =
      seg46BlindDeltaX127 rho + rho 32544 := by
    unfold seg46BlindDeltaX128 seg46BlindDeltaX127
    rw [Shieldd.GnarkFormal.StrideRun.sumAux_succ rho 31909 5 127]

    ring

  have hnexty : seg46BlindDeltaY128 rho =
      seg46BlindDeltaY127 rho + rho 32545 := by
    unfold seg46BlindDeltaY128 seg46BlindDeltaY127
    rw [Shieldd.GnarkFormal.StrideRun.sumAux_succ rho 31910 5 127]

    ring

  change Shieldd.GnarkFormal.Deployed.NetBalance.NbFixedStepRel 128
    (Bool.toZMod bit) ⟨((4661681602708190761543544705274244814260880986867766715334030151044279151219 : Seg46.F) * rho 31655 + seg46BlindDeltaX127 rho : Seg46.F),
      ((1 : Seg46.F) + (4337336842509898676347982752646772244181661588533917621717979456142867120377 : Seg46.F) * rho 31655 + seg46BlindDeltaY127 rho : Seg46.F)⟩
    ⟨((4661681602708190761543544705274244814260880986867766715334030151044279151219 : Seg46.F) * rho 31655 + seg46BlindDeltaX128 rho : Seg46.F),
      ((1 : Seg46.F) + (4337336842509898676347982752646772244181661588533917621717979456142867120377 : Seg46.F) * rho 31655 + seg46BlindDeltaY128 rho : Seg46.F)⟩
  rw [hnextx, hnexty, ← hbitValue]
  apply Shieldd.GnarkFormal.NbFixedGenSeg46.rung128_wide (rho 31655) (rho 31783) (seg46BlindDeltaX127 rho) (seg46BlindDeltaY127 rho) (rho 32541) (rho 32542) (rho 32543) (rho 32544) (rho 32545) hacc
  · unfold seg46BlindDeltaX127 seg46BlindDeltaY127
    linear_combination r1275
  · unfold seg46BlindDeltaX127 seg46BlindDeltaY127
    linear_combination r1276
  · unfold seg46BlindDeltaX127 seg46BlindDeltaY127
    linear_combination r1277
  · unfold seg46BlindDeltaX127
    linear_combination r1278
  · unfold seg46BlindDeltaY127
    linear_combination r1279
  · linear_combination r516

theorem seg46Blind_rows129 (rho : Nat -> Seg46.F) (h : Seg46.relation rho) :
    Seg46.relationRow517 rho ∧ Seg46.relationRow1280 rho ∧ Seg46.relationRow1281 rho ∧ Seg46.relationRow1282 rho ∧ Seg46.relationRow1283 rho ∧ Seg46.relationRow1284 rho := by
  unfold Seg46.relation at h

  rcases h with ⟨

    _, _, _, _, _, _, p6, _, _, _,

    _, _, _, _, _, _, p16, _, _, _,

    _, _, _, _, _, _, _, _

  ⟩

  unfold Seg46.relationPart6 at p6

  rcases p6 with ⟨_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, r517, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _⟩

  unfold Seg46.relationPart16 at p16

  rcases p16 with ⟨r1280, r1281, r1282, r1283, r1284, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _⟩

  exact ⟨r517, r1280, r1281, r1282, r1283, r1284⟩

theorem seg46Blind_rung129 (rho : Nat -> Seg46.F) (h : Seg46.relation rho)
    (bit : Bool) (hbitValue : rho 31784 = Bool.toZMod bit)
    (hacc : EdwardsBridge.onCurve (seg46BlindAccState rho 129)) :
    Shieldd.GnarkFormal.Deployed.NetBalance.NbFixedStepRel
      129 (Bool.toZMod bit) (seg46BlindAccState rho 129)
      (seg46BlindAccState rho 130) := by
  obtain ⟨r517, r1280, r1281, r1282, r1283, r1284⟩ := seg46Blind_rows129 rho h
  unfold Seg46.relationRow517 at r517

  unfold Seg46.relationRow1280 Seg46.relationLc676 Seg46.relationLc677 at r1280

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r1280

  unfold Seg46.relationRow1281 Seg46.relationLc678 at r1281

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r1281

  unfold Seg46.relationRow1282 Seg46.relationLc679 at r1282

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r1282

  unfold Seg46.relationRow1283 Seg46.relationLc680 at r1283

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r1283

  unfold Seg46.relationRow1284 Seg46.relationLc681 at r1284

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r1284

  have hnextx : seg46BlindDeltaX129 rho =
      seg46BlindDeltaX128 rho + rho 32549 := by
    unfold seg46BlindDeltaX129 seg46BlindDeltaX128
    rw [Shieldd.GnarkFormal.StrideRun.sumAux_succ rho 31909 5 128]

    ring

  have hnexty : seg46BlindDeltaY129 rho =
      seg46BlindDeltaY128 rho + rho 32550 := by
    unfold seg46BlindDeltaY129 seg46BlindDeltaY128
    rw [Shieldd.GnarkFormal.StrideRun.sumAux_succ rho 31910 5 128]

    ring

  change Shieldd.GnarkFormal.Deployed.NetBalance.NbFixedStepRel 129
    (Bool.toZMod bit) ⟨((4661681602708190761543544705274244814260880986867766715334030151044279151219 : Seg46.F) * rho 31655 + seg46BlindDeltaX128 rho : Seg46.F),
      ((1 : Seg46.F) + (4337336842509898676347982752646772244181661588533917621717979456142867120377 : Seg46.F) * rho 31655 + seg46BlindDeltaY128 rho : Seg46.F)⟩
    ⟨((4661681602708190761543544705274244814260880986867766715334030151044279151219 : Seg46.F) * rho 31655 + seg46BlindDeltaX129 rho : Seg46.F),
      ((1 : Seg46.F) + (4337336842509898676347982752646772244181661588533917621717979456142867120377 : Seg46.F) * rho 31655 + seg46BlindDeltaY129 rho : Seg46.F)⟩
  rw [hnextx, hnexty, ← hbitValue]
  apply Shieldd.GnarkFormal.NbFixedGenSeg46.rung129_wide (rho 31655) (rho 31784) (seg46BlindDeltaX128 rho) (seg46BlindDeltaY128 rho) (rho 32546) (rho 32547) (rho 32548) (rho 32549) (rho 32550) hacc
  · unfold seg46BlindDeltaX128 seg46BlindDeltaY128
    linear_combination r1280
  · unfold seg46BlindDeltaX128 seg46BlindDeltaY128
    linear_combination r1281
  · unfold seg46BlindDeltaX128 seg46BlindDeltaY128
    linear_combination r1282
  · unfold seg46BlindDeltaX128
    linear_combination r1283
  · unfold seg46BlindDeltaY128
    linear_combination r1284
  · linear_combination r517

theorem seg46Blind_rows130 (rho : Nat -> Seg46.F) (h : Seg46.relation rho) :
    Seg46.relationRow518 rho ∧ Seg46.relationRow1285 rho ∧ Seg46.relationRow1286 rho ∧ Seg46.relationRow1287 rho ∧ Seg46.relationRow1288 rho ∧ Seg46.relationRow1289 rho := by
  unfold Seg46.relation at h

  rcases h with ⟨

    _, _, _, _, _, _, p6, _, _, _,

    _, _, _, _, _, _, p16, _, _, _,

    _, _, _, _, _, _, _, _

  ⟩

  unfold Seg46.relationPart6 at p6

  rcases p6 with ⟨_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, r518, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _⟩

  unfold Seg46.relationPart16 at p16

  rcases p16 with ⟨_, _, _, _, _, r1285, r1286, r1287, r1288, r1289, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _⟩

  exact ⟨r518, r1285, r1286, r1287, r1288, r1289⟩

theorem seg46Blind_rung130 (rho : Nat -> Seg46.F) (h : Seg46.relation rho)
    (bit : Bool) (hbitValue : rho 31785 = Bool.toZMod bit)
    (hacc : EdwardsBridge.onCurve (seg46BlindAccState rho 130)) :
    Shieldd.GnarkFormal.Deployed.NetBalance.NbFixedStepRel
      130 (Bool.toZMod bit) (seg46BlindAccState rho 130)
      (seg46BlindAccState rho 131) := by
  obtain ⟨r518, r1285, r1286, r1287, r1288, r1289⟩ := seg46Blind_rows130 rho h
  unfold Seg46.relationRow518 at r518

  unfold Seg46.relationRow1285 Seg46.relationLc682 Seg46.relationLc683 at r1285

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r1285

  unfold Seg46.relationRow1286 Seg46.relationLc684 at r1286

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r1286

  unfold Seg46.relationRow1287 Seg46.relationLc685 at r1287

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r1287

  unfold Seg46.relationRow1288 Seg46.relationLc686 at r1288

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r1288

  unfold Seg46.relationRow1289 Seg46.relationLc687 at r1289

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r1289

  have hnextx : seg46BlindDeltaX130 rho =
      seg46BlindDeltaX129 rho + rho 32554 := by
    unfold seg46BlindDeltaX130 seg46BlindDeltaX129
    rw [Shieldd.GnarkFormal.StrideRun.sumAux_succ rho 31909 5 129]

    ring

  have hnexty : seg46BlindDeltaY130 rho =
      seg46BlindDeltaY129 rho + rho 32555 := by
    unfold seg46BlindDeltaY130 seg46BlindDeltaY129
    rw [Shieldd.GnarkFormal.StrideRun.sumAux_succ rho 31910 5 129]

    ring

  change Shieldd.GnarkFormal.Deployed.NetBalance.NbFixedStepRel 130
    (Bool.toZMod bit) ⟨((4661681602708190761543544705274244814260880986867766715334030151044279151219 : Seg46.F) * rho 31655 + seg46BlindDeltaX129 rho : Seg46.F),
      ((1 : Seg46.F) + (4337336842509898676347982752646772244181661588533917621717979456142867120377 : Seg46.F) * rho 31655 + seg46BlindDeltaY129 rho : Seg46.F)⟩
    ⟨((4661681602708190761543544705274244814260880986867766715334030151044279151219 : Seg46.F) * rho 31655 + seg46BlindDeltaX130 rho : Seg46.F),
      ((1 : Seg46.F) + (4337336842509898676347982752646772244181661588533917621717979456142867120377 : Seg46.F) * rho 31655 + seg46BlindDeltaY130 rho : Seg46.F)⟩
  rw [hnextx, hnexty, ← hbitValue]
  apply Shieldd.GnarkFormal.NbFixedGenSeg46.rung130_wide (rho 31655) (rho 31785) (seg46BlindDeltaX129 rho) (seg46BlindDeltaY129 rho) (rho 32551) (rho 32552) (rho 32553) (rho 32554) (rho 32555) hacc
  · unfold seg46BlindDeltaX129 seg46BlindDeltaY129
    linear_combination r1285
  · unfold seg46BlindDeltaX129 seg46BlindDeltaY129
    linear_combination r1286
  · unfold seg46BlindDeltaX129 seg46BlindDeltaY129
    linear_combination r1287
  · unfold seg46BlindDeltaX129
    linear_combination r1288
  · unfold seg46BlindDeltaY129
    linear_combination r1289
  · linear_combination r518

theorem seg46Blind_hstep_c12 (rho : Nat -> Seg46.F)
    (h : Seg46.relation rho) (bits : List.Vector Bool 251)
    (hbitAt : ∀ i, i < 251 → rho (31655 + i) = Bool.toZMod bits[i]!) :
    ∀ i, 121 ≤ i → i < 131 →
      EdwardsBridge.onCurve (seg46BlindAccState rho i) →
      Shieldd.GnarkFormal.Deployed.NetBalance.NbFixedStepRel i
        (Bool.toZMod bits[i]!) (seg46BlindAccState rho i)
        (seg46BlindAccState rho (i + 1)) := by
  intro i hlo hhi hacc
  interval_cases i
  · exact seg46Blind_rung121 rho h bits[121]! (hbitAt 121 (by omega)) hacc
  · exact seg46Blind_rung122 rho h bits[122]! (hbitAt 122 (by omega)) hacc
  · exact seg46Blind_rung123 rho h bits[123]! (hbitAt 123 (by omega)) hacc
  · exact seg46Blind_rung124 rho h bits[124]! (hbitAt 124 (by omega)) hacc
  · exact seg46Blind_rung125 rho h bits[125]! (hbitAt 125 (by omega)) hacc
  · exact seg46Blind_rung126 rho h bits[126]! (hbitAt 126 (by omega)) hacc
  · exact seg46Blind_rung127 rho h bits[127]! (hbitAt 127 (by omega)) hacc
  · exact seg46Blind_rung128 rho h bits[128]! (hbitAt 128 (by omega)) hacc
  · exact seg46Blind_rung129 rho h bits[129]! (hbitAt 129 (by omega)) hacc
  · exact seg46Blind_rung130 rho h bits[130]! (hbitAt 130 (by omega)) hacc

end Shieldd.GnarkFormal.Deployed.Contracts.NoteReshape2x1
