/-
GENERATED by gen/gen_nb_slice.py — do not edit by hand.
-/
import ShielddGnarkFormal.Deployed.Contracts.NoteReshape2x1.NbAdapterSeg46Base
import ShielddGnarkFormal.Deployed.Contracts.NoteReshape2x1.CompressAdapterCommon
import ShielddGnarkFormal.RvkToBinary

set_option maxRecDepth 1000000
set_option maxHeartbeats 20000000
set_option linter.unusedVariables false

namespace Shieldd.GnarkFormal.Deployed.Contracts.NoteReshape2x1

theorem seg46BlindBits_toBinary (rho : Nat -> Seg46.F) (h : Seg46.relation rho) :
    GatesDef.to_binary (rho 5) 251 (seg46BlindBits rho) := by
  unfold Seg46.relation at h

  rcases h with ⟨

    _, _, _, _, p4, p5, p6, p7, _, _,

    _, _, _, _, _, _, _, _, _, _,

    _, _, _, _, _, _, _, _

  ⟩

  unfold Seg46.relationPart4 at p4

  rcases p4 with ⟨_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, r388, r389, r390, r391, r392, r393, r394, r395, r396, r397, r398, r399⟩

  unfold Seg46.relationPart5 at p5

  rcases p5 with ⟨r400, r401, r402, r403, r404, r405, r406, r407, r408, r409, r410, r411, r412, r413, r414, r415, r416, r417, r418, r419, r420, r421, r422, r423, r424, r425, r426, r427, r428, r429, r430, r431, r432, r433, r434, r435, r436, r437, r438, r439, r440, r441, r442, r443, r444, r445, r446, r447, r448, r449, r450, r451, r452, r453, r454, r455, r456, r457, r458, r459, r460, r461, r462, r463, r464, r465, r466, r467, r468, r469, r470, r471, r472, r473, r474, r475, r476, r477, r478, r479⟩

  unfold Seg46.relationPart6 at p6

  rcases p6 with ⟨r480, r481, r482, r483, r484, r485, r486, r487, r488, r489, r490, r491, r492, r493, r494, r495, r496, r497, r498, r499, r500, r501, r502, r503, r504, r505, r506, r507, r508, r509, r510, r511, r512, r513, r514, r515, r516, r517, r518, r519, r520, r521, r522, r523, r524, r525, r526, r527, r528, r529, r530, r531, r532, r533, r534, r535, r536, r537, r538, r539, r540, r541, r542, r543, r544, r545, r546, r547, r548, r549, r550, r551, r552, r553, r554, r555, r556, r557, r558, r559⟩

  unfold Seg46.relationPart7 at p7

  rcases p7 with ⟨r560, r561, r562, r563, r564, r565, r566, r567, r568, r569, r570, r571, r572, r573, r574, r575, r576, r577, r578, r579, r580, r581, r582, r583, r584, r585, r586, r587, r588, r589, r590, r591, r592, r593, r594, r595, r596, r597, r598, r599, r600, r601, r602, r603, r604, r605, r606, r607, r608, r609, r610, r611, r612, r613, r614, r615, r616, r617, r618, r619, r620, r621, r622, r623, r624, r625, r626, r627, r628, r629, r630, r631, r632, r633, r634, r635, r636, r637, r638, r639⟩

  unfold Seg46.relationRow388 at r388

  unfold Seg46.relationRow389 at r389

  unfold Seg46.relationRow390 at r390

  unfold Seg46.relationRow391 at r391

  unfold Seg46.relationRow392 at r392

  unfold Seg46.relationRow393 at r393

  unfold Seg46.relationRow394 at r394

  unfold Seg46.relationRow395 at r395

  unfold Seg46.relationRow396 at r396

  unfold Seg46.relationRow397 at r397

  unfold Seg46.relationRow398 at r398

  unfold Seg46.relationRow399 at r399

  unfold Seg46.relationRow400 at r400

  unfold Seg46.relationRow401 at r401

  unfold Seg46.relationRow402 at r402

  unfold Seg46.relationRow403 at r403

  unfold Seg46.relationRow404 at r404

  unfold Seg46.relationRow405 at r405

  unfold Seg46.relationRow406 at r406

  unfold Seg46.relationRow407 at r407

  unfold Seg46.relationRow408 at r408

  unfold Seg46.relationRow409 at r409

  unfold Seg46.relationRow410 at r410

  unfold Seg46.relationRow411 at r411

  unfold Seg46.relationRow412 at r412

  unfold Seg46.relationRow413 at r413

  unfold Seg46.relationRow414 at r414

  unfold Seg46.relationRow415 at r415

  unfold Seg46.relationRow416 at r416

  unfold Seg46.relationRow417 at r417

  unfold Seg46.relationRow418 at r418

  unfold Seg46.relationRow419 at r419

  unfold Seg46.relationRow420 at r420

  unfold Seg46.relationRow421 at r421

  unfold Seg46.relationRow422 at r422

  unfold Seg46.relationRow423 at r423

  unfold Seg46.relationRow424 at r424

  unfold Seg46.relationRow425 at r425

  unfold Seg46.relationRow426 at r426

  unfold Seg46.relationRow427 at r427

  unfold Seg46.relationRow428 at r428

  unfold Seg46.relationRow429 at r429

  unfold Seg46.relationRow430 at r430

  unfold Seg46.relationRow431 at r431

  unfold Seg46.relationRow432 at r432

  unfold Seg46.relationRow433 at r433

  unfold Seg46.relationRow434 at r434

  unfold Seg46.relationRow435 at r435

  unfold Seg46.relationRow436 at r436

  unfold Seg46.relationRow437 at r437

  unfold Seg46.relationRow438 at r438

  unfold Seg46.relationRow439 at r439

  unfold Seg46.relationRow440 at r440

  unfold Seg46.relationRow441 at r441

  unfold Seg46.relationRow442 at r442

  unfold Seg46.relationRow443 at r443

  unfold Seg46.relationRow444 at r444

  unfold Seg46.relationRow445 at r445

  unfold Seg46.relationRow446 at r446

  unfold Seg46.relationRow447 at r447

  unfold Seg46.relationRow448 at r448

  unfold Seg46.relationRow449 at r449

  unfold Seg46.relationRow450 at r450

  unfold Seg46.relationRow451 at r451

  unfold Seg46.relationRow452 at r452

  unfold Seg46.relationRow453 at r453

  unfold Seg46.relationRow454 at r454

  unfold Seg46.relationRow455 at r455

  unfold Seg46.relationRow456 at r456

  unfold Seg46.relationRow457 at r457

  unfold Seg46.relationRow458 at r458

  unfold Seg46.relationRow459 at r459

  unfold Seg46.relationRow460 at r460

  unfold Seg46.relationRow461 at r461

  unfold Seg46.relationRow462 at r462

  unfold Seg46.relationRow463 at r463

  unfold Seg46.relationRow464 at r464

  unfold Seg46.relationRow465 at r465

  unfold Seg46.relationRow466 at r466

  unfold Seg46.relationRow467 at r467

  unfold Seg46.relationRow468 at r468

  unfold Seg46.relationRow469 at r469

  unfold Seg46.relationRow470 at r470

  unfold Seg46.relationRow471 at r471

  unfold Seg46.relationRow472 at r472

  unfold Seg46.relationRow473 at r473

  unfold Seg46.relationRow474 at r474

  unfold Seg46.relationRow475 at r475

  unfold Seg46.relationRow476 at r476

  unfold Seg46.relationRow477 at r477

  unfold Seg46.relationRow478 at r478

  unfold Seg46.relationRow479 at r479

  unfold Seg46.relationRow480 at r480

  unfold Seg46.relationRow481 at r481

  unfold Seg46.relationRow482 at r482

  unfold Seg46.relationRow483 at r483

  unfold Seg46.relationRow484 at r484

  unfold Seg46.relationRow485 at r485

  unfold Seg46.relationRow486 at r486

  unfold Seg46.relationRow487 at r487

  unfold Seg46.relationRow488 at r488

  unfold Seg46.relationRow489 at r489

  unfold Seg46.relationRow490 at r490

  unfold Seg46.relationRow491 at r491

  unfold Seg46.relationRow492 at r492

  unfold Seg46.relationRow493 at r493

  unfold Seg46.relationRow494 at r494

  unfold Seg46.relationRow495 at r495

  unfold Seg46.relationRow496 at r496

  unfold Seg46.relationRow497 at r497

  unfold Seg46.relationRow498 at r498

  unfold Seg46.relationRow499 at r499

  unfold Seg46.relationRow500 at r500

  unfold Seg46.relationRow501 at r501

  unfold Seg46.relationRow502 at r502

  unfold Seg46.relationRow503 at r503

  unfold Seg46.relationRow504 at r504

  unfold Seg46.relationRow505 at r505

  unfold Seg46.relationRow506 at r506

  unfold Seg46.relationRow507 at r507

  unfold Seg46.relationRow508 at r508

  unfold Seg46.relationRow509 at r509

  unfold Seg46.relationRow510 at r510

  unfold Seg46.relationRow511 at r511

  unfold Seg46.relationRow512 at r512

  unfold Seg46.relationRow513 at r513

  unfold Seg46.relationRow514 at r514

  unfold Seg46.relationRow515 at r515

  unfold Seg46.relationRow516 at r516

  unfold Seg46.relationRow517 at r517

  unfold Seg46.relationRow518 at r518

  unfold Seg46.relationRow519 at r519

  unfold Seg46.relationRow520 at r520

  unfold Seg46.relationRow521 at r521

  unfold Seg46.relationRow522 at r522

  unfold Seg46.relationRow523 at r523

  unfold Seg46.relationRow524 at r524

  unfold Seg46.relationRow525 at r525

  unfold Seg46.relationRow526 at r526

  unfold Seg46.relationRow527 at r527

  unfold Seg46.relationRow528 at r528

  unfold Seg46.relationRow529 at r529

  unfold Seg46.relationRow530 at r530

  unfold Seg46.relationRow531 at r531

  unfold Seg46.relationRow532 at r532

  unfold Seg46.relationRow533 at r533

  unfold Seg46.relationRow534 at r534

  unfold Seg46.relationRow535 at r535

  unfold Seg46.relationRow536 at r536

  unfold Seg46.relationRow537 at r537

  unfold Seg46.relationRow538 at r538

  unfold Seg46.relationRow539 at r539

  unfold Seg46.relationRow540 at r540

  unfold Seg46.relationRow541 at r541

  unfold Seg46.relationRow542 at r542

  unfold Seg46.relationRow543 at r543

  unfold Seg46.relationRow544 at r544

  unfold Seg46.relationRow545 at r545

  unfold Seg46.relationRow546 at r546

  unfold Seg46.relationRow547 at r547

  unfold Seg46.relationRow548 at r548

  unfold Seg46.relationRow549 at r549

  unfold Seg46.relationRow550 at r550

  unfold Seg46.relationRow551 at r551

  unfold Seg46.relationRow552 at r552

  unfold Seg46.relationRow553 at r553

  unfold Seg46.relationRow554 at r554

  unfold Seg46.relationRow555 at r555

  unfold Seg46.relationRow556 at r556

  unfold Seg46.relationRow557 at r557

  unfold Seg46.relationRow558 at r558

  unfold Seg46.relationRow559 at r559

  unfold Seg46.relationRow560 at r560

  unfold Seg46.relationRow561 at r561

  unfold Seg46.relationRow562 at r562

  unfold Seg46.relationRow563 at r563

  unfold Seg46.relationRow564 at r564

  unfold Seg46.relationRow565 at r565

  unfold Seg46.relationRow566 at r566

  unfold Seg46.relationRow567 at r567

  unfold Seg46.relationRow568 at r568

  unfold Seg46.relationRow569 at r569

  unfold Seg46.relationRow570 at r570

  unfold Seg46.relationRow571 at r571

  unfold Seg46.relationRow572 at r572

  unfold Seg46.relationRow573 at r573

  unfold Seg46.relationRow574 at r574

  unfold Seg46.relationRow575 at r575

  unfold Seg46.relationRow576 at r576

  unfold Seg46.relationRow577 at r577

  unfold Seg46.relationRow578 at r578

  unfold Seg46.relationRow579 at r579

  unfold Seg46.relationRow580 at r580

  unfold Seg46.relationRow581 at r581

  unfold Seg46.relationRow582 at r582

  unfold Seg46.relationRow583 at r583

  unfold Seg46.relationRow584 at r584

  unfold Seg46.relationRow585 at r585

  unfold Seg46.relationRow586 at r586

  unfold Seg46.relationRow587 at r587

  unfold Seg46.relationRow588 at r588

  unfold Seg46.relationRow589 at r589

  unfold Seg46.relationRow590 at r590

  unfold Seg46.relationRow591 at r591

  unfold Seg46.relationRow592 at r592

  unfold Seg46.relationRow593 at r593

  unfold Seg46.relationRow594 at r594

  unfold Seg46.relationRow595 at r595

  unfold Seg46.relationRow596 at r596

  unfold Seg46.relationRow597 at r597

  unfold Seg46.relationRow598 at r598

  unfold Seg46.relationRow599 at r599

  unfold Seg46.relationRow600 at r600

  unfold Seg46.relationRow601 at r601

  unfold Seg46.relationRow602 at r602

  unfold Seg46.relationRow603 at r603

  unfold Seg46.relationRow604 at r604

  unfold Seg46.relationRow605 at r605

  unfold Seg46.relationRow606 at r606

  unfold Seg46.relationRow607 at r607

  unfold Seg46.relationRow608 at r608

  unfold Seg46.relationRow609 at r609

  unfold Seg46.relationRow610 at r610

  unfold Seg46.relationRow611 at r611

  unfold Seg46.relationRow612 at r612

  unfold Seg46.relationRow613 at r613

  unfold Seg46.relationRow614 at r614

  unfold Seg46.relationRow615 at r615

  unfold Seg46.relationRow616 at r616

  unfold Seg46.relationRow617 at r617

  unfold Seg46.relationRow618 at r618

  unfold Seg46.relationRow619 at r619

  unfold Seg46.relationRow620 at r620

  unfold Seg46.relationRow621 at r621

  unfold Seg46.relationRow622 at r622

  unfold Seg46.relationRow623 at r623

  unfold Seg46.relationRow624 at r624

  unfold Seg46.relationRow625 at r625

  unfold Seg46.relationRow626 at r626

  unfold Seg46.relationRow627 at r627

  unfold Seg46.relationRow628 at r628

  unfold Seg46.relationRow629 at r629

  unfold Seg46.relationRow630 at r630

  unfold Seg46.relationRow631 at r631

  unfold Seg46.relationRow632 at r632

  unfold Seg46.relationRow633 at r633

  unfold Seg46.relationRow634 at r634

  unfold Seg46.relationRow635 at r635

  unfold Seg46.relationRow636 at r636

  unfold Seg46.relationRow637 at r637

  unfold Seg46.relationRow638 at r638

  have hrecover := recover_ofFn_eq_recBits rho 31655 251

  have hacc : powSumAcc rho 0 1 31655 251 = rho 5 := by

    unfold Seg46.relationRow639 Seg46.relationLc3 Seg46.relationLc3Part0 Seg46.relationLc3Part1 Seg46.relationLc3Part2 Seg46.relationLc3Part3 Seg46.relationLc3Part4 Seg46.relationLc3Part5 Seg46.relationLc3Part6 Seg46.relationLc3Part7 at r639

    simp only [powSumAcc]

    linear_combination r639

  have hrec : recover_binary_zmod' (seg46BlindBits rho) = rho 5 := by

    simp only [seg46BlindBits]

    rw [hrecover]

    rw [powSumAcc_eq] at hacc

    simpa using hacc

  apply Shieldd.GnarkFormal.RvkToBinary.to_binary_of_deployed (rho 5) (seg46BlindBits rho)
  · intro i hi
    have key := seg46BlindBits_get rho i hi
    have hgoal : rho (31655 + i) * (1 - rho (31655 + i)) = 0 := by
      interval_cases i
      · linear_combination r388
      · linear_combination r389
      · linear_combination r390
      · linear_combination r391
      · linear_combination r392
      · linear_combination r393
      · linear_combination r394
      · linear_combination r395
      · linear_combination r396
      · linear_combination r397
      · linear_combination r398
      · linear_combination r399
      · linear_combination r400
      · linear_combination r401
      · linear_combination r402
      · linear_combination r403
      · linear_combination r404
      · linear_combination r405
      · linear_combination r406
      · linear_combination r407
      · linear_combination r408
      · linear_combination r409
      · linear_combination r410
      · linear_combination r411
      · linear_combination r412
      · linear_combination r413
      · linear_combination r414
      · linear_combination r415
      · linear_combination r416
      · linear_combination r417
      · linear_combination r418
      · linear_combination r419
      · linear_combination r420
      · linear_combination r421
      · linear_combination r422
      · linear_combination r423
      · linear_combination r424
      · linear_combination r425
      · linear_combination r426
      · linear_combination r427
      · linear_combination r428
      · linear_combination r429
      · linear_combination r430
      · linear_combination r431
      · linear_combination r432
      · linear_combination r433
      · linear_combination r434
      · linear_combination r435
      · linear_combination r436
      · linear_combination r437
      · linear_combination r438
      · linear_combination r439
      · linear_combination r440
      · linear_combination r441
      · linear_combination r442
      · linear_combination r443
      · linear_combination r444
      · linear_combination r445
      · linear_combination r446
      · linear_combination r447
      · linear_combination r448
      · linear_combination r449
      · linear_combination r450
      · linear_combination r451
      · linear_combination r452
      · linear_combination r453
      · linear_combination r454
      · linear_combination r455
      · linear_combination r456
      · linear_combination r457
      · linear_combination r458
      · linear_combination r459
      · linear_combination r460
      · linear_combination r461
      · linear_combination r462
      · linear_combination r463
      · linear_combination r464
      · linear_combination r465
      · linear_combination r466
      · linear_combination r467
      · linear_combination r468
      · linear_combination r469
      · linear_combination r470
      · linear_combination r471
      · linear_combination r472
      · linear_combination r473
      · linear_combination r474
      · linear_combination r475
      · linear_combination r476
      · linear_combination r477
      · linear_combination r478
      · linear_combination r479
      · linear_combination r480
      · linear_combination r481
      · linear_combination r482
      · linear_combination r483
      · linear_combination r484
      · linear_combination r485
      · linear_combination r486
      · linear_combination r487
      · linear_combination r488
      · linear_combination r489
      · linear_combination r490
      · linear_combination r491
      · linear_combination r492
      · linear_combination r493
      · linear_combination r494
      · linear_combination r495
      · linear_combination r496
      · linear_combination r497
      · linear_combination r498
      · linear_combination r499
      · linear_combination r500
      · linear_combination r501
      · linear_combination r502
      · linear_combination r503
      · linear_combination r504
      · linear_combination r505
      · linear_combination r506
      · linear_combination r507
      · linear_combination r508
      · linear_combination r509
      · linear_combination r510
      · linear_combination r511
      · linear_combination r512
      · linear_combination r513
      · linear_combination r514
      · linear_combination r515
      · linear_combination r516
      · linear_combination r517
      · linear_combination r518
      · linear_combination r519
      · linear_combination r520
      · linear_combination r521
      · linear_combination r522
      · linear_combination r523
      · linear_combination r524
      · linear_combination r525
      · linear_combination r526
      · linear_combination r527
      · linear_combination r528
      · linear_combination r529
      · linear_combination r530
      · linear_combination r531
      · linear_combination r532
      · linear_combination r533
      · linear_combination r534
      · linear_combination r535
      · linear_combination r536
      · linear_combination r537
      · linear_combination r538
      · linear_combination r539
      · linear_combination r540
      · linear_combination r541
      · linear_combination r542
      · linear_combination r543
      · linear_combination r544
      · linear_combination r545
      · linear_combination r546
      · linear_combination r547
      · linear_combination r548
      · linear_combination r549
      · linear_combination r550
      · linear_combination r551
      · linear_combination r552
      · linear_combination r553
      · linear_combination r554
      · linear_combination r555
      · linear_combination r556
      · linear_combination r557
      · linear_combination r558
      · linear_combination r559
      · linear_combination r560
      · linear_combination r561
      · linear_combination r562
      · linear_combination r563
      · linear_combination r564
      · linear_combination r565
      · linear_combination r566
      · linear_combination r567
      · linear_combination r568
      · linear_combination r569
      · linear_combination r570
      · linear_combination r571
      · linear_combination r572
      · linear_combination r573
      · linear_combination r574
      · linear_combination r575
      · linear_combination r576
      · linear_combination r577
      · linear_combination r578
      · linear_combination r579
      · linear_combination r580
      · linear_combination r581
      · linear_combination r582
      · linear_combination r583
      · linear_combination r584
      · linear_combination r585
      · linear_combination r586
      · linear_combination r587
      · linear_combination r588
      · linear_combination r589
      · linear_combination r590
      · linear_combination r591
      · linear_combination r592
      · linear_combination r593
      · linear_combination r594
      · linear_combination r595
      · linear_combination r596
      · linear_combination r597
      · linear_combination r598
      · linear_combination r599
      · linear_combination r600
      · linear_combination r601
      · linear_combination r602
      · linear_combination r603
      · linear_combination r604
      · linear_combination r605
      · linear_combination r606
      · linear_combination r607
      · linear_combination r608
      · linear_combination r609
      · linear_combination r610
      · linear_combination r611
      · linear_combination r612
      · linear_combination r613
      · linear_combination r614
      · linear_combination r615
      · linear_combination r616
      · linear_combination r617
      · linear_combination r618
      · linear_combination r619
      · linear_combination r620
      · linear_combination r621
      · linear_combination r622
      · linear_combination r623
      · linear_combination r624
      · linear_combination r625
      · linear_combination r626
      · linear_combination r627
      · linear_combination r628
      · linear_combination r629
      · linear_combination r630
      · linear_combination r631
      · linear_combination r632
      · linear_combination r633
      · linear_combination r634
      · linear_combination r635
      · linear_combination r636
      · linear_combination r637
      · linear_combination r638
    have key' : (seg46BlindBits rho)[i] = rho (31655 + i) := by
      rw [← getElem!_pos (seg46BlindBits rho) i (by simpa using hi)]
      exact key
    exact key' ▸ hgoal
  · exact hrec

end Shieldd.GnarkFormal.Deployed.Contracts.NoteReshape2x1
