/-
GENERATED by gen/gen_note_reshape_nb_semantics.py — do not edit by hand.
-/
import ShielddGnarkFormal.Deployed.Templates.Semantics.TDecafConservationNetBalanceCommitment_9602c510696ca316ef532feb1eaa5610fa2276fdeb6f49a351c8c7c242b359e6NbIn0Bits
import ShielddGnarkFormal.Deployed.Templates.Semantics.TDecafConservationNetBalanceCommitment_9602c510696ca316ef532feb1eaa5610fa2276fdeb6f49a351c8c7c242b359e6NbIn1Bits
import ShielddGnarkFormal.Deployed.Templates.Semantics.TDecafConservationNetBalanceCommitment_9602c510696ca316ef532feb1eaa5610fa2276fdeb6f49a351c8c7c242b359e6NbOut0Bits
import ShielddGnarkFormal.Deployed.Templates.Semantics.TDecafConservationNetBalanceCommitment_9602c510696ca316ef532feb1eaa5610fa2276fdeb6f49a351c8c7c242b359e6NbBlindBits
import ShielddGnarkFormal.Deployed.Templates.Semantics.TDecafConservationNetBalanceCommitment_9602c510696ca316ef532feb1eaa5610fa2276fdeb6f49a351c8c7c242b359e6NbBlind
import ShielddGnarkFormal.Deployed.Templates.Semantics.TDecafConservationNetBalanceCommitment_9602c510696ca316ef532feb1eaa5610fa2276fdeb6f49a351c8c7c242b359e6NbConserv
import ShielddGnarkFormal.Decaf377Assumptions
import ShielddGnarkFormal.ChoiceFreeBinary
import ShielddGnarkFormal.Deployed.NetBalance.ChoiceFreeLadder
import ShielddGnarkFormal.ScalarMulBridge
import ShielddGnarkFormal.ChoiceFreeZMod

set_option maxRecDepth 1000000
set_option maxHeartbeats 20000000
set_option linter.unusedVariables false

namespace Shieldd.GnarkFormal.Deployed.Templates.Semantics.TDecafConservationNetBalanceCommitment_9602c510696ca316ef532feb1eaa5610fa2276fdeb6f49a351c8c7c242b359e6

open scoped Shieldd.GnarkFormal.ChoiceFreeZMod
open Shieldd.GnarkFormal.Deployed.Templates.Semantics.TDecafConservationNetBalanceCommitment_9602c510696ca316ef532feb1eaa5610fa2276fdeb6f49a351c8c7c242b359e6.NbSupport
open Shieldd.GnarkFormal.NetBalanceCommitmentBridge
open Shieldd.GnarkFormal.ScalarMulBridge

abbrev Order : Nat := Shieldd.GnarkFormal.Deployed.Templates.Semantics.TDecafConservationNetBalanceCommitment_9602c510696ca316ef532feb1eaa5610fa2276fdeb6f49a351c8c7c242b359e6.NbSupport.Order
abbrev F := Shieldd.GnarkFormal.Deployed.Templates.Semantics.TDecafConservationNetBalanceCommitment_9602c510696ca316ef532feb1eaa5610fa2276fdeb6f49a351c8c7c242b359e6.NbSupport.F

def relation (rho : Nat -> F) : Prop :=
  Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafConservationNetBalanceCommitment_9602c510696ca316ef532feb1eaa5610fa2276fdeb6f49a351c8c7c242b359e6.relation rho

def spec (rho : Nat -> F) : Prop :=
  (rho 129).val < 2 ^ 128 ∧
  (rho 258).val < 2 ^ 128 ∧
  (rho 387).val < 2 ^ 128 ∧
  (rho 129 + rho 258) = (rho 387) ∧
  Shieldd.GnarkFormal.Decaf377Assumptions.Point.mk (nbBlindAccState rho 251).x (nbBlindAccState rho 251).y =
    Shieldd.GnarkFormal.Decaf377Assumptions.scalarMulLE 251
      Shieldd.GnarkFormal.Decaf377Assumptions.valueBlindingGenerator (rho 639)

theorem sound (rho : Nat -> F) (h : relation rho) : spec rho := by
  have hIn0Bin := nbIn0Bits_toBinary rho h
  have hIn1Bin := nbIn1Bits_toBinary rho h
  have hOut0Bin := nbOut0Bits_toBinary rho h
  have hBlindBin := nbBlindBits_toBinary rho h
  obtain ⟨blindBool, hBlindEq, hBlindValue⟩ :=
    Shieldd.GnarkFormal.ChoiceFreeBinary.exists_bool_vector_of_to_binary
      pow251_lt_order hBlindBin
  have hBlindScalar := nbBlind_scalarMul rho h blindBool hBlindEq hBlindValue
  have hcons := nb_conservation rho h
  refine ⟨Shieldd.GnarkFormal.ChoiceFreeBinary.range_of_to_binary Shieldd.GnarkFormal.ScalarMulBridge.pow128_lt_order hIn0Bin, Shieldd.GnarkFormal.ChoiceFreeBinary.range_of_to_binary Shieldd.GnarkFormal.ScalarMulBridge.pow128_lt_order hIn1Bin, Shieldd.GnarkFormal.ChoiceFreeBinary.range_of_to_binary Shieldd.GnarkFormal.ScalarMulBridge.pow128_lt_order hOut0Bin, hcons, ?_⟩
  have hbg : toA Shieldd.GnarkFormal.Deployed.NetBalanceChoiceFree.blindGen =
      Shieldd.GnarkFormal.Decaf377Assumptions.valueBlindingGenerator := rfl
  change toA (nbBlindAccState rho 251) =
    Shieldd.GnarkFormal.Decaf377Assumptions.scalarMulLE 251
      Shieldd.GnarkFormal.Decaf377Assumptions.valueBlindingGenerator
      (rho 639)
  rw [← hbg]
  exact hBlindScalar

end Shieldd.GnarkFormal.Deployed.Templates.Semantics.TDecafConservationNetBalanceCommitment_9602c510696ca316ef532feb1eaa5610fa2276fdeb6f49a351c8c7c242b359e6
