/-
GENERATED by gen/gen_note_reshape_dummy_rvk_semantics.py — do not edit by hand.
-/
import ShielddGnarkFormal.ChoiceFreeZMod
import ShielddGnarkFormal.Deployed.Templates.Semantics.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5DummyRvkRandomizerDefs

set_option maxRecDepth 1000000
set_option maxHeartbeats 20000000
set_option linter.unusedVariables false

namespace Shieldd.GnarkFormal.Deployed.Templates.Semantics.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.DummyRvkSupport

attribute [-instance] ZMod.instField
open scoped Shieldd.GnarkFormal.ChoiceFreeZMod

theorem dummyRvkRandomizer_rows121 (rho : Nat -> F) (h : Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relation rho) :
    Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationRow1926 rho ∧ Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationRow2657 rho ∧ Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationRow2658 rho ∧ Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationRow2659 rho ∧ Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationRow2660 rho ∧ Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationRow2661 rho := by
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relation at h

  rcases h with ⟨

    _, _, _, _, _, _, _, _, _, _,

    _, _, _, _, _, _, _, _, _, _,

    _, _, _, _, p24, _, _, _, _, _,

    _, _, _, p33, _, _, _, _, _, _,

    _, _, _, _, _, _

  ⟩

  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationPart24 at p24

  rcases p24 with ⟨_, _, _, _, _, _, r1926, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _⟩

  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationPart33 at p33

  rcases p33 with ⟨_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, r2657, r2658, r2659, r2660, r2661, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _⟩

  exact ⟨r1926, r2657, r2658, r2659, r2660, r2661⟩

theorem dummyRvkRandomizer_rung121 (rho : Nat -> F) (h : Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relation rho)
    (bit : Bool) (hbitValue : rho 1927 = Bool.toZMod bit)
    (hacc : EdwardsBridge.onCurve (dummyRvkRandomizerAccState rho 121)) :
    Shieldd.GnarkFormal.RvkFixedBaseLadderChoiceFree.FixedStepRel
      121 (Bool.toZMod bit) (dummyRvkRandomizerAccState rho 121)
      (dummyRvkRandomizerAccState rho 122) := by
  obtain ⟨r1926, r2657, r2658, r2659, r2660, r2661⟩ := dummyRvkRandomizer_rows121 rho h
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationRow1926 at r1926

  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationRow2657 Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationLc2131 Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationLc2132 at r2657

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r2657

  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationRow2658 Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationLc2133 at r2658

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r2658

  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationRow2659 Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationLc2134 at r2659

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r2659

  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationRow2660 Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationLc2135 at r2660

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r2660

  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationRow2661 Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationLc2136 at r2661

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r2661

  have hnextx : dummyRvkRandomizerDeltaX121 rho =
      dummyRvkRandomizerDeltaX120 rho + rho 2661 := by
    unfold dummyRvkRandomizerDeltaX121 dummyRvkRandomizerDeltaX120
    rw [Shieldd.GnarkFormal.StrideRun.sumAux_succ rho 2061 5 120]

    ring

  have hnexty : dummyRvkRandomizerDeltaY121 rho =
      dummyRvkRandomizerDeltaY120 rho + rho 2662 := by
    unfold dummyRvkRandomizerDeltaY121 dummyRvkRandomizerDeltaY120
    rw [Shieldd.GnarkFormal.StrideRun.sumAux_succ rho 2062 5 120]

    ring

  change Shieldd.GnarkFormal.RvkFixedBaseLadderChoiceFree.FixedStepRel 121
    (Bool.toZMod bit) ⟨((4959445789346820725352484487855828915252512307947624787834978378872129235627 : F) * rho 1806 + dummyRvkRandomizerDeltaX120 rho : F),
      ((1 : F) + (6060471950081851567114691557659790004756535011754163002297540472747064943287 : F) * rho 1806 + dummyRvkRandomizerDeltaY120 rho : F)⟩
    ⟨((4959445789346820725352484487855828915252512307947624787834978378872129235627 : F) * rho 1806 + dummyRvkRandomizerDeltaX121 rho : F),
      ((1 : F) + (6060471950081851567114691557659790004756535011754163002297540472747064943287 : F) * rho 1806 + dummyRvkRandomizerDeltaY121 rho : F)⟩
  rw [hnextx, hnexty, ← hbitValue]
  apply Shieldd.GnarkFormal.RvkFixedGenInst0ChoiceFree.rung121_wide (rho 1806) (rho 1927) (dummyRvkRandomizerDeltaX120 rho) (dummyRvkRandomizerDeltaY120 rho) (rho 2658) (rho 2659) (rho 2660) (rho 2661) (rho 2662) hacc
  · unfold dummyRvkRandomizerDeltaX120 dummyRvkRandomizerDeltaY120
    linear_combination r2657
  · unfold dummyRvkRandomizerDeltaX120 dummyRvkRandomizerDeltaY120
    linear_combination r2658
  · unfold dummyRvkRandomizerDeltaX120 dummyRvkRandomizerDeltaY120
    linear_combination r2659
  · unfold dummyRvkRandomizerDeltaX120
    linear_combination r2660
  · unfold dummyRvkRandomizerDeltaY120
    linear_combination r2661
  · linear_combination r1926

theorem dummyRvkRandomizer_rows122 (rho : Nat -> F) (h : Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relation rho) :
    Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationRow1927 rho ∧ Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationRow2662 rho ∧ Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationRow2663 rho ∧ Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationRow2664 rho ∧ Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationRow2665 rho ∧ Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationRow2666 rho := by
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relation at h

  rcases h with ⟨

    _, _, _, _, _, _, _, _, _, _,

    _, _, _, _, _, _, _, _, _, _,

    _, _, _, _, p24, _, _, _, _, _,

    _, _, _, p33, _, _, _, _, _, _,

    _, _, _, _, _, _

  ⟩

  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationPart24 at p24

  rcases p24 with ⟨_, _, _, _, _, _, _, r1927, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _⟩

  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationPart33 at p33

  rcases p33 with ⟨_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, r2662, r2663, r2664, r2665, r2666, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _⟩

  exact ⟨r1927, r2662, r2663, r2664, r2665, r2666⟩

theorem dummyRvkRandomizer_rung122 (rho : Nat -> F) (h : Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relation rho)
    (bit : Bool) (hbitValue : rho 1928 = Bool.toZMod bit)
    (hacc : EdwardsBridge.onCurve (dummyRvkRandomizerAccState rho 122)) :
    Shieldd.GnarkFormal.RvkFixedBaseLadderChoiceFree.FixedStepRel
      122 (Bool.toZMod bit) (dummyRvkRandomizerAccState rho 122)
      (dummyRvkRandomizerAccState rho 123) := by
  obtain ⟨r1927, r2662, r2663, r2664, r2665, r2666⟩ := dummyRvkRandomizer_rows122 rho h
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationRow1927 at r1927

  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationRow2662 Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationLc2137 Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationLc2138 at r2662

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r2662

  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationRow2663 Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationLc2139 at r2663

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r2663

  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationRow2664 Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationLc2140 at r2664

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r2664

  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationRow2665 Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationLc2141 at r2665

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r2665

  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationRow2666 Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationLc2142 at r2666

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r2666

  have hnextx : dummyRvkRandomizerDeltaX122 rho =
      dummyRvkRandomizerDeltaX121 rho + rho 2666 := by
    unfold dummyRvkRandomizerDeltaX122 dummyRvkRandomizerDeltaX121
    rw [Shieldd.GnarkFormal.StrideRun.sumAux_succ rho 2061 5 121]

    ring

  have hnexty : dummyRvkRandomizerDeltaY122 rho =
      dummyRvkRandomizerDeltaY121 rho + rho 2667 := by
    unfold dummyRvkRandomizerDeltaY122 dummyRvkRandomizerDeltaY121
    rw [Shieldd.GnarkFormal.StrideRun.sumAux_succ rho 2062 5 121]

    ring

  change Shieldd.GnarkFormal.RvkFixedBaseLadderChoiceFree.FixedStepRel 122
    (Bool.toZMod bit) ⟨((4959445789346820725352484487855828915252512307947624787834978378872129235627 : F) * rho 1806 + dummyRvkRandomizerDeltaX121 rho : F),
      ((1 : F) + (6060471950081851567114691557659790004756535011754163002297540472747064943287 : F) * rho 1806 + dummyRvkRandomizerDeltaY121 rho : F)⟩
    ⟨((4959445789346820725352484487855828915252512307947624787834978378872129235627 : F) * rho 1806 + dummyRvkRandomizerDeltaX122 rho : F),
      ((1 : F) + (6060471950081851567114691557659790004756535011754163002297540472747064943287 : F) * rho 1806 + dummyRvkRandomizerDeltaY122 rho : F)⟩
  rw [hnextx, hnexty, ← hbitValue]
  apply Shieldd.GnarkFormal.RvkFixedGenInst0ChoiceFree.rung122_wide (rho 1806) (rho 1928) (dummyRvkRandomizerDeltaX121 rho) (dummyRvkRandomizerDeltaY121 rho) (rho 2663) (rho 2664) (rho 2665) (rho 2666) (rho 2667) hacc
  · unfold dummyRvkRandomizerDeltaX121 dummyRvkRandomizerDeltaY121
    linear_combination r2662
  · unfold dummyRvkRandomizerDeltaX121 dummyRvkRandomizerDeltaY121
    linear_combination r2663
  · unfold dummyRvkRandomizerDeltaX121 dummyRvkRandomizerDeltaY121
    linear_combination r2664
  · unfold dummyRvkRandomizerDeltaX121
    linear_combination r2665
  · unfold dummyRvkRandomizerDeltaY121
    linear_combination r2666
  · linear_combination r1927

theorem dummyRvkRandomizer_rows123 (rho : Nat -> F) (h : Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relation rho) :
    Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationRow1928 rho ∧ Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationRow2667 rho ∧ Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationRow2668 rho ∧ Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationRow2669 rho ∧ Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationRow2670 rho ∧ Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationRow2671 rho := by
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relation at h

  rcases h with ⟨

    _, _, _, _, _, _, _, _, _, _,

    _, _, _, _, _, _, _, _, _, _,

    _, _, _, _, p24, _, _, _, _, _,

    _, _, _, p33, _, _, _, _, _, _,

    _, _, _, _, _, _

  ⟩

  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationPart24 at p24

  rcases p24 with ⟨_, _, _, _, _, _, _, _, r1928, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _⟩

  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationPart33 at p33

  rcases p33 with ⟨_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, r2667, r2668, r2669, r2670, r2671, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _⟩

  exact ⟨r1928, r2667, r2668, r2669, r2670, r2671⟩

theorem dummyRvkRandomizer_rung123 (rho : Nat -> F) (h : Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relation rho)
    (bit : Bool) (hbitValue : rho 1929 = Bool.toZMod bit)
    (hacc : EdwardsBridge.onCurve (dummyRvkRandomizerAccState rho 123)) :
    Shieldd.GnarkFormal.RvkFixedBaseLadderChoiceFree.FixedStepRel
      123 (Bool.toZMod bit) (dummyRvkRandomizerAccState rho 123)
      (dummyRvkRandomizerAccState rho 124) := by
  obtain ⟨r1928, r2667, r2668, r2669, r2670, r2671⟩ := dummyRvkRandomizer_rows123 rho h
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationRow1928 at r1928

  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationRow2667 Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationLc2143 Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationLc2144 at r2667

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r2667

  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationRow2668 Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationLc2145 at r2668

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r2668

  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationRow2669 Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationLc2146 at r2669

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r2669

  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationRow2670 Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationLc2147 at r2670

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r2670

  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationRow2671 Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationLc2148 at r2671

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r2671

  have hnextx : dummyRvkRandomizerDeltaX123 rho =
      dummyRvkRandomizerDeltaX122 rho + rho 2671 := by
    unfold dummyRvkRandomizerDeltaX123 dummyRvkRandomizerDeltaX122
    rw [Shieldd.GnarkFormal.StrideRun.sumAux_succ rho 2061 5 122]

    ring

  have hnexty : dummyRvkRandomizerDeltaY123 rho =
      dummyRvkRandomizerDeltaY122 rho + rho 2672 := by
    unfold dummyRvkRandomizerDeltaY123 dummyRvkRandomizerDeltaY122
    rw [Shieldd.GnarkFormal.StrideRun.sumAux_succ rho 2062 5 122]

    ring

  change Shieldd.GnarkFormal.RvkFixedBaseLadderChoiceFree.FixedStepRel 123
    (Bool.toZMod bit) ⟨((4959445789346820725352484487855828915252512307947624787834978378872129235627 : F) * rho 1806 + dummyRvkRandomizerDeltaX122 rho : F),
      ((1 : F) + (6060471950081851567114691557659790004756535011754163002297540472747064943287 : F) * rho 1806 + dummyRvkRandomizerDeltaY122 rho : F)⟩
    ⟨((4959445789346820725352484487855828915252512307947624787834978378872129235627 : F) * rho 1806 + dummyRvkRandomizerDeltaX123 rho : F),
      ((1 : F) + (6060471950081851567114691557659790004756535011754163002297540472747064943287 : F) * rho 1806 + dummyRvkRandomizerDeltaY123 rho : F)⟩
  rw [hnextx, hnexty, ← hbitValue]
  apply Shieldd.GnarkFormal.RvkFixedGenInst0ChoiceFree.rung123_wide (rho 1806) (rho 1929) (dummyRvkRandomizerDeltaX122 rho) (dummyRvkRandomizerDeltaY122 rho) (rho 2668) (rho 2669) (rho 2670) (rho 2671) (rho 2672) hacc
  · unfold dummyRvkRandomizerDeltaX122 dummyRvkRandomizerDeltaY122
    linear_combination r2667
  · unfold dummyRvkRandomizerDeltaX122 dummyRvkRandomizerDeltaY122
    linear_combination r2668
  · unfold dummyRvkRandomizerDeltaX122 dummyRvkRandomizerDeltaY122
    linear_combination r2669
  · unfold dummyRvkRandomizerDeltaX122
    linear_combination r2670
  · unfold dummyRvkRandomizerDeltaY122
    linear_combination r2671
  · linear_combination r1928

theorem dummyRvkRandomizer_rows124 (rho : Nat -> F) (h : Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relation rho) :
    Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationRow1929 rho ∧ Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationRow2672 rho ∧ Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationRow2673 rho ∧ Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationRow2674 rho ∧ Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationRow2675 rho ∧ Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationRow2676 rho := by
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relation at h

  rcases h with ⟨

    _, _, _, _, _, _, _, _, _, _,

    _, _, _, _, _, _, _, _, _, _,

    _, _, _, _, p24, _, _, _, _, _,

    _, _, _, p33, _, _, _, _, _, _,

    _, _, _, _, _, _

  ⟩

  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationPart24 at p24

  rcases p24 with ⟨_, _, _, _, _, _, _, _, _, r1929, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _⟩

  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationPart33 at p33

  rcases p33 with ⟨_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, r2672, r2673, r2674, r2675, r2676, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _⟩

  exact ⟨r1929, r2672, r2673, r2674, r2675, r2676⟩

theorem dummyRvkRandomizer_rung124 (rho : Nat -> F) (h : Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relation rho)
    (bit : Bool) (hbitValue : rho 1930 = Bool.toZMod bit)
    (hacc : EdwardsBridge.onCurve (dummyRvkRandomizerAccState rho 124)) :
    Shieldd.GnarkFormal.RvkFixedBaseLadderChoiceFree.FixedStepRel
      124 (Bool.toZMod bit) (dummyRvkRandomizerAccState rho 124)
      (dummyRvkRandomizerAccState rho 125) := by
  obtain ⟨r1929, r2672, r2673, r2674, r2675, r2676⟩ := dummyRvkRandomizer_rows124 rho h
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationRow1929 at r1929

  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationRow2672 Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationLc2149 Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationLc2150 at r2672

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r2672

  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationRow2673 Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationLc2151 at r2673

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r2673

  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationRow2674 Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationLc2152 at r2674

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r2674

  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationRow2675 Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationLc2153 at r2675

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r2675

  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationRow2676 Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationLc2154 at r2676

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r2676

  have hnextx : dummyRvkRandomizerDeltaX124 rho =
      dummyRvkRandomizerDeltaX123 rho + rho 2676 := by
    unfold dummyRvkRandomizerDeltaX124 dummyRvkRandomizerDeltaX123
    rw [Shieldd.GnarkFormal.StrideRun.sumAux_succ rho 2061 5 123]

    ring

  have hnexty : dummyRvkRandomizerDeltaY124 rho =
      dummyRvkRandomizerDeltaY123 rho + rho 2677 := by
    unfold dummyRvkRandomizerDeltaY124 dummyRvkRandomizerDeltaY123
    rw [Shieldd.GnarkFormal.StrideRun.sumAux_succ rho 2062 5 123]

    ring

  change Shieldd.GnarkFormal.RvkFixedBaseLadderChoiceFree.FixedStepRel 124
    (Bool.toZMod bit) ⟨((4959445789346820725352484487855828915252512307947624787834978378872129235627 : F) * rho 1806 + dummyRvkRandomizerDeltaX123 rho : F),
      ((1 : F) + (6060471950081851567114691557659790004756535011754163002297540472747064943287 : F) * rho 1806 + dummyRvkRandomizerDeltaY123 rho : F)⟩
    ⟨((4959445789346820725352484487855828915252512307947624787834978378872129235627 : F) * rho 1806 + dummyRvkRandomizerDeltaX124 rho : F),
      ((1 : F) + (6060471950081851567114691557659790004756535011754163002297540472747064943287 : F) * rho 1806 + dummyRvkRandomizerDeltaY124 rho : F)⟩
  rw [hnextx, hnexty, ← hbitValue]
  apply Shieldd.GnarkFormal.RvkFixedGenInst0ChoiceFree.rung124_wide (rho 1806) (rho 1930) (dummyRvkRandomizerDeltaX123 rho) (dummyRvkRandomizerDeltaY123 rho) (rho 2673) (rho 2674) (rho 2675) (rho 2676) (rho 2677) hacc
  · unfold dummyRvkRandomizerDeltaX123 dummyRvkRandomizerDeltaY123
    linear_combination r2672
  · unfold dummyRvkRandomizerDeltaX123 dummyRvkRandomizerDeltaY123
    linear_combination r2673
  · unfold dummyRvkRandomizerDeltaX123 dummyRvkRandomizerDeltaY123
    linear_combination r2674
  · unfold dummyRvkRandomizerDeltaX123
    linear_combination r2675
  · unfold dummyRvkRandomizerDeltaY123
    linear_combination r2676
  · linear_combination r1929

theorem dummyRvkRandomizer_rows125 (rho : Nat -> F) (h : Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relation rho) :
    Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationRow1930 rho ∧ Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationRow2677 rho ∧ Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationRow2678 rho ∧ Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationRow2679 rho ∧ Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationRow2680 rho ∧ Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationRow2681 rho := by
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relation at h

  rcases h with ⟨

    _, _, _, _, _, _, _, _, _, _,

    _, _, _, _, _, _, _, _, _, _,

    _, _, _, _, p24, _, _, _, _, _,

    _, _, _, p33, _, _, _, _, _, _,

    _, _, _, _, _, _

  ⟩

  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationPart24 at p24

  rcases p24 with ⟨_, _, _, _, _, _, _, _, _, _, r1930, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _⟩

  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationPart33 at p33

  rcases p33 with ⟨_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, r2677, r2678, r2679, r2680, r2681, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _⟩

  exact ⟨r1930, r2677, r2678, r2679, r2680, r2681⟩

theorem dummyRvkRandomizer_rung125 (rho : Nat -> F) (h : Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relation rho)
    (bit : Bool) (hbitValue : rho 1931 = Bool.toZMod bit)
    (hacc : EdwardsBridge.onCurve (dummyRvkRandomizerAccState rho 125)) :
    Shieldd.GnarkFormal.RvkFixedBaseLadderChoiceFree.FixedStepRel
      125 (Bool.toZMod bit) (dummyRvkRandomizerAccState rho 125)
      (dummyRvkRandomizerAccState rho 126) := by
  obtain ⟨r1930, r2677, r2678, r2679, r2680, r2681⟩ := dummyRvkRandomizer_rows125 rho h
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationRow1930 at r1930

  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationRow2677 Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationLc2155 Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationLc2156 at r2677

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r2677

  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationRow2678 Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationLc2157 at r2678

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r2678

  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationRow2679 Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationLc2158 at r2679

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r2679

  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationRow2680 Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationLc2159 at r2680

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r2680

  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationRow2681 Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationLc2160 at r2681

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r2681

  have hnextx : dummyRvkRandomizerDeltaX125 rho =
      dummyRvkRandomizerDeltaX124 rho + rho 2681 := by
    unfold dummyRvkRandomizerDeltaX125 dummyRvkRandomizerDeltaX124
    rw [Shieldd.GnarkFormal.StrideRun.sumAux_succ rho 2061 5 124]

    ring

  have hnexty : dummyRvkRandomizerDeltaY125 rho =
      dummyRvkRandomizerDeltaY124 rho + rho 2682 := by
    unfold dummyRvkRandomizerDeltaY125 dummyRvkRandomizerDeltaY124
    rw [Shieldd.GnarkFormal.StrideRun.sumAux_succ rho 2062 5 124]

    ring

  change Shieldd.GnarkFormal.RvkFixedBaseLadderChoiceFree.FixedStepRel 125
    (Bool.toZMod bit) ⟨((4959445789346820725352484487855828915252512307947624787834978378872129235627 : F) * rho 1806 + dummyRvkRandomizerDeltaX124 rho : F),
      ((1 : F) + (6060471950081851567114691557659790004756535011754163002297540472747064943287 : F) * rho 1806 + dummyRvkRandomizerDeltaY124 rho : F)⟩
    ⟨((4959445789346820725352484487855828915252512307947624787834978378872129235627 : F) * rho 1806 + dummyRvkRandomizerDeltaX125 rho : F),
      ((1 : F) + (6060471950081851567114691557659790004756535011754163002297540472747064943287 : F) * rho 1806 + dummyRvkRandomizerDeltaY125 rho : F)⟩
  rw [hnextx, hnexty, ← hbitValue]
  apply Shieldd.GnarkFormal.RvkFixedGenInst0ChoiceFree.rung125_wide (rho 1806) (rho 1931) (dummyRvkRandomizerDeltaX124 rho) (dummyRvkRandomizerDeltaY124 rho) (rho 2678) (rho 2679) (rho 2680) (rho 2681) (rho 2682) hacc
  · unfold dummyRvkRandomizerDeltaX124 dummyRvkRandomizerDeltaY124
    linear_combination r2677
  · unfold dummyRvkRandomizerDeltaX124 dummyRvkRandomizerDeltaY124
    linear_combination r2678
  · unfold dummyRvkRandomizerDeltaX124 dummyRvkRandomizerDeltaY124
    linear_combination r2679
  · unfold dummyRvkRandomizerDeltaX124
    linear_combination r2680
  · unfold dummyRvkRandomizerDeltaY124
    linear_combination r2681
  · linear_combination r1930

theorem dummyRvkRandomizer_rows126 (rho : Nat -> F) (h : Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relation rho) :
    Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationRow1931 rho ∧ Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationRow2682 rho ∧ Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationRow2683 rho ∧ Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationRow2684 rho ∧ Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationRow2685 rho ∧ Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationRow2686 rho := by
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relation at h

  rcases h with ⟨

    _, _, _, _, _, _, _, _, _, _,

    _, _, _, _, _, _, _, _, _, _,

    _, _, _, _, p24, _, _, _, _, _,

    _, _, _, p33, _, _, _, _, _, _,

    _, _, _, _, _, _

  ⟩

  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationPart24 at p24

  rcases p24 with ⟨_, _, _, _, _, _, _, _, _, _, _, r1931, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _⟩

  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationPart33 at p33

  rcases p33 with ⟨_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, r2682, r2683, r2684, r2685, r2686, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _⟩

  exact ⟨r1931, r2682, r2683, r2684, r2685, r2686⟩

theorem dummyRvkRandomizer_rung126 (rho : Nat -> F) (h : Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relation rho)
    (bit : Bool) (hbitValue : rho 1932 = Bool.toZMod bit)
    (hacc : EdwardsBridge.onCurve (dummyRvkRandomizerAccState rho 126)) :
    Shieldd.GnarkFormal.RvkFixedBaseLadderChoiceFree.FixedStepRel
      126 (Bool.toZMod bit) (dummyRvkRandomizerAccState rho 126)
      (dummyRvkRandomizerAccState rho 127) := by
  obtain ⟨r1931, r2682, r2683, r2684, r2685, r2686⟩ := dummyRvkRandomizer_rows126 rho h
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationRow1931 at r1931

  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationRow2682 Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationLc2161 Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationLc2162 at r2682

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r2682

  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationRow2683 Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationLc2163 at r2683

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r2683

  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationRow2684 Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationLc2164 at r2684

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r2684

  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationRow2685 Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationLc2165 at r2685

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r2685

  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationRow2686 Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationLc2166 at r2686

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r2686

  have hnextx : dummyRvkRandomizerDeltaX126 rho =
      dummyRvkRandomizerDeltaX125 rho + rho 2686 := by
    unfold dummyRvkRandomizerDeltaX126 dummyRvkRandomizerDeltaX125
    rw [Shieldd.GnarkFormal.StrideRun.sumAux_succ rho 2061 5 125]

    ring

  have hnexty : dummyRvkRandomizerDeltaY126 rho =
      dummyRvkRandomizerDeltaY125 rho + rho 2687 := by
    unfold dummyRvkRandomizerDeltaY126 dummyRvkRandomizerDeltaY125
    rw [Shieldd.GnarkFormal.StrideRun.sumAux_succ rho 2062 5 125]

    ring

  change Shieldd.GnarkFormal.RvkFixedBaseLadderChoiceFree.FixedStepRel 126
    (Bool.toZMod bit) ⟨((4959445789346820725352484487855828915252512307947624787834978378872129235627 : F) * rho 1806 + dummyRvkRandomizerDeltaX125 rho : F),
      ((1 : F) + (6060471950081851567114691557659790004756535011754163002297540472747064943287 : F) * rho 1806 + dummyRvkRandomizerDeltaY125 rho : F)⟩
    ⟨((4959445789346820725352484487855828915252512307947624787834978378872129235627 : F) * rho 1806 + dummyRvkRandomizerDeltaX126 rho : F),
      ((1 : F) + (6060471950081851567114691557659790004756535011754163002297540472747064943287 : F) * rho 1806 + dummyRvkRandomizerDeltaY126 rho : F)⟩
  rw [hnextx, hnexty, ← hbitValue]
  apply Shieldd.GnarkFormal.RvkFixedGenInst0ChoiceFree.rung126_wide (rho 1806) (rho 1932) (dummyRvkRandomizerDeltaX125 rho) (dummyRvkRandomizerDeltaY125 rho) (rho 2683) (rho 2684) (rho 2685) (rho 2686) (rho 2687) hacc
  · unfold dummyRvkRandomizerDeltaX125 dummyRvkRandomizerDeltaY125
    linear_combination r2682
  · unfold dummyRvkRandomizerDeltaX125 dummyRvkRandomizerDeltaY125
    linear_combination r2683
  · unfold dummyRvkRandomizerDeltaX125 dummyRvkRandomizerDeltaY125
    linear_combination r2684
  · unfold dummyRvkRandomizerDeltaX125
    linear_combination r2685
  · unfold dummyRvkRandomizerDeltaY125
    linear_combination r2686
  · linear_combination r1931

theorem dummyRvkRandomizer_rows127 (rho : Nat -> F) (h : Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relation rho) :
    Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationRow1932 rho ∧ Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationRow2687 rho ∧ Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationRow2688 rho ∧ Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationRow2689 rho ∧ Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationRow2690 rho ∧ Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationRow2691 rho := by
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relation at h

  rcases h with ⟨

    _, _, _, _, _, _, _, _, _, _,

    _, _, _, _, _, _, _, _, _, _,

    _, _, _, _, p24, _, _, _, _, _,

    _, _, _, p33, _, _, _, _, _, _,

    _, _, _, _, _, _

  ⟩

  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationPart24 at p24

  rcases p24 with ⟨_, _, _, _, _, _, _, _, _, _, _, _, r1932, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _⟩

  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationPart33 at p33

  rcases p33 with ⟨_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, r2687, r2688, r2689, r2690, r2691, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _⟩

  exact ⟨r1932, r2687, r2688, r2689, r2690, r2691⟩

theorem dummyRvkRandomizer_rung127 (rho : Nat -> F) (h : Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relation rho)
    (bit : Bool) (hbitValue : rho 1933 = Bool.toZMod bit)
    (hacc : EdwardsBridge.onCurve (dummyRvkRandomizerAccState rho 127)) :
    Shieldd.GnarkFormal.RvkFixedBaseLadderChoiceFree.FixedStepRel
      127 (Bool.toZMod bit) (dummyRvkRandomizerAccState rho 127)
      (dummyRvkRandomizerAccState rho 128) := by
  obtain ⟨r1932, r2687, r2688, r2689, r2690, r2691⟩ := dummyRvkRandomizer_rows127 rho h
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationRow1932 at r1932

  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationRow2687 Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationLc2167 Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationLc2168 at r2687

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r2687

  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationRow2688 Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationLc2169 at r2688

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r2688

  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationRow2689 Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationLc2170 at r2689

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r2689

  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationRow2690 Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationLc2171 at r2690

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r2690

  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationRow2691 Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationLc2172 at r2691

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r2691

  have hnextx : dummyRvkRandomizerDeltaX127 rho =
      dummyRvkRandomizerDeltaX126 rho + rho 2691 := by
    unfold dummyRvkRandomizerDeltaX127 dummyRvkRandomizerDeltaX126
    rw [Shieldd.GnarkFormal.StrideRun.sumAux_succ rho 2061 5 126]

    ring

  have hnexty : dummyRvkRandomizerDeltaY127 rho =
      dummyRvkRandomizerDeltaY126 rho + rho 2692 := by
    unfold dummyRvkRandomizerDeltaY127 dummyRvkRandomizerDeltaY126
    rw [Shieldd.GnarkFormal.StrideRun.sumAux_succ rho 2062 5 126]

    ring

  change Shieldd.GnarkFormal.RvkFixedBaseLadderChoiceFree.FixedStepRel 127
    (Bool.toZMod bit) ⟨((4959445789346820725352484487855828915252512307947624787834978378872129235627 : F) * rho 1806 + dummyRvkRandomizerDeltaX126 rho : F),
      ((1 : F) + (6060471950081851567114691557659790004756535011754163002297540472747064943287 : F) * rho 1806 + dummyRvkRandomizerDeltaY126 rho : F)⟩
    ⟨((4959445789346820725352484487855828915252512307947624787834978378872129235627 : F) * rho 1806 + dummyRvkRandomizerDeltaX127 rho : F),
      ((1 : F) + (6060471950081851567114691557659790004756535011754163002297540472747064943287 : F) * rho 1806 + dummyRvkRandomizerDeltaY127 rho : F)⟩
  rw [hnextx, hnexty, ← hbitValue]
  apply Shieldd.GnarkFormal.RvkFixedGenInst0ChoiceFree.rung127_wide (rho 1806) (rho 1933) (dummyRvkRandomizerDeltaX126 rho) (dummyRvkRandomizerDeltaY126 rho) (rho 2688) (rho 2689) (rho 2690) (rho 2691) (rho 2692) hacc
  · unfold dummyRvkRandomizerDeltaX126 dummyRvkRandomizerDeltaY126
    linear_combination r2687
  · unfold dummyRvkRandomizerDeltaX126 dummyRvkRandomizerDeltaY126
    linear_combination r2688
  · unfold dummyRvkRandomizerDeltaX126 dummyRvkRandomizerDeltaY126
    linear_combination r2689
  · unfold dummyRvkRandomizerDeltaX126
    linear_combination r2690
  · unfold dummyRvkRandomizerDeltaY126
    linear_combination r2691
  · linear_combination r1932

theorem dummyRvkRandomizer_rows128 (rho : Nat -> F) (h : Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relation rho) :
    Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationRow1933 rho ∧ Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationRow2692 rho ∧ Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationRow2693 rho ∧ Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationRow2694 rho ∧ Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationRow2695 rho ∧ Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationRow2696 rho := by
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relation at h

  rcases h with ⟨

    _, _, _, _, _, _, _, _, _, _,

    _, _, _, _, _, _, _, _, _, _,

    _, _, _, _, p24, _, _, _, _, _,

    _, _, _, p33, _, _, _, _, _, _,

    _, _, _, _, _, _

  ⟩

  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationPart24 at p24

  rcases p24 with ⟨_, _, _, _, _, _, _, _, _, _, _, _, _, r1933, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _⟩

  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationPart33 at p33

  rcases p33 with ⟨_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, r2692, r2693, r2694, r2695, r2696, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _⟩

  exact ⟨r1933, r2692, r2693, r2694, r2695, r2696⟩

theorem dummyRvkRandomizer_rung128 (rho : Nat -> F) (h : Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relation rho)
    (bit : Bool) (hbitValue : rho 1934 = Bool.toZMod bit)
    (hacc : EdwardsBridge.onCurve (dummyRvkRandomizerAccState rho 128)) :
    Shieldd.GnarkFormal.RvkFixedBaseLadderChoiceFree.FixedStepRel
      128 (Bool.toZMod bit) (dummyRvkRandomizerAccState rho 128)
      (dummyRvkRandomizerAccState rho 129) := by
  obtain ⟨r1933, r2692, r2693, r2694, r2695, r2696⟩ := dummyRvkRandomizer_rows128 rho h
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationRow1933 at r1933

  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationRow2692 Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationLc2173 Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationLc2174 at r2692

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r2692

  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationRow2693 Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationLc2175 at r2693

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r2693

  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationRow2694 Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationLc2176 at r2694

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r2694

  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationRow2695 Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationLc2177 at r2695

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r2695

  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationRow2696 Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationLc2178 at r2696

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r2696

  have hnextx : dummyRvkRandomizerDeltaX128 rho =
      dummyRvkRandomizerDeltaX127 rho + rho 2696 := by
    unfold dummyRvkRandomizerDeltaX128 dummyRvkRandomizerDeltaX127
    rw [Shieldd.GnarkFormal.StrideRun.sumAux_succ rho 2061 5 127]

    ring

  have hnexty : dummyRvkRandomizerDeltaY128 rho =
      dummyRvkRandomizerDeltaY127 rho + rho 2697 := by
    unfold dummyRvkRandomizerDeltaY128 dummyRvkRandomizerDeltaY127
    rw [Shieldd.GnarkFormal.StrideRun.sumAux_succ rho 2062 5 127]

    ring

  change Shieldd.GnarkFormal.RvkFixedBaseLadderChoiceFree.FixedStepRel 128
    (Bool.toZMod bit) ⟨((4959445789346820725352484487855828915252512307947624787834978378872129235627 : F) * rho 1806 + dummyRvkRandomizerDeltaX127 rho : F),
      ((1 : F) + (6060471950081851567114691557659790004756535011754163002297540472747064943287 : F) * rho 1806 + dummyRvkRandomizerDeltaY127 rho : F)⟩
    ⟨((4959445789346820725352484487855828915252512307947624787834978378872129235627 : F) * rho 1806 + dummyRvkRandomizerDeltaX128 rho : F),
      ((1 : F) + (6060471950081851567114691557659790004756535011754163002297540472747064943287 : F) * rho 1806 + dummyRvkRandomizerDeltaY128 rho : F)⟩
  rw [hnextx, hnexty, ← hbitValue]
  apply Shieldd.GnarkFormal.RvkFixedGenInst0ChoiceFree.rung128_wide (rho 1806) (rho 1934) (dummyRvkRandomizerDeltaX127 rho) (dummyRvkRandomizerDeltaY127 rho) (rho 2693) (rho 2694) (rho 2695) (rho 2696) (rho 2697) hacc
  · unfold dummyRvkRandomizerDeltaX127 dummyRvkRandomizerDeltaY127
    linear_combination r2692
  · unfold dummyRvkRandomizerDeltaX127 dummyRvkRandomizerDeltaY127
    linear_combination r2693
  · unfold dummyRvkRandomizerDeltaX127 dummyRvkRandomizerDeltaY127
    linear_combination r2694
  · unfold dummyRvkRandomizerDeltaX127
    linear_combination r2695
  · unfold dummyRvkRandomizerDeltaY127
    linear_combination r2696
  · linear_combination r1933

theorem dummyRvkRandomizer_rows129 (rho : Nat -> F) (h : Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relation rho) :
    Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationRow1934 rho ∧ Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationRow2697 rho ∧ Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationRow2698 rho ∧ Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationRow2699 rho ∧ Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationRow2700 rho ∧ Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationRow2701 rho := by
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relation at h

  rcases h with ⟨

    _, _, _, _, _, _, _, _, _, _,

    _, _, _, _, _, _, _, _, _, _,

    _, _, _, _, p24, _, _, _, _, _,

    _, _, _, p33, _, _, _, _, _, _,

    _, _, _, _, _, _

  ⟩

  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationPart24 at p24

  rcases p24 with ⟨_, _, _, _, _, _, _, _, _, _, _, _, _, _, r1934, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _⟩

  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationPart33 at p33

  rcases p33 with ⟨_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, r2697, r2698, r2699, r2700, r2701, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _⟩

  exact ⟨r1934, r2697, r2698, r2699, r2700, r2701⟩

theorem dummyRvkRandomizer_rung129 (rho : Nat -> F) (h : Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relation rho)
    (bit : Bool) (hbitValue : rho 1935 = Bool.toZMod bit)
    (hacc : EdwardsBridge.onCurve (dummyRvkRandomizerAccState rho 129)) :
    Shieldd.GnarkFormal.RvkFixedBaseLadderChoiceFree.FixedStepRel
      129 (Bool.toZMod bit) (dummyRvkRandomizerAccState rho 129)
      (dummyRvkRandomizerAccState rho 130) := by
  obtain ⟨r1934, r2697, r2698, r2699, r2700, r2701⟩ := dummyRvkRandomizer_rows129 rho h
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationRow1934 at r1934

  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationRow2697 Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationLc2179 Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationLc2180 at r2697

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r2697

  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationRow2698 Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationLc2181 at r2698

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r2698

  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationRow2699 Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationLc2182 at r2699

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r2699

  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationRow2700 Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationLc2183 at r2700

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r2700

  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationRow2701 Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationLc2184 at r2701

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r2701

  have hnextx : dummyRvkRandomizerDeltaX129 rho =
      dummyRvkRandomizerDeltaX128 rho + rho 2701 := by
    unfold dummyRvkRandomizerDeltaX129 dummyRvkRandomizerDeltaX128
    rw [Shieldd.GnarkFormal.StrideRun.sumAux_succ rho 2061 5 128]

    ring

  have hnexty : dummyRvkRandomizerDeltaY129 rho =
      dummyRvkRandomizerDeltaY128 rho + rho 2702 := by
    unfold dummyRvkRandomizerDeltaY129 dummyRvkRandomizerDeltaY128
    rw [Shieldd.GnarkFormal.StrideRun.sumAux_succ rho 2062 5 128]

    ring

  change Shieldd.GnarkFormal.RvkFixedBaseLadderChoiceFree.FixedStepRel 129
    (Bool.toZMod bit) ⟨((4959445789346820725352484487855828915252512307947624787834978378872129235627 : F) * rho 1806 + dummyRvkRandomizerDeltaX128 rho : F),
      ((1 : F) + (6060471950081851567114691557659790004756535011754163002297540472747064943287 : F) * rho 1806 + dummyRvkRandomizerDeltaY128 rho : F)⟩
    ⟨((4959445789346820725352484487855828915252512307947624787834978378872129235627 : F) * rho 1806 + dummyRvkRandomizerDeltaX129 rho : F),
      ((1 : F) + (6060471950081851567114691557659790004756535011754163002297540472747064943287 : F) * rho 1806 + dummyRvkRandomizerDeltaY129 rho : F)⟩
  rw [hnextx, hnexty, ← hbitValue]
  apply Shieldd.GnarkFormal.RvkFixedGenInst0ChoiceFree.rung129_wide (rho 1806) (rho 1935) (dummyRvkRandomizerDeltaX128 rho) (dummyRvkRandomizerDeltaY128 rho) (rho 2698) (rho 2699) (rho 2700) (rho 2701) (rho 2702) hacc
  · unfold dummyRvkRandomizerDeltaX128 dummyRvkRandomizerDeltaY128
    linear_combination r2697
  · unfold dummyRvkRandomizerDeltaX128 dummyRvkRandomizerDeltaY128
    linear_combination r2698
  · unfold dummyRvkRandomizerDeltaX128 dummyRvkRandomizerDeltaY128
    linear_combination r2699
  · unfold dummyRvkRandomizerDeltaX128
    linear_combination r2700
  · unfold dummyRvkRandomizerDeltaY128
    linear_combination r2701
  · linear_combination r1934

theorem dummyRvkRandomizer_rows130 (rho : Nat -> F) (h : Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relation rho) :
    Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationRow1935 rho ∧ Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationRow2702 rho ∧ Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationRow2703 rho ∧ Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationRow2704 rho ∧ Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationRow2705 rho ∧ Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationRow2706 rho := by
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relation at h

  rcases h with ⟨

    _, _, _, _, _, _, _, _, _, _,

    _, _, _, _, _, _, _, _, _, _,

    _, _, _, _, p24, _, _, _, _, _,

    _, _, _, p33, _, _, _, _, _, _,

    _, _, _, _, _, _

  ⟩

  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationPart24 at p24

  rcases p24 with ⟨_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, r1935, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _⟩

  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationPart33 at p33

  rcases p33 with ⟨_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, r2702, r2703, r2704, r2705, r2706, _, _, _, _, _, _, _, _, _, _, _, _, _⟩

  exact ⟨r1935, r2702, r2703, r2704, r2705, r2706⟩

theorem dummyRvkRandomizer_rung130 (rho : Nat -> F) (h : Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relation rho)
    (bit : Bool) (hbitValue : rho 1936 = Bool.toZMod bit)
    (hacc : EdwardsBridge.onCurve (dummyRvkRandomizerAccState rho 130)) :
    Shieldd.GnarkFormal.RvkFixedBaseLadderChoiceFree.FixedStepRel
      130 (Bool.toZMod bit) (dummyRvkRandomizerAccState rho 130)
      (dummyRvkRandomizerAccState rho 131) := by
  obtain ⟨r1935, r2702, r2703, r2704, r2705, r2706⟩ := dummyRvkRandomizer_rows130 rho h
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationRow1935 at r1935

  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationRow2702 Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationLc2185 Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationLc2186 at r2702

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r2702

  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationRow2703 Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationLc2187 at r2703

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r2703

  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationRow2704 Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationLc2188 at r2704

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r2704

  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationRow2705 Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationLc2189 at r2705

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r2705

  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationRow2706 Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relationLc2190 at r2706

  simp only [Shieldd.GnarkFormal.StructuredLC.eval, Shieldd.GnarkFormal.StructuredLC.sumRuns, Shieldd.GnarkFormal.StructuredLC.sumResidual, Shieldd.GnarkFormal.StrideRun.eval] at r2706

  have hnextx : dummyRvkRandomizerDeltaX130 rho =
      dummyRvkRandomizerDeltaX129 rho + rho 2706 := by
    unfold dummyRvkRandomizerDeltaX130 dummyRvkRandomizerDeltaX129
    rw [Shieldd.GnarkFormal.StrideRun.sumAux_succ rho 2061 5 129]

    ring

  have hnexty : dummyRvkRandomizerDeltaY130 rho =
      dummyRvkRandomizerDeltaY129 rho + rho 2707 := by
    unfold dummyRvkRandomizerDeltaY130 dummyRvkRandomizerDeltaY129
    rw [Shieldd.GnarkFormal.StrideRun.sumAux_succ rho 2062 5 129]

    ring

  change Shieldd.GnarkFormal.RvkFixedBaseLadderChoiceFree.FixedStepRel 130
    (Bool.toZMod bit) ⟨((4959445789346820725352484487855828915252512307947624787834978378872129235627 : F) * rho 1806 + dummyRvkRandomizerDeltaX129 rho : F),
      ((1 : F) + (6060471950081851567114691557659790004756535011754163002297540472747064943287 : F) * rho 1806 + dummyRvkRandomizerDeltaY129 rho : F)⟩
    ⟨((4959445789346820725352484487855828915252512307947624787834978378872129235627 : F) * rho 1806 + dummyRvkRandomizerDeltaX130 rho : F),
      ((1 : F) + (6060471950081851567114691557659790004756535011754163002297540472747064943287 : F) * rho 1806 + dummyRvkRandomizerDeltaY130 rho : F)⟩
  rw [hnextx, hnexty, ← hbitValue]
  apply Shieldd.GnarkFormal.RvkFixedGenInst0ChoiceFree.rung130_wide (rho 1806) (rho 1936) (dummyRvkRandomizerDeltaX129 rho) (dummyRvkRandomizerDeltaY129 rho) (rho 2703) (rho 2704) (rho 2705) (rho 2706) (rho 2707) hacc
  · unfold dummyRvkRandomizerDeltaX129 dummyRvkRandomizerDeltaY129
    linear_combination r2702
  · unfold dummyRvkRandomizerDeltaX129 dummyRvkRandomizerDeltaY129
    linear_combination r2703
  · unfold dummyRvkRandomizerDeltaX129 dummyRvkRandomizerDeltaY129
    linear_combination r2704
  · unfold dummyRvkRandomizerDeltaX129
    linear_combination r2705
  · unfold dummyRvkRandomizerDeltaY129
    linear_combination r2706
  · linear_combination r1935

theorem dummyRvkRandomizer_hstep_c12 (rho : Nat -> F)
    (h : Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.relation rho) (bits : List.Vector Bool 251)
    (hbitAt : ∀ i, i < 251 → rho (1806 + i) = Bool.toZMod bits[i]!) :
    ∀ i, 121 ≤ i → i < 131 →
      EdwardsBridge.onCurve (dummyRvkRandomizerAccState rho i) →
      Shieldd.GnarkFormal.RvkFixedBaseLadderChoiceFree.FixedStepRel i
        (Bool.toZMod bits[i]!) (dummyRvkRandomizerAccState rho i)
        (dummyRvkRandomizerAccState rho (i + 1)) := by
  intro i hlo hhi hacc
  interval_cases i
  · exact dummyRvkRandomizer_rung121 rho h bits[121]! (hbitAt 121 (by omega)) hacc
  · exact dummyRvkRandomizer_rung122 rho h bits[122]! (hbitAt 122 (by omega)) hacc
  · exact dummyRvkRandomizer_rung123 rho h bits[123]! (hbitAt 123 (by omega)) hacc
  · exact dummyRvkRandomizer_rung124 rho h bits[124]! (hbitAt 124 (by omega)) hacc
  · exact dummyRvkRandomizer_rung125 rho h bits[125]! (hbitAt 125 (by omega)) hacc
  · exact dummyRvkRandomizer_rung126 rho h bits[126]! (hbitAt 126 (by omega)) hacc
  · exact dummyRvkRandomizer_rung127 rho h bits[127]! (hbitAt 127 (by omega)) hacc
  · exact dummyRvkRandomizer_rung128 rho h bits[128]! (hbitAt 128 (by omega)) hacc
  · exact dummyRvkRandomizer_rung129 rho h bits[129]! (hbitAt 129 (by omega)) hacc
  · exact dummyRvkRandomizer_rung130 rho h bits[130]! (hbitAt 130 (by omega)) hacc

end Shieldd.GnarkFormal.Deployed.Templates.Semantics.TDecafRandomizedVerificationKeyDummy_e51d3ae895dfdd9467b9c73fdd305f3afed8e71a1350fb96e3119a3fba8860a5.DummyRvkSupport
