/-
GENERATED by gen/gen_certified_composite_semantics.py -- do not edit.
-/
import ShielddGnarkFormal.Deployed.Templates.Semantics.TGadgetPoseidonEncryptionDetection_cb69c394a6636349ef1ca32ae7f664980eedd6a7010cb2a2d96541cc47984b25PoseidonBlock4Base
import ShielddGnarkFormal.Deployed.Templates.Relations.TGadgetPoseidonEncryptionDetection_cb69c394a6636349ef1ca32ae7f664980eedd6a7010cb2a2d96541cc47984b25
import ShielddGnarkFormal.Deployed.Poseidon2Link
import Mathlib.Tactic.LinearCombination
import Mathlib.Tactic.Ring

set_option maxRecDepth 1000000
set_option maxHeartbeats 10000000

namespace Shieldd.GnarkFormal.Deployed.Templates.Semantics.TGadgetPoseidonEncryptionDetection_cb69c394a6636349ef1ca32ae7f664980eedd6a7010cb2a2d96541cc47984b25Poseidon.Block4.Gate1

open Shieldd.GnarkFormal.Deployed.Templates.Semantics.TGadgetPoseidonEncryptionDetection_cb69c394a6636349ef1ca32ae7f664980eedd6a7010cb2a2d96541cc47984b25Poseidon.Block4
attribute [-instance] ZMod.instField
open scoped Shieldd.GnarkFormal.ChoiceFreeZMod

theorem block4Part1 (rho : Nat → F) (h2182 : Shieldd.GnarkFormal.Deployed.Templates.Relations.TGadgetPoseidonEncryptionDetection_cb69c394a6636349ef1ca32ae7f664980eedd6a7010cb2a2d96541cc47984b25.relationRow2182 rho) (h2183 : Shieldd.GnarkFormal.Deployed.Templates.Relations.TGadgetPoseidonEncryptionDetection_cb69c394a6636349ef1ca32ae7f664980eedd6a7010cb2a2d96541cc47984b25.relationRow2183 rho) (h2184 : Shieldd.GnarkFormal.Deployed.Templates.Relations.TGadgetPoseidonEncryptionDetection_cb69c394a6636349ef1ca32ae7f664980eedd6a7010cb2a2d96541cc47984b25.relationRow2184 rho) (h2185 : Shieldd.GnarkFormal.Deployed.Templates.Relations.TGadgetPoseidonEncryptionDetection_cb69c394a6636349ef1ca32ae7f664980eedd6a7010cb2a2d96541cc47984b25.relationRow2185 rho) (h2186 : Shieldd.GnarkFormal.Deployed.Templates.Relations.TGadgetPoseidonEncryptionDetection_cb69c394a6636349ef1ca32ae7f664980eedd6a7010cb2a2d96541cc47984b25.relationRow2186 rho) :
    rho 1850 = Shieldd.GnarkFormal.Poseidon2Bridge.p17
      (block4RoundInput1 rho) := by
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TGadgetPoseidonEncryptionDetection_cb69c394a6636349ef1ca32ae7f664980eedd6a7010cb2a2d96541cc47984b25.relationRow2182 at h2182
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TGadgetPoseidonEncryptionDetection_cb69c394a6636349ef1ca32ae7f664980eedd6a7010cb2a2d96541cc47984b25.relationRow2183 at h2183
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TGadgetPoseidonEncryptionDetection_cb69c394a6636349ef1ca32ae7f664980eedd6a7010cb2a2d96541cc47984b25.relationRow2184 at h2184
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TGadgetPoseidonEncryptionDetection_cb69c394a6636349ef1ca32ae7f664980eedd6a7010cb2a2d96541cc47984b25.relationRow2185 at h2185
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TGadgetPoseidonEncryptionDetection_cb69c394a6636349ef1ca32ae7f664980eedd6a7010cb2a2d96541cc47984b25.relationRow2186 at h2186
  have hblock4Input1 : block4RoundInput1 rho = (1228136616197762052653441821720785113809650554844944689742273658631473420430 : F) + (6333346312071277818186618704086159898531924501365547870951425091938056929281 : F) * rho 1845 := by
    unfold block4RoundInput1
    rfl
  apply Shieldd.GnarkFormal.Deployed.Templates.Semantics.TransferPoseidon2Trace.p17_from_rows
      (block4RoundInput1 rho)
      (rho 1846) (rho 1847) (rho 1848) (rho 1849) (rho 1850)
  · rw [hblock4Input1]; linear_combination h2182
  · linear_combination h2183
  · linear_combination h2184
  · linear_combination h2185
  · rw [hblock4Input1]; linear_combination h2186

theorem block4Part2 (rho : Nat → F) (h2187 : Shieldd.GnarkFormal.Deployed.Templates.Relations.TGadgetPoseidonEncryptionDetection_cb69c394a6636349ef1ca32ae7f664980eedd6a7010cb2a2d96541cc47984b25.relationRow2187 rho) (h2188 : Shieldd.GnarkFormal.Deployed.Templates.Relations.TGadgetPoseidonEncryptionDetection_cb69c394a6636349ef1ca32ae7f664980eedd6a7010cb2a2d96541cc47984b25.relationRow2188 rho) (h2189 : Shieldd.GnarkFormal.Deployed.Templates.Relations.TGadgetPoseidonEncryptionDetection_cb69c394a6636349ef1ca32ae7f664980eedd6a7010cb2a2d96541cc47984b25.relationRow2189 rho) (h2190 : Shieldd.GnarkFormal.Deployed.Templates.Relations.TGadgetPoseidonEncryptionDetection_cb69c394a6636349ef1ca32ae7f664980eedd6a7010cb2a2d96541cc47984b25.relationRow2190 rho) (h2191 : Shieldd.GnarkFormal.Deployed.Templates.Relations.TGadgetPoseidonEncryptionDetection_cb69c394a6636349ef1ca32ae7f664980eedd6a7010cb2a2d96541cc47984b25.relationRow2191 rho) :
    rho 1855 = Shieldd.GnarkFormal.Poseidon2Bridge.p17
      (block4RoundInput2 rho) := by
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TGadgetPoseidonEncryptionDetection_cb69c394a6636349ef1ca32ae7f664980eedd6a7010cb2a2d96541cc47984b25.relationRow2187 at h2187
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TGadgetPoseidonEncryptionDetection_cb69c394a6636349ef1ca32ae7f664980eedd6a7010cb2a2d96541cc47984b25.relationRow2188 at h2188
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TGadgetPoseidonEncryptionDetection_cb69c394a6636349ef1ca32ae7f664980eedd6a7010cb2a2d96541cc47984b25.relationRow2189 at h2189
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TGadgetPoseidonEncryptionDetection_cb69c394a6636349ef1ca32ae7f664980eedd6a7010cb2a2d96541cc47984b25.relationRow2190 at h2190
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TGadgetPoseidonEncryptionDetection_cb69c394a6636349ef1ca32ae7f664980eedd6a7010cb2a2d96541cc47984b25.relationRow2191 at h2191
  have hblock4Input2 : block4RoundInput2 rho = (5229801747739620403852565443819552361759989826831810505565125521907524166361 : F) + (6755569399542696339399059951025237225100719468123251062348186764733927391233 : F) * rho 1845 := by
    unfold block4RoundInput2
    rfl
  apply Shieldd.GnarkFormal.Deployed.Templates.Semantics.TransferPoseidon2Trace.p17_from_rows
      (block4RoundInput2 rho)
      (rho 1851) (rho 1852) (rho 1853) (rho 1854) (rho 1855)
  · rw [hblock4Input2]; linear_combination h2187
  · linear_combination h2188
  · linear_combination h2189
  · linear_combination h2190
  · rw [hblock4Input2]; linear_combination h2191

theorem block4Part3 (rho : Nat → F) (h2192 : Shieldd.GnarkFormal.Deployed.Templates.Relations.TGadgetPoseidonEncryptionDetection_cb69c394a6636349ef1ca32ae7f664980eedd6a7010cb2a2d96541cc47984b25.relationRow2192 rho) (h2193 : Shieldd.GnarkFormal.Deployed.Templates.Relations.TGadgetPoseidonEncryptionDetection_cb69c394a6636349ef1ca32ae7f664980eedd6a7010cb2a2d96541cc47984b25.relationRow2193 rho) (h2194 : Shieldd.GnarkFormal.Deployed.Templates.Relations.TGadgetPoseidonEncryptionDetection_cb69c394a6636349ef1ca32ae7f664980eedd6a7010cb2a2d96541cc47984b25.relationRow2194 rho) (h2195 : Shieldd.GnarkFormal.Deployed.Templates.Relations.TGadgetPoseidonEncryptionDetection_cb69c394a6636349ef1ca32ae7f664980eedd6a7010cb2a2d96541cc47984b25.relationRow2195 rho) (h2196 : Shieldd.GnarkFormal.Deployed.Templates.Relations.TGadgetPoseidonEncryptionDetection_cb69c394a6636349ef1ca32ae7f664980eedd6a7010cb2a2d96541cc47984b25.relationRow2196 rho) :
    rho 1860 = Shieldd.GnarkFormal.Poseidon2Bridge.p17
      (block4RoundInput3 rho) := by
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TGadgetPoseidonEncryptionDetection_cb69c394a6636349ef1ca32ae7f664980eedd6a7010cb2a2d96541cc47984b25.relationRow2192 at h2192
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TGadgetPoseidonEncryptionDetection_cb69c394a6636349ef1ca32ae7f664980eedd6a7010cb2a2d96541cc47984b25.relationRow2193 at h2193
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TGadgetPoseidonEncryptionDetection_cb69c394a6636349ef1ca32ae7f664980eedd6a7010cb2a2d96541cc47984b25.relationRow2194 at h2194
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TGadgetPoseidonEncryptionDetection_cb69c394a6636349ef1ca32ae7f664980eedd6a7010cb2a2d96541cc47984b25.relationRow2195 at h2195
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TGadgetPoseidonEncryptionDetection_cb69c394a6636349ef1ca32ae7f664980eedd6a7010cb2a2d96541cc47984b25.relationRow2196 at h2196
  have hblock4Input3 : block4RoundInput3 rho = (5449784062177697673672326237764238453778065127365215466720972346486959480802 : F) + (7037051457856975353540687448984622109479916112628386523279361213264507699201 : F) * rho 1845 := by
    unfold block4RoundInput3
    rfl
  apply Shieldd.GnarkFormal.Deployed.Templates.Semantics.TransferPoseidon2Trace.p17_from_rows
      (block4RoundInput3 rho)
      (rho 1856) (rho 1857) (rho 1858) (rho 1859) (rho 1860)
  · rw [hblock4Input3]; linear_combination h2192
  · linear_combination h2193
  · linear_combination h2194
  · linear_combination h2195
  · rw [hblock4Input3]; linear_combination h2196

theorem sound (rho : Nat → F)
    (h : Shieldd.GnarkFormal.Deployed.Templates.Relations.TGadgetPoseidonEncryptionDetection_cb69c394a6636349ef1ca32ae7f664980eedd6a7010cb2a2d96541cc47984b25.relation rho)
    (hPrev : Shieldd.GnarkFormal.Deployed.Templates.Semantics.TransferPoseidon2Trace.state0 block4Domain (block4Input0 rho) (block4Input1 rho) = block4Endpoint0 rho) :
    Shieldd.GnarkFormal.Deployed.Templates.Semantics.TransferPoseidon2Trace.state1 block4Domain (block4Input0 rho)
      (block4Input1 rho) = block4Endpoint1 rho := by
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TGadgetPoseidonEncryptionDetection_cb69c394a6636349ef1ca32ae7f664980eedd6a7010cb2a2d96541cc47984b25.relation at h
  rcases h with ⟨
    _, _, _, _, _, _, _, _,
    _, _, _, _, _, _, _, _,
    _, _, _, _, _, _, _, _,
    _, _, _, p27, _, _, _
  ⟩
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TGadgetPoseidonEncryptionDetection_cb69c394a6636349ef1ca32ae7f664980eedd6a7010cb2a2d96541cc47984b25.relationPart27 at p27
  rcases p27 with ⟨_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, h2182, h2183, h2184, h2185, h2186, h2187, h2188, h2189, h2190, h2191, h2192, h2193, h2194, h2195, h2196, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _⟩
  have hp1 := block4Part1 rho h2182 h2183 h2184 h2185 h2186
  have hp2 := block4Part2 rho h2187 h2188 h2189 h2190 h2191
  have hp3 := block4Part3 rho h2192 h2193 h2194 h2195 h2196
  have ha0 : rho 1850 =
      Shieldd.GnarkFormal.Poseidon2Bridge.p17
        ((block4Endpoint0 rho)[0] +
          (1216889461603982466063117074419064018993731784023337352219629352951004218382 : F)) := by
    rw [hp1, block4RoundInput1_eq_arg]
  have ha1 : rho 1855 =
      Shieldd.GnarkFormal.Poseidon2Bridge.p17
        ((block4Endpoint0 rho)[1] +
          (4580374146984258872617301222640071415348151863297599652351895199406510624060 : F)) := by
    rw [hp2, block4RoundInput2_eq_arg]
  have ha2 : rho 1860 =
      Shieldd.GnarkFormal.Poseidon2Bridge.p17
        ((block4Endpoint0 rho)[2] +
          (5287771711632967718595430906600106184880872479312192055075552617141548501299 : F)) := by
    rw [hp3, block4RoundInput3_eq_arg]
  have hCurrent : Shieldd.GnarkFormal.Deployed.Templates.Semantics.TransferPoseidon2Trace.state1 block4Domain (block4Input0 rho) (block4Input1 rho) = block4Endpoint1 rho := by
    unfold Shieldd.GnarkFormal.Deployed.Templates.Semantics.TransferPoseidon2Trace.state1
    rw [hPrev]
    rw [Shieldd.GnarkFormal.Deployed.Poseidon2Link.fr_eq3
      (block4Endpoint0 rho) Shieldd.GnarkFormal.Deployed.Templates.Semantics.TransferPoseidon2Trace.roundConstants1
      (rho 1850) (rho 1855) (rho 1860)
      ha0 ha1 ha2]
    apply List.Vector.eq
    simp [block4Endpoint1, Shieldd.GnarkFormal.Deployed.Poseidon2Link.row3, Shieldd.GnarkFormal.Deployed.Templates.Semantics.TransferPoseidon2Trace.roundConstants1, block4Endpoint0]
  exact hCurrent

end Shieldd.GnarkFormal.Deployed.Templates.Semantics.TGadgetPoseidonEncryptionDetection_cb69c394a6636349ef1ca32ae7f664980eedd6a7010cb2a2d96541cc47984b25Poseidon.Block4.Gate1
