/-
GENERATED by gen/gen_certified_composite_semantics.py -- do not edit.
-/
import ShielddGnarkFormal.Deployed.Templates.Semantics.TGadgetPoseidonEncryptionDetection_63775682d65609fcb7205087c01734b96d2d3337f3d614c8ffd568df5c38c49cPoseidonBlock0Base
import ShielddGnarkFormal.Deployed.Templates.Relations.TGadgetPoseidonEncryptionDetection_63775682d65609fcb7205087c01734b96d2d3337f3d614c8ffd568df5c38c49c
import ShielddGnarkFormal.Deployed.Poseidon2Link
import Mathlib.Tactic.LinearCombination
import Mathlib.Tactic.Ring

set_option maxRecDepth 1000000
set_option maxHeartbeats 10000000

namespace Shieldd.GnarkFormal.Deployed.Templates.Semantics.TGadgetPoseidonEncryptionDetection_63775682d65609fcb7205087c01734b96d2d3337f3d614c8ffd568df5c38c49cPoseidon.Block0.Gate37

open Shieldd.GnarkFormal.Deployed.Templates.Semantics.TGadgetPoseidonEncryptionDetection_63775682d65609fcb7205087c01734b96d2d3337f3d614c8ffd568df5c38c49cPoseidon.Block0
attribute [-instance] ZMod.instField
open scoped Shieldd.GnarkFormal.ChoiceFreeZMod

theorem block0Part48 (rho : Nat → F) (h1352 : Shieldd.GnarkFormal.Deployed.Templates.Relations.TGadgetPoseidonEncryptionDetection_63775682d65609fcb7205087c01734b96d2d3337f3d614c8ffd568df5c38c49c.relationRow1352 rho) (h1353 : Shieldd.GnarkFormal.Deployed.Templates.Relations.TGadgetPoseidonEncryptionDetection_63775682d65609fcb7205087c01734b96d2d3337f3d614c8ffd568df5c38c49c.relationRow1353 rho) (h1354 : Shieldd.GnarkFormal.Deployed.Templates.Relations.TGadgetPoseidonEncryptionDetection_63775682d65609fcb7205087c01734b96d2d3337f3d614c8ffd568df5c38c49c.relationRow1354 rho) (h1355 : Shieldd.GnarkFormal.Deployed.Templates.Relations.TGadgetPoseidonEncryptionDetection_63775682d65609fcb7205087c01734b96d2d3337f3d614c8ffd568df5c38c49c.relationRow1355 rho) (h1356 : Shieldd.GnarkFormal.Deployed.Templates.Relations.TGadgetPoseidonEncryptionDetection_63775682d65609fcb7205087c01734b96d2d3337f3d614c8ffd568df5c38c49c.relationRow1356 rho) :
    rho 1020 = Shieldd.GnarkFormal.Poseidon2Bridge.p17
      (block0RoundInput48 rho) := by
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TGadgetPoseidonEncryptionDetection_63775682d65609fcb7205087c01734b96d2d3337f3d614c8ffd568df5c38c49c.relationRow1352 at h1352
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TGadgetPoseidonEncryptionDetection_63775682d65609fcb7205087c01734b96d2d3337f3d614c8ffd568df5c38c49c.relationRow1353 at h1353
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TGadgetPoseidonEncryptionDetection_63775682d65609fcb7205087c01734b96d2d3337f3d614c8ffd568df5c38c49c.relationRow1354 at h1354
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TGadgetPoseidonEncryptionDetection_63775682d65609fcb7205087c01734b96d2d3337f3d614c8ffd568df5c38c49c.relationRow1355 at h1355
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TGadgetPoseidonEncryptionDetection_63775682d65609fcb7205087c01734b96d2d3337f3d614c8ffd568df5c38c49c.relationRow1356 at h1356
  have hblock0Input48 : block0RoundInput48 rho = (2433763979138972299522164212362097495457810156842620348670661190742330717004 : F) + (5629641166285580282832549959187697687583932890102709218623488970611606159361 : F) * rho 1005 + (6333346312071277818186618704086159898531924501365547870951425091938056929281 : F) * rho 1010 + (6755569399542696339399059951025237225100719468123251062348186764733927391233 : F) * rho 1015 := by
    unfold block0RoundInput48
    rfl
  apply Shieldd.GnarkFormal.Deployed.Templates.Semantics.TransferPoseidon2Trace.p17_from_rows
      (block0RoundInput48 rho)
      (rho 1016) (rho 1017) (rho 1018) (rho 1019) (rho 1020)
  · rw [hblock0Input48]; linear_combination h1352
  · linear_combination h1353
  · linear_combination h1354
  · linear_combination h1355
  · rw [hblock0Input48]; linear_combination h1356

theorem block0Part49 (rho : Nat → F) (h1357 : Shieldd.GnarkFormal.Deployed.Templates.Relations.TGadgetPoseidonEncryptionDetection_63775682d65609fcb7205087c01734b96d2d3337f3d614c8ffd568df5c38c49c.relationRow1357 rho) (h1358 : Shieldd.GnarkFormal.Deployed.Templates.Relations.TGadgetPoseidonEncryptionDetection_63775682d65609fcb7205087c01734b96d2d3337f3d614c8ffd568df5c38c49c.relationRow1358 rho) (h1359 : Shieldd.GnarkFormal.Deployed.Templates.Relations.TGadgetPoseidonEncryptionDetection_63775682d65609fcb7205087c01734b96d2d3337f3d614c8ffd568df5c38c49c.relationRow1359 rho) (h1360 : Shieldd.GnarkFormal.Deployed.Templates.Relations.TGadgetPoseidonEncryptionDetection_63775682d65609fcb7205087c01734b96d2d3337f3d614c8ffd568df5c38c49c.relationRow1360 rho) (h1361 : Shieldd.GnarkFormal.Deployed.Templates.Relations.TGadgetPoseidonEncryptionDetection_63775682d65609fcb7205087c01734b96d2d3337f3d614c8ffd568df5c38c49c.relationRow1361 rho) :
    rho 1025 = Shieldd.GnarkFormal.Poseidon2Bridge.p17
      (block0RoundInput49 rho) := by
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TGadgetPoseidonEncryptionDetection_63775682d65609fcb7205087c01734b96d2d3337f3d614c8ffd568df5c38c49c.relationRow1357 at h1357
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TGadgetPoseidonEncryptionDetection_63775682d65609fcb7205087c01734b96d2d3337f3d614c8ffd568df5c38c49c.relationRow1358 at h1358
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TGadgetPoseidonEncryptionDetection_63775682d65609fcb7205087c01734b96d2d3337f3d614c8ffd568df5c38c49c.relationRow1359 at h1359
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TGadgetPoseidonEncryptionDetection_63775682d65609fcb7205087c01734b96d2d3337f3d614c8ffd568df5c38c49c.relationRow1360 at h1360
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TGadgetPoseidonEncryptionDetection_63775682d65609fcb7205087c01734b96d2d3337f3d614c8ffd568df5c38c49c.relationRow1361 at h1361
  have hblock0Input49 : block0RoundInput49 rho = (983738301417603757808483219105286248075595155162538643758190406964355750696 : F) + (6333346312071277818186618704086159898531924501365547870951425091938056929281 : F) * rho 1005 + (6755569399542696339399059951025237225100719468123251062348186764733927391233 : F) * rho 1010 + (7037051457856975353540687448984622109479916112628386523279361213264507699201 : F) * rho 1015 := by
    unfold block0RoundInput49
    rfl
  apply Shieldd.GnarkFormal.Deployed.Templates.Semantics.TransferPoseidon2Trace.p17_from_rows
      (block0RoundInput49 rho)
      (rho 1021) (rho 1022) (rho 1023) (rho 1024) (rho 1025)
  · rw [hblock0Input49]; linear_combination h1357
  · linear_combination h1358
  · linear_combination h1359
  · linear_combination h1360
  · rw [hblock0Input49]; linear_combination h1361

theorem block0Part50 (rho : Nat → F) (h1362 : Shieldd.GnarkFormal.Deployed.Templates.Relations.TGadgetPoseidonEncryptionDetection_63775682d65609fcb7205087c01734b96d2d3337f3d614c8ffd568df5c38c49c.relationRow1362 rho) (h1363 : Shieldd.GnarkFormal.Deployed.Templates.Relations.TGadgetPoseidonEncryptionDetection_63775682d65609fcb7205087c01734b96d2d3337f3d614c8ffd568df5c38c49c.relationRow1363 rho) (h1364 : Shieldd.GnarkFormal.Deployed.Templates.Relations.TGadgetPoseidonEncryptionDetection_63775682d65609fcb7205087c01734b96d2d3337f3d614c8ffd568df5c38c49c.relationRow1364 rho) (h1365 : Shieldd.GnarkFormal.Deployed.Templates.Relations.TGadgetPoseidonEncryptionDetection_63775682d65609fcb7205087c01734b96d2d3337f3d614c8ffd568df5c38c49c.relationRow1365 rho) (h1366 : Shieldd.GnarkFormal.Deployed.Templates.Relations.TGadgetPoseidonEncryptionDetection_63775682d65609fcb7205087c01734b96d2d3337f3d614c8ffd568df5c38c49c.relationRow1366 rho) :
    rho 1030 = Shieldd.GnarkFormal.Poseidon2Bridge.p17
      (block0RoundInput50 rho) := by
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TGadgetPoseidonEncryptionDetection_63775682d65609fcb7205087c01734b96d2d3337f3d614c8ffd568df5c38c49c.relationRow1362 at h1362
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TGadgetPoseidonEncryptionDetection_63775682d65609fcb7205087c01734b96d2d3337f3d614c8ffd568df5c38c49c.relationRow1363 at h1363
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TGadgetPoseidonEncryptionDetection_63775682d65609fcb7205087c01734b96d2d3337f3d614c8ffd568df5c38c49c.relationRow1364 at h1364
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TGadgetPoseidonEncryptionDetection_63775682d65609fcb7205087c01734b96d2d3337f3d614c8ffd568df5c38c49c.relationRow1365 at h1365
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TGadgetPoseidonEncryptionDetection_63775682d65609fcb7205087c01734b96d2d3337f3d614c8ffd568df5c38c49c.relationRow1366 at h1366
  have hblock0Input50 : block0RoundInput50 rho = (209202405659177692545688490614016438006505568346018036573546364833013030573 : F) + (6755569399542696339399059951025237225100719468123251062348186764733927391233 : F) * rho 1005 + (7037051457856975353540687448984622109479916112628386523279361213264507699201 : F) * rho 1010 + (7238110070938603220784707090384182741179342287274911852515914390786350776321 : F) * rho 1015 := by
    unfold block0RoundInput50
    rfl
  apply Shieldd.GnarkFormal.Deployed.Templates.Semantics.TransferPoseidon2Trace.p17_from_rows
      (block0RoundInput50 rho)
      (rho 1026) (rho 1027) (rho 1028) (rho 1029) (rho 1030)
  · rw [hblock0Input50]; linear_combination h1362
  · linear_combination h1363
  · linear_combination h1364
  · linear_combination h1365
  · rw [hblock0Input50]; linear_combination h1366

theorem sound (rho : Nat → F)
    (h : Shieldd.GnarkFormal.Deployed.Templates.Relations.TGadgetPoseidonEncryptionDetection_63775682d65609fcb7205087c01734b96d2d3337f3d614c8ffd568df5c38c49c.relation rho)
    (hPrev : Shieldd.GnarkFormal.Deployed.Templates.Semantics.TransferPoseidon2Trace.state36 block0Domain (block0Input0 rho) (block0Input1 rho) = block0Endpoint36 rho) :
    Shieldd.GnarkFormal.Deployed.Templates.Semantics.TransferPoseidon2Trace.state37 block0Domain (block0Input0 rho)
      (block0Input1 rho) = block0Endpoint37 rho := by
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TGadgetPoseidonEncryptionDetection_63775682d65609fcb7205087c01734b96d2d3337f3d614c8ffd568df5c38c49c.relation at h
  rcases h with ⟨
    _, _, _, _, _, _, _, _,
    _, _, _, _, _, _, _, _,
    p16, p17, _, _, _, _, _, _,
    _, _, _, _, _, _, _
  ⟩
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TGadgetPoseidonEncryptionDetection_63775682d65609fcb7205087c01734b96d2d3337f3d614c8ffd568df5c38c49c.relationPart16 at p16
  rcases p16 with ⟨_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, h1352, h1353, h1354, h1355, h1356, h1357, h1358, h1359⟩
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TGadgetPoseidonEncryptionDetection_63775682d65609fcb7205087c01734b96d2d3337f3d614c8ffd568df5c38c49c.relationPart17 at p17
  rcases p17 with ⟨h1360, h1361, h1362, h1363, h1364, h1365, h1366, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _⟩
  have hp48 := block0Part48 rho h1352 h1353 h1354 h1355 h1356
  have hp49 := block0Part49 rho h1357 h1358 h1359 h1360 h1361
  have hp50 := block0Part50 rho h1362 h1363 h1364 h1365 h1366
  have ha0 : rho 1020 =
      Shieldd.GnarkFormal.Poseidon2Bridge.p17
        ((block0Endpoint36 rho)[0] +
          (2433763979138972299522164212362097495457810156842620348670661190742330717004 : F)) := by
    rw [hp48, block0RoundInput48_eq_arg]
  have ha1 : rho 1025 =
      Shieldd.GnarkFormal.Poseidon2Bridge.p17
        ((block0Endpoint36 rho)[1] +
          (983738301417603757808483219105286248075595155162538643758190406964355750696 : F)) := by
    rw [hp49, block0RoundInput49_eq_arg]
  have ha2 : rho 1030 =
      Shieldd.GnarkFormal.Poseidon2Bridge.p17
        ((block0Endpoint36 rho)[2] +
          (209202405659177692545688490614016438006505568346018036573546364833013030573 : F)) := by
    rw [hp50, block0RoundInput50_eq_arg]
  have hCurrent : Shieldd.GnarkFormal.Deployed.Templates.Semantics.TransferPoseidon2Trace.state37 block0Domain (block0Input0 rho) (block0Input1 rho) = block0Endpoint37 rho := by
    unfold Shieldd.GnarkFormal.Deployed.Templates.Semantics.TransferPoseidon2Trace.state37
    rw [hPrev]
    rw [Shieldd.GnarkFormal.Deployed.Poseidon2Link.fr_eq3
      (block0Endpoint36 rho) Shieldd.GnarkFormal.Deployed.Templates.Semantics.TransferPoseidon2Trace.roundConstants37
      (rho 1020) (rho 1025) (rho 1030)
      ha0 ha1 ha2]
    apply List.Vector.eq
    simp [block0Endpoint37, Shieldd.GnarkFormal.Deployed.Poseidon2Link.row3, Shieldd.GnarkFormal.Deployed.Templates.Semantics.TransferPoseidon2Trace.roundConstants37, block0Endpoint36]
  exact hCurrent

end Shieldd.GnarkFormal.Deployed.Templates.Semantics.TGadgetPoseidonEncryptionDetection_63775682d65609fcb7205087c01734b96d2d3337f3d614c8ffd568df5c38c49cPoseidon.Block0.Gate37
