/-
GENERATED by gen/gen_certified_statement_hash_semantics.py -- do not edit.
-/
import ShielddGnarkFormal.ChoiceFreeZMod
import ShielddGnarkFormal.Deployed.Templates.Relations.TStatementHash_042c03f6fbeb384ad6230b63ee320b87cd0d4f74a820f0cac6e6f7499e9350bd
import ShielddGnarkFormal.Deployed.StatementHashDeployedBridge
import ShielddGnarkFormal.Deployed.PrimeOrderCertificate
import Mathlib.Tactic.LinearCombination

set_option maxRecDepth 1000000
set_option maxHeartbeats 20000000

namespace Shieldd.GnarkFormal.Deployed.Templates.Semantics.TStatementHash_042c03f6fbeb384ad6230b63ee320b87cd0d4f74a820f0cac6e6f7499e9350bd.Part108

open scoped Shieldd.GnarkFormal.ChoiceFreeZMod

abbrev Order : Nat := Shieldd.GnarkFormal.Extracted.Deployed.StatementHash470_5c3d95.Order
abbrev F := Shieldd.GnarkFormal.Extracted.Deployed.StatementHash470_5c3d95.F

local instance : Fact (Nat.Prime Order) :=
  ⟨Shieldd.GnarkFormal.Deployed.decaf377ScalarFieldPrime⟩

theorem sound (rho : Nat → F)
    (h : Shieldd.GnarkFormal.Deployed.Templates.Relations.TStatementHash_042c03f6fbeb384ad6230b63ee320b87cd0d4f74a820f0cac6e6f7499e9350bd.relationPart108 rho) :
    rho 561 = Shieldd.GnarkFormal.Poseidon7Bridge.p17 ((668162892374950427662549511154762981360347712424398661730228079012540764160 : F) + (7916682890089097272733273380107699873164905626706934838689281364922571161601 : F) * rho 484 + (5464063484924239686278651430976294814419699569805570712193386353828911860556 : F) * rho 491 + (2345683819285658451180229149661540703159972037542795507759787071088169233067 : F) * rho 497 + (5777789618029937658696564431797900258309825860894885777008317627732964216186 : F) * rho 503 + (8022238661956951903036383691842469204807104368396360636538471783121538777089 : F) * rho 509 + (8042344523265114689760785655982425267977046985861013169462127100873723084801 : F) * rho 515 + (1151517511285686876033930673470210890642168091157372340172986380352373987142 : F) * rho 521) := by
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TStatementHash_042c03f6fbeb384ad6230b63ee320b87cd0d4f74a820f0cac6e6f7499e9350bd.relationPart108 Shieldd.GnarkFormal.Deployed.Templates.Relations.TStatementHash_042c03f6fbeb384ad6230b63ee320b87cd0d4f74a820f0cac6e6f7499e9350bd.relationRow540 Shieldd.GnarkFormal.Deployed.Templates.Relations.TStatementHash_042c03f6fbeb384ad6230b63ee320b87cd0d4f74a820f0cac6e6f7499e9350bd.relationRow541 Shieldd.GnarkFormal.Deployed.Templates.Relations.TStatementHash_042c03f6fbeb384ad6230b63ee320b87cd0d4f74a820f0cac6e6f7499e9350bd.relationRow542 Shieldd.GnarkFormal.Deployed.Templates.Relations.TStatementHash_042c03f6fbeb384ad6230b63ee320b87cd0d4f74a820f0cac6e6f7499e9350bd.relationRow543 Shieldd.GnarkFormal.Deployed.Templates.Relations.TStatementHash_042c03f6fbeb384ad6230b63ee320b87cd0d4f74a820f0cac6e6f7499e9350bd.relationRow544 at h
  rcases h with ⟨h0, h1, h2, h3, h4⟩

  exact Shieldd.GnarkFormal.Deployed.StatementHash.p17_from_rows
    ((668162892374950427662549511154762981360347712424398661730228079012540764160 : F) + (7916682890089097272733273380107699873164905626706934838689281364922571161601 : F) * rho 484 + (5464063484924239686278651430976294814419699569805570712193386353828911860556 : F) * rho 491 + (2345683819285658451180229149661540703159972037542795507759787071088169233067 : F) * rho 497 + (5777789618029937658696564431797900258309825860894885777008317627732964216186 : F) * rho 503 + (8022238661956951903036383691842469204807104368396360636538471783121538777089 : F) * rho 509 + (8042344523265114689760785655982425267977046985861013169462127100873723084801 : F) * rho 515 + (1151517511285686876033930673470210890642168091157372340172986380352373987142 : F) * rho 521) (rho 557) (rho 558) (rho 559) (rho 560) (rho 561)
    (by simpa only [one_mul] using h0)
    (by simpa only [one_mul] using h1)
    (by simpa only [one_mul] using h2)
    (by simpa only [one_mul] using h3)
    (by simpa only [one_mul] using h4)

end Shieldd.GnarkFormal.Deployed.Templates.Semantics.TStatementHash_042c03f6fbeb384ad6230b63ee320b87cd0d4f74a820f0cac6e6f7499e9350bd.Part108
