/-
GENERATED by gen/gen_certified_statement_hash_semantics.py -- do not edit.
-/
import ShielddGnarkFormal.ChoiceFreeZMod
import ShielddGnarkFormal.Deployed.Templates.Relations.TStatementHash_0cf7625f3041ed713c8f3634f6d3914aad6059b5f8113ba50facad312738e969
import ShielddGnarkFormal.Deployed.StatementHashDeployedBridge
import ShielddGnarkFormal.Deployed.PrimeOrderCertificate
import Mathlib.Tactic.LinearCombination

set_option maxRecDepth 1000000
set_option maxHeartbeats 20000000

namespace Shieldd.GnarkFormal.Deployed.Templates.Semantics.TStatementHash_0cf7625f3041ed713c8f3634f6d3914aad6059b5f8113ba50facad312738e969.Part8

open scoped Shieldd.GnarkFormal.ChoiceFreeZMod

abbrev Order : Nat := Shieldd.GnarkFormal.Extracted.Deployed.StatementHash470_5c3d95.Order
abbrev F := Shieldd.GnarkFormal.Extracted.Deployed.StatementHash470_5c3d95.F

local instance : Fact (Nat.Prime Order) :=
  ⟨Shieldd.GnarkFormal.Deployed.decaf377ScalarFieldPrime⟩

theorem sound (rho : Nat → F)
    (h : Shieldd.GnarkFormal.Deployed.Templates.Relations.TStatementHash_0cf7625f3041ed713c8f3634f6d3914aad6059b5f8113ba50facad312738e969.relationPart8 rho) :
    rho 56 = Shieldd.GnarkFormal.Poseidon7Bridge.p17 ((6048090055695718336164316388430610261157901704700994584504723673529095059297 : F) + (7794887768703111160845069174259889105885445540142212764247907805462223912961 : F) * rho 13 + (7841285910183486822516766014582864636277620811214487840225573923351880007681 : F) * rho 19 + (7881497632799812395965569942862776762617506046143792906072884558856248623105 : F) * rho 25 + (7916682890089097272733273380107699873164905626706934838689281364922571161601 : F) * rho 31) := by
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TStatementHash_0cf7625f3041ed713c8f3634f6d3914aad6059b5f8113ba50facad312738e969.relationPart8 Shieldd.GnarkFormal.Deployed.Templates.Relations.TStatementHash_0cf7625f3041ed713c8f3634f6d3914aad6059b5f8113ba50facad312738e969.relationRow40 Shieldd.GnarkFormal.Deployed.Templates.Relations.TStatementHash_0cf7625f3041ed713c8f3634f6d3914aad6059b5f8113ba50facad312738e969.relationRow41 Shieldd.GnarkFormal.Deployed.Templates.Relations.TStatementHash_0cf7625f3041ed713c8f3634f6d3914aad6059b5f8113ba50facad312738e969.relationRow42 Shieldd.GnarkFormal.Deployed.Templates.Relations.TStatementHash_0cf7625f3041ed713c8f3634f6d3914aad6059b5f8113ba50facad312738e969.relationRow43 Shieldd.GnarkFormal.Deployed.Templates.Relations.TStatementHash_0cf7625f3041ed713c8f3634f6d3914aad6059b5f8113ba50facad312738e969.relationRow44 at h
  rcases h with ⟨h0, h1, h2, h3, h4⟩

  exact Shieldd.GnarkFormal.Deployed.StatementHash.p17_from_rows
    ((6048090055695718336164316388430610261157901704700994584504723673529095059297 : F) + (7794887768703111160845069174259889105885445540142212764247907805462223912961 : F) * rho 13 + (7841285910183486822516766014582864636277620811214487840225573923351880007681 : F) * rho 19 + (7881497632799812395965569942862776762617506046143792906072884558856248623105 : F) * rho 25 + (7916682890089097272733273380107699873164905626706934838689281364922571161601 : F) * rho 31) (rho 52) (rho 53) (rho 54) (rho 55) (rho 56)
    (by simpa only [one_mul] using h0)
    (by simpa only [one_mul] using h1)
    (by simpa only [one_mul] using h2)
    (by simpa only [one_mul] using h3)
    (by simpa only [one_mul] using h4)

end Shieldd.GnarkFormal.Deployed.Templates.Semantics.TStatementHash_0cf7625f3041ed713c8f3634f6d3914aad6059b5f8113ba50facad312738e969.Part8
