/-
GENERATED by gen/gen_certified_statement_hash_semantics.py -- do not edit.
-/
import ShielddGnarkFormal.ChoiceFreeZMod
import ShielddGnarkFormal.Deployed.Templates.Relations.TStatementHash_0e54d8ea5fc5d0d95e113695b4b0340e4b6bab4d5abb13df4d51436c93755a86
import ShielddGnarkFormal.Deployed.StatementHashDeployedBridge
import ShielddGnarkFormal.Deployed.PrimeOrderCertificate
import Mathlib.Tactic.LinearCombination

set_option maxRecDepth 1000000
set_option maxHeartbeats 20000000

namespace Shieldd.GnarkFormal.Deployed.Templates.Semantics.TStatementHash_0e54d8ea5fc5d0d95e113695b4b0340e4b6bab4d5abb13df4d51436c93755a86.Part390

open scoped Shieldd.GnarkFormal.ChoiceFreeZMod

abbrev Order : Nat := Shieldd.GnarkFormal.Extracted.Deployed.StatementHash470_5c3d95.Order
abbrev F := Shieldd.GnarkFormal.Extracted.Deployed.StatementHash470_5c3d95.F

local instance : Fact (Nat.Prime Order) :=
  ⟨Shieldd.GnarkFormal.Deployed.decaf377ScalarFieldPrime⟩

theorem sound (rho : Nat → F)
    (h : Shieldd.GnarkFormal.Deployed.Templates.Relations.TStatementHash_0e54d8ea5fc5d0d95e113695b4b0340e4b6bab4d5abb13df4d51436c93755a86.relationPart390 rho) :
    rho 1992 = Shieldd.GnarkFormal.Poseidon7Bridge.p17 ((3701445319960685500187372866839573788911562434003838334630494362033395661150 : F) + (7916682890089097272733273380107699873164905626706934838689281364922571161601 : F) * rho 1915 + (5464063484924239686278651430976294814419699569805570712193386353828911860556 : F) * rho 1921 + (2345683819285658451180229149661540703159972037542795507759787071088169233067 : F) * rho 1927 + (5777789618029937658696564431797900258309825860894885777008317627732964216186 : F) * rho 1933 + (8022238661956951903036383691842469204807104368396360636538471783121538777089 : F) * rho 1940 + (8042344523265114689760785655982425267977046985861013169462127100873723084801 : F) * rho 1946 + (1151517511285686876033930673470210890642168091157372340172986380352373987142 : F) * rho 1952) := by
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TStatementHash_0e54d8ea5fc5d0d95e113695b4b0340e4b6bab4d5abb13df4d51436c93755a86.relationPart390 Shieldd.GnarkFormal.Deployed.Templates.Relations.TStatementHash_0e54d8ea5fc5d0d95e113695b4b0340e4b6bab4d5abb13df4d51436c93755a86.relationRow1950 Shieldd.GnarkFormal.Deployed.Templates.Relations.TStatementHash_0e54d8ea5fc5d0d95e113695b4b0340e4b6bab4d5abb13df4d51436c93755a86.relationRow1951 Shieldd.GnarkFormal.Deployed.Templates.Relations.TStatementHash_0e54d8ea5fc5d0d95e113695b4b0340e4b6bab4d5abb13df4d51436c93755a86.relationRow1952 Shieldd.GnarkFormal.Deployed.Templates.Relations.TStatementHash_0e54d8ea5fc5d0d95e113695b4b0340e4b6bab4d5abb13df4d51436c93755a86.relationRow1953 Shieldd.GnarkFormal.Deployed.Templates.Relations.TStatementHash_0e54d8ea5fc5d0d95e113695b4b0340e4b6bab4d5abb13df4d51436c93755a86.relationRow1954 at h
  rcases h with ⟨h0, h1, h2, h3, h4⟩

  exact Shieldd.GnarkFormal.Deployed.StatementHash.p17_from_rows
    ((3701445319960685500187372866839573788911562434003838334630494362033395661150 : F) + (7916682890089097272733273380107699873164905626706934838689281364922571161601 : F) * rho 1915 + (5464063484924239686278651430976294814419699569805570712193386353828911860556 : F) * rho 1921 + (2345683819285658451180229149661540703159972037542795507759787071088169233067 : F) * rho 1927 + (5777789618029937658696564431797900258309825860894885777008317627732964216186 : F) * rho 1933 + (8022238661956951903036383691842469204807104368396360636538471783121538777089 : F) * rho 1940 + (8042344523265114689760785655982425267977046985861013169462127100873723084801 : F) * rho 1946 + (1151517511285686876033930673470210890642168091157372340172986380352373987142 : F) * rho 1952) (rho 1988) (rho 1989) (rho 1990) (rho 1991) (rho 1992)
    (by simpa only [one_mul] using h0)
    (by simpa only [one_mul] using h1)
    (by simpa only [one_mul] using h2)
    (by simpa only [one_mul] using h3)
    (by simpa only [one_mul] using h4)

end Shieldd.GnarkFormal.Deployed.Templates.Semantics.TStatementHash_0e54d8ea5fc5d0d95e113695b4b0340e4b6bab4d5abb13df4d51436c93755a86.Part390
