/-
GENERATED by gen/gen_certified_statement_hash_semantics.py -- do not edit.
-/
import ShielddGnarkFormal.ChoiceFreeZMod
import ShielddGnarkFormal.Deployed.Templates.Relations.TStatementHash_f091e489b9a220b0436835ce5343e78627a43408ea621e9d71e60917c2e7c77f
import ShielddGnarkFormal.Deployed.StatementHashDeployedBridge
import ShielddGnarkFormal.Deployed.PrimeOrderCertificate
import Mathlib.Tactic.LinearCombination

set_option maxRecDepth 1000000
set_option maxHeartbeats 20000000

namespace Shieldd.GnarkFormal.Deployed.Templates.Semantics.TStatementHash_f091e489b9a220b0436835ce5343e78627a43408ea621e9d71e60917c2e7c77f.Part660

open scoped Shieldd.GnarkFormal.ChoiceFreeZMod

abbrev Order : Nat := Shieldd.GnarkFormal.Extracted.Deployed.StatementHash470_5c3d95.Order
abbrev F := Shieldd.GnarkFormal.Extracted.Deployed.StatementHash470_5c3d95.F

local instance : Fact (Nat.Prime Order) :=
  ⟨Shieldd.GnarkFormal.Deployed.decaf377ScalarFieldPrime⟩

theorem sound (rho : Nat → F)
    (h : Shieldd.GnarkFormal.Deployed.Templates.Relations.TStatementHash_f091e489b9a220b0436835ce5343e78627a43408ea621e9d71e60917c2e7c77f.relationPart660 rho) :
    rho 3356 = Shieldd.GnarkFormal.Poseidon7Bridge.p17 ((2855829734933438757468663790345339760547398211463821325869404910462386849302 : F) + (4691367638571316902360458299323081406319944075085591015519574142176338466134 : F) * rho 3345 + (7600015574485533381823942444903391878238309401638657445141710110325668315137 : F) * rho 3351) := by
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TStatementHash_f091e489b9a220b0436835ce5343e78627a43408ea621e9d71e60917c2e7c77f.relationPart660 Shieldd.GnarkFormal.Deployed.Templates.Relations.TStatementHash_f091e489b9a220b0436835ce5343e78627a43408ea621e9d71e60917c2e7c77f.relationRow3300 Shieldd.GnarkFormal.Deployed.Templates.Relations.TStatementHash_f091e489b9a220b0436835ce5343e78627a43408ea621e9d71e60917c2e7c77f.relationRow3301 Shieldd.GnarkFormal.Deployed.Templates.Relations.TStatementHash_f091e489b9a220b0436835ce5343e78627a43408ea621e9d71e60917c2e7c77f.relationRow3302 Shieldd.GnarkFormal.Deployed.Templates.Relations.TStatementHash_f091e489b9a220b0436835ce5343e78627a43408ea621e9d71e60917c2e7c77f.relationRow3303 Shieldd.GnarkFormal.Deployed.Templates.Relations.TStatementHash_f091e489b9a220b0436835ce5343e78627a43408ea621e9d71e60917c2e7c77f.relationRow3304 at h
  rcases h with ⟨h0, h1, h2, h3, h4⟩

  exact Shieldd.GnarkFormal.Deployed.StatementHash.p17_from_rows
    ((2855829734933438757468663790345339760547398211463821325869404910462386849302 : F) + (4691367638571316902360458299323081406319944075085591015519574142176338466134 : F) * rho 3345 + (7600015574485533381823942444903391878238309401638657445141710110325668315137 : F) * rho 3351) (rho 3352) (rho 3353) (rho 3354) (rho 3355) (rho 3356)
    (by simpa only [one_mul] using h0)
    (by simpa only [one_mul] using h1)
    (by simpa only [one_mul] using h2)
    (by simpa only [one_mul] using h3)
    (by simpa only [one_mul] using h4)

end Shieldd.GnarkFormal.Deployed.Templates.Semantics.TStatementHash_f091e489b9a220b0436835ce5343e78627a43408ea621e9d71e60917c2e7c77f.Part660
