[package]
name = "shieldd-sdk-tct"
authors = {workspace = true}
repository = {workspace = true}
description = "The tiered commitment tree for Shieldd"
version = {workspace = true}
license = {workspace = true}
edition = {workspace = true}

[features]
internal = []
arbitrary = ["proptest", "proptest-derive"]
parallel = ["dep:rayon"]

[dependencies]
shieldd-sdk-crypto.workspace = true
ff.workspace = true
anyhow.workspace = true
async-trait = {workspace = true}
derivative = {workspace = true}
futures = {workspace = true}
getrandom = {workspace = true, features = ["js"]}
hash_hasher = "2"
hex = {workspace = true}
imbl = {workspace = true, features = ["serde"]}
once_cell = {workspace = true}
parking_lot = {workspace = true}
shieldd-sdk-proto = {workspace = true, default-features = true}
proptest = {workspace = true, optional = true}
proptest-derive = {workspace = true, optional = true}
rand = {workspace = true}
rayon = { version = "1.10", optional = true }
serde = {workspace = true, features = ["derive", "rc"]}
thiserror = {workspace = true}
tracing = {workspace = true}

[dev-dependencies]
shieldd-sdk-circuits.workspace = true
static_assertions = "1"
proptest = {workspace = true}
proptest-derive = {workspace = true}
serde_json = {workspace = true}
getrandom = {workspace = true}
