[package]
name = "shieldd-sdk-compliance"
authors = {workspace = true}
repository = {workspace = true}
description = "Compliance component implementation for Shieldd"
version = {workspace = true}
license = {workspace = true}
edition = {workspace = true}

[features]
component = [
    "cnidarium",
    "cnidarium-component",
    "ibc-proto",
    "shieldd-sdk-proto/cnidarium",
    "shieldd-sdk-proto/rpc",
    "shieldd-sdk-sct/component",
    "rusqlite",
    "tokio",
    "tonic",
]
default = ["component"]
sqlite-bundled = ["rusqlite/bundled"]
test-helpers = ["decaf377-ka"]
poc-orbis-v0 = ["dep:aes-gcm", "dep:hkdf"]

[dependencies]
anyhow = {workspace = true}
aes-gcm = {version = "0.10", optional = true}
ark-ff = {workspace = true}
base64 = {workspace = true}
ark-serialize = {workspace = true}
async-trait = {workspace = true}
bincode = {workspace = true}
cnidarium = {workspace = true, optional = true, default-features = true}
cnidarium-component = {workspace = true, optional = true, default-features = true}
decaf377 = {workspace = true, default-features = true}
decaf377-rdsa = {workspace = true}
decaf377-ka = {workspace = true, optional = true}
once_cell = {workspace = true}
shieldd-sdk-asset = {workspace = true, default-features = false}
shieldd-sdk-keys = {workspace = true, default-features = false}
shieldd-sdk-num = {workspace = true, default-features = false}
shieldd-sdk-proto = {workspace = true, default-features = false}
shieldd-sdk-sct = {workspace = true, default-features = false}
shieldd-sdk-tct = {workspace = true, default-features = false}
shieldd-sdk-txhash = {workspace = true, default-features = false}
poseidon377 = {workspace = true}
serde = {workspace = true, features = ["derive"]}
serde_json = {workspace = true}
sha2 = {workspace = true}
blake2b_simd = {workspace = true}
hex = {workspace = true}
hkdf = {version = "0.12", optional = true}
ibc-proto = {workspace = true, optional = true, default-features = false}
futures = {workspace = true}
rand_core = {workspace = true}
rusqlite = {version = "0.32", optional = true}
tendermint = {workspace = true}
tokio = {workspace = true, optional = true}
tonic = {workspace = true, optional = true}
tracing = {workspace = true}

[dev-dependencies]
decaf377-ka = {workspace = true}
shieldd-sdk-keys = {workspace = true, features = ["demo"]}
rand = {workspace = true}
serde_json = {workspace = true}
tempfile = {workspace = true}
tokio = {workspace = true, features = ["full"]}
