[package]
name = "shieldd-sdk-proto"
authors = {workspace = true}
repository = {workspace = true}
description = "Bindings and extension traits for Shieldd protobufs"
version = {workspace = true}
license = {workspace = true}
edition = {workspace = true}

[features]
rpc = ["dep:tonic"]
cnidarium = ["dep:cnidarium"]

[dependencies]
anyhow = {workspace = true}
async-trait = {workspace = true}
bech32 = {workspace = true}
bytes = {workspace = true, features = ["serde"]}
cnidarium = {workspace = true, optional = true, default-features = true}
decaf377-rdsa = {workspace = true}
futures = {workspace = true}
hex = {workspace = true}
ics23 = {workspace = true}
pbjson = {workspace = true}
pbjson-types = {workspace = true}
pin-project = {workspace = true}
prost = {workspace = true}
serde = {workspace = true, features = ["derive"]}
serde_json = {workspace = true}
tendermint = {workspace = true}
tonic = {workspace = true, optional = true}
tracing = {workspace = true}

[dependencies.ibc-proto]
workspace = true
default-features = false
features = [
    "std",
    "serde",
]
