[package]
name = "shieldd-sdk-tct-property-test"
authors = {workspace = true}
repository = {workspace = true}
description = "Property testing for the TCT, as a library"
version = {workspace = true}
license = {workspace = true}
edition = {workspace = true}
publish = false

[dev-dependencies]
anyhow = {workspace = true}
shieldd-sdk-tct = {workspace = true, features = ["arbitrary"], default-features = true}
proptest = {workspace = true}
proptest-derive = {workspace = true}
