name: docs-lint
on:
  pull_request:
  merge_group:
    types: [checks_requested]
  # Also support ad-hoc calls for workflow.
  workflow_call:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  rustdocs:
    # We use a custom script to generate the rustdoc index page,
    # and refactors to rust deps can break that generation. Let's ensure this script exits 0
    # on PRs, but we'll still only deploy after merge into main.
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
        with:
          lfs: true

      - uses: ./.github/actions/setup-nix-rust

      # Building with warm cache takes ~40s, depending on changes.
      - name: Build rustdocs
        run: nix develop .#nightly --command ./deployments/scripts/rust-docs
