name: formal-scheduled

on:
  schedule:
    - cron: '17 9 * * *' # dev
    - cron: '41 9 * * *' # main

permissions:
  contents: read
  packages: read

jobs:
  formal-dev:
    if: github.event.schedule == '17 9 * * *'
    uses: ./.github/workflows/formal.yml
    with:
      target_ref: dev

  provers-dev:
    if: github.event.schedule == '17 9 * * *'
    uses: ./.github/workflows/soundness-provers.yml
    with:
      target_ref: dev

  features-dev:
    if: github.event.schedule == '17 9 * * *'
    uses: ./.github/workflows/rust-features.yml
    with:
      target_ref: dev

  formal-main:
    if: github.event.schedule == '41 9 * * *'
    uses: ./.github/workflows/formal.yml
    with:
      target_ref: main

  provers-main:
    if: github.event.schedule == '41 9 * * *'
    uses: ./.github/workflows/soundness-provers.yml
    with:
      target_ref: main

  features-main:
    if: github.event.schedule == '41 9 * * *'
    uses: ./.github/workflows/rust-features.yml
    with:
      target_ref: main
