name: docs
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      image_tag:
        description: Deployment subdirectory for generated documentation.
        required: false
        type: string
  workflow_call:

jobs:

  # Renders and deploys protocol and API docs.
  # Would be faster if we parallelized it, but it's already <10m,
  # and only runs post-merge on main, so 10m isn't bad.
  build:
    timeout-minutes: 30
    runs-on: buildjet-16vcpu-ubuntu-2204
    steps:
      - name: Checkout the source code
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - name: install nix
        uses: nixbuild/nix-quick-install-action@60e9c39264d4714139af3cdf15f691b19eec3530 # v28

      - name: setup nix cache
        uses: nix-community/cache-nix-action@7df957e333c1e5da7721f60227dbba6d06080569 # v7.0.2
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-
          backend: buildjet

      - name: Load Rust caching
        uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # v2

      # Previously we used a GHA helper to look up the version, which was overkill.
      # Let's still log the version of the docs we intend to build.
      - name: Print version component of deployment path
        run: echo ${{ github.event.inputs.image_tag || github.ref_name }}

      - name: Build protocol spec
        run: cd docs/protocol/ && nix develop --command mdbook build

      - name: Move protocol spec to subdirectory
        run: |
          cd docs/protocol
          rm -rf firebase-tmp
          mkdir firebase-tmp
          mv book/html firebase-tmp/${{ github.event.inputs.image_tag || github.ref_name }}
          tree firebase-tmp

      - name: Deploy protocol spec to firebase
        uses: w9jds/firebase-action@27f890f050c1cccd01b032a19ebdf19808177159 # v12.9.0
        with:
          args: deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: shieldd-protocol
          PROJECT_PATH: docs/protocol

      - name: Build rustdocs
        run: nix develop .#nightly --command ./deployments/scripts/rust-docs

      - name: Move API docs to subdirectory
        run: |
          cd docs/rustdoc
          if [ -d "firebase-tmp" ]; then rm -rf firebase-tmp; fi
          mkdir firebase-tmp
          mv ../../target/doc firebase-tmp/${{ github.event.inputs.image_tag || github.ref_name }}
          # Copy in the static index file
          cp index.html firebase-tmp/${{ github.event.inputs.image_tag || github.ref_name }}

      - name: Deploy API docs to firebase
        uses: w9jds/firebase-action@27f890f050c1cccd01b032a19ebdf19808177159 # v12.9.0
        with:
          args: deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: shieldd-doc
          PROJECT_PATH: docs/rustdoc
